DROP TABLE IF EXISTS step1_case_fixes;
CREATE TEMP TABLE step1_case_fixes (attribute_code text, old_value text, new_value text);
INSERT INTO step1_case_fixes (attribute_code, old_value, new_value) VALUES
    ('COL', 'ITALIAN', 'Italian'),
    ('COL', 'BENGALI', 'Bengali'),
    ('COL', 'BIRTH STONE', 'Birth Stone'),
    ('COL', 'MECHINE', 'Machine'),
    ('STL', 'Rosary ', 'Rosary'),
    ('STL', 'NET', 'Net'),
    ('STL', 'CHARMS', 'Charms'),
    ('STL', 'CHETH', 'Cheth'),
    ('STL', 'HIGHWAY', 'Highway'),
    ('STL', 'PARASPARAM RODIUM', 'Parasparam Rodium'),
    ('STL', 'TIGHT ARANJAL', 'Tight Aranjal'),
    ('STL', 'NAKASHI', 'Nakashi'),
    ('STL', 'THREAD', 'Thread'),
    ('STL', 'HALF ROUND ENAMEL', 'Half Round Enamel'),
    ('STL', 'HALF ROUND STONE', 'Half Round Stone'),
    ('STL', 'PIPE', 'Pipe'),
    ('STL', 'PIPE ENAMEL', 'Pipe Enamel'),
    ('STL', 'LAKSHMI STONE', 'Lakshmi Stone'),
    ('STL', 'EYE', 'Eye'),
    ('STL', 'JAGUAR', 'Jaguar'),
    ('STL', 'LEAF', 'Leaf'),
    ('STL', 'SIMBA', 'Simba'),
    ('STL', 'CLOSED SETTING', 'Closed Setting'),
    ('STL', 'SCREW ENAMEL', 'Screw Enamel'),
    ('STL', 'CLUSTER', 'Cluster'),
    ('STL', 'OPEN CLOSE SETTING', 'Open Close Setting'),
    ('STL', 'FILIGREE', 'Filigree'),
    ('STL', 'GEMSTONE', 'Gemstone'),
    ('STL', 'BELVERY', 'Belvery'),
    ('STL', 'LAKSHMI CORAL', 'Lakshmi Coral'),
    ('STL', 'RAVA', 'Rava'),
    ('STL', 'DRISHYAM', 'Drishyam'),
    ('STL', 'DRISHYAM ENAMEL', 'Drishyam Enamel'),
    ('STL', 'PIRIYAN PIPE', 'Piriyan Pipe'),
    ('STL', 'SOLID RODIUM', 'Solid Rodium'),
    ('STL', 'SQUARE OPEN', 'Square Open'),
    ('STL', 'SQUARE PIPE RODIUM', 'Square Pipe Rodium'),
    ('STL', 'RADHA KRISHNA', 'Radha Krishna'),
    ('STL', 'MEENAKSHI', 'Meenakshi'),
    ('STL', 'PEACOCK', 'Peacock'),
    ('STL', 'RAM PARIVAR', 'Ram Parivar'),
    ('STL', 'CLOSED SETTING GOD', 'Closed Setting God'),
    ('STL', 'SINGAPORE STONE', 'Singapore Stone'),
    ('STL', 'SOLITAIRE', 'Solitaire'),
    ('STL', 'MEHNDI STONE', 'Mehndi Stone'),
    ('STL', 'BISCUIT', 'Biscuit'),
    ('STL', 'CARTIER', 'Cartier'),
    ('STL', 'CUBAN', 'Cuban'),
    ('STL', 'HOLLOW', 'Hollow'),
    ('STL', 'MEHNDI RODIUM', 'Mehndi Rodium'),
    ('STL', 'NAVABI', 'Navabi'),
    ('STL', 'NEW MAGIC', 'New Magic'),
    ('STL', 'JADAU', 'Jadau'),
    ('STL', 'CERA', 'Cera'),
    ('STL', 'CUPOD', 'Cupod'),
    ('STL', 'FLORA', 'Flora'),
    ('STL', 'YIN-YANG', 'Yin-Yang'),
    ('STL', 'KARINGALI', 'Karingali'),
    ('STL', 'SANDAL BRACELET', 'Sandal Bracelet'),
    ('STL', 'MADRASI SP', 'Madrasi Sp'),
    ('STL', 'MEHNDI PLAIN', 'Mehndi Plain'),
    ('STL', 'RAINBOW', 'Rainbow'),
    ('STL', 'SITA RAM', 'Sita Ram'),
    ('STL', 'TENNIS', 'Tennis'),
    ('STL', 'DELUXE', 'Deluxe'),
    ('STL', 'TURKISH SPECIAL', 'Turkish Special'),
    ('STL', 'MADHIRA', 'Madhira'),
    ('STL', 'MADHIRA CUTTING', 'Madhira Cutting'),
    ('STL', 'NAVABI KATTA', 'Navabi Katta'),
    ('STL', 'ANUSHKA', 'Anushka'),
    ('STL', 'BAHUBALI', 'Bahubali'),
    ('STL', 'BALL BASHA', 'Ball Basha'),
    ('STL', 'BASHA', 'Basha'),
    ('STL', 'BATTANI', 'Battani'),
    ('STL', 'BATTANI LAYER', 'Battani Layer'),
    ('STL', 'BATTANI MIX', 'Battani Mix'),
    ('STL', 'BATTANI MIX LAYER', 'Battani Mix Layer'),
    ('STL', 'BULB', 'Bulb'),
    ('STL', 'BULB LAYER', 'Bulb Layer'),
    ('STL', 'CHANDRAMUKHI', 'Chandramukhi'),
    ('STL', 'GENTLEMAN', 'Gentleman'),
    ('STL', 'HEART', 'Heart'),
    ('STL', 'HOLLOW CBT', 'Hollow Cbt'),
    ('STL', 'IPL', 'Ipl'),
    ('STL', 'IPL CUTTING', 'Ipl Cutting'),
    ('STL', 'KATTAPPA', 'Kattappa'),
    ('STL', 'MUDICHI THARA', 'Mudichi Thara'),
    ('STL', 'MUGAPPU LAKSHMI', 'Mugappu Lakshmi'),
    ('STL', 'MUGAPPU LAKSHMI STONE', 'Mugappu Lakshmi Stone'),
    ('STL', 'MUGAPPU PEACOCK', 'Mugappu Peacock'),
    ('STL', 'MULLBERRY', 'Mullberry'),
    ('STL', 'PYRAMID', 'Pyramid'),
    ('STL', 'PYRAMID MIX', 'Pyramid Mix'),
    ('STL', 'SQUARE ROPE', 'Square Rope'),
    ('STL', 'THALI KODI', 'Thali Kodi'),
    ('STL', 'TYRE', 'Tyre'),
    ('STL', 'TYRE LAYER', 'Tyre Layer'),
    ('STL', 'TYRE MIX', 'Tyre Mix'),
    ('STL', 'TYRE MIX LAYER', 'Tyre Mix Layer'),
    ('STL', 'BALL-URI KATTA', 'Ball-Uri Katta'),
    ('STL', 'DHRUVAM', 'Dhruvam'),
    ('STL', 'DISCO', 'Disco'),
    ('STL', 'DOUBLE SIDE KUMALA', 'Double Side Kumala'),
    ('STL', 'GOPURAM', 'Gopuram'),
    ('STL', 'INDIAN RUPEE', 'Indian Rupee'),
    ('STL', 'KANAKA MALA', 'Kanaka Mala'),
    ('STL', 'KILUKKAM', 'Kilukkam'),
    ('STL', 'MOGAMBO', 'Mogambo'),
    ('STL', 'MONKEYPEN', 'Monkeypen'),
    ('STL', 'NEELA THAMARA', 'Neela Thamara'),
    ('STL', 'ONE SIDE KUMALA', 'One Side Kumala'),
    ('STL', 'OVAL KANNI', 'Oval Kanni'),
    ('STL', 'PARASPARAM PLAIN', 'Parasparam Plain'),
    ('STL', 'PUZHU S', 'Puzhu S'),
    ('STL', 'SQUARE SUNDARI', 'Square Sundari'),
    ('STL', 'THARA', 'Thara'),
    ('STL', 'URI-KATTA', 'Uri-Katta'),
    ('STL', 'MC GF SPECIAL', 'Mc Gf Special'),
    ('STL', 'BOXCHAIN ROSE GOLD', 'Boxchain Rose Gold'),
    ('STL', 'BOXCHAIN YELLOW GOLD', 'Boxchain Yellow Gold'),
    ('STL', 'KAJU KATLI', 'Kaju Katli'),
    ('STL', 'ADDIGAI', 'Addigai'),
    ('STL', 'PADAKKA', 'Padakka'),
    ('STL', 'PEARL MALA', 'Pearl Mala'),
    ('STL', 'CLASSIC', 'Classic'),
    ('STL', 'AVIL MALA', 'Avil Mala'),
    ('STL', 'MANDAKASARA', 'Mandakasara'),
    ('STL', 'MOHANMALA', 'Mohanmala'),
    ('STL', 'NAVARATNA MALA', 'Navaratna Mala'),
    ('STL', 'STONE MALA', 'Stone Mala'),
    ('STL', 'CRYSTAL', 'Crystal'),
    ('STL', 'KASUMALA STONE', 'Kasumala Stone'),
    ('STL', 'MATTE', 'Matte'),
    ('STL', 'MATTE STONE', 'Matte Stone'),
    ('STL', 'MULLAMUTTU STONE', 'Mullamuttu Stone'),
    ('STL', 'PALAKKA THREAD LOCKET', 'Palakka Thread Locket'),
    ('STL', 'THREAD LOCKET GOD', 'Thread Locket God'),
    ('STL', 'BALAJI', 'Balaji'),
    ('STL', 'KANTI', 'Kanti'),
    ('STL', 'RED SANDAL SP', 'Red Sandal Sp'),
    ('STL', 'RUDRAKSHAM SP', 'Rudraksham Sp'),
    ('STL', 'TRADITIONAL THREAD LOCKET PALAKKA', 'Traditional Thread Locket Palakka'),
    ('STL', 'BUGADI', 'Bugadi'),
    ('STL', 'J TYPE', 'J Type'),
    ('STL', 'SANIYA', 'Saniya'),
    ('STL', 'SINGLE STONE', 'Single Stone'),
    ('STL', 'STAR', 'Star'),
    ('STL', 'SWASTIK', 'Swastik'),
    ('STL', 'ARASA ILLAI THALI', 'Arasa Illai Thali'),
    ('STL', 'LAKSHMI COIN', 'Lakshmi Coin'),
    ('STL', 'LAKSHMI DOLLAR', 'Lakshmi Dollar'),
    ('STL', 'MANGO STONE THALI', 'Mango Stone Thali'),
    ('STL', 'MANJIMA GOD', 'Manjima God'),
    ('STL', 'OHM DOLLAR', 'Ohm Dollar'),
    ('STL', 'PEACOCK THALI', 'Peacock Thali'),
    ('STL', 'PEARL THALI', 'Pearl Thali'),
    ('STL', 'PILLAYAR THALI', 'Pillayar Thali'),
    ('STL', 'POTTU THALI', 'Pottu Thali'),
    ('STL', 'SILLUVAI DOLLAR', 'Silluvai Dollar'),
    ('STL', 'SILUVAI THALI', 'Siluvai Thali'),
    ('STL', 'SOKKAR MEENAKSHI THALI', 'Sokkar Meenakshi Thali'),
    ('STL', 'URUTTU POTHARAM', 'Uruttu Potharam'),
    ('STL', 'TANMANIYA', 'Tanmaniya'),
    ('STL', 'TIGER NAIL', 'Tiger Nail'),
    ('STL', 'DISCO KASU', 'Disco Kasu'),
    ('STL', 'MYSUR THALI', 'Mysur Thali'),
    ('STL', 'KERALA FANCY', 'Kerala Fancy'),
    ('STL', 'KUMBALA OHM THALI', 'Kumbala Ohm Thali'),
    ('STL', 'KUMBALA PLAIN THALI', 'Kumbala Plain Thali'),
    ('STL', 'MANJIMA CROSS', 'Manjima Cross'),
    ('STL', 'MANJIMA GURUVAYURAPPAN', 'Manjima Guruvayurappan'),
    ('STL', 'MANJIMA JESUS', 'Manjima Jesus'),
    ('STL', 'MANJIMA KRISHNA', 'Manjima Krishna'),
    ('STL', 'MANJIMA LAKSHMI', 'Manjima Lakshmi'),
    ('STL', 'MANJIMA OM', 'Manjima Om'),
    ('STL', 'MANJIMA SARASWATHI', 'Manjima Saraswathi'),
    ('STL', 'PIPE CROSS', 'Pipe Cross'),
    ('STL', 'SLEEVA CROSS', 'Sleeva Cross'),
    ('STL', 'SLEEVA THALI', 'Sleeva Thali'),
    ('STL', 'SOLID CROSS', 'Solid Cross'),
    ('STL', 'FISH', 'Fish'),
    ('STL', 'GANDABERUNDA', 'Gandaberunda'),
    ('STL', 'WATTI', 'Watti'),
    ('STL', 'HANGING THALI', 'Hanging Thali'),
    ('STL', 'THALI', 'Thali'),
    ('STL', 'VANGI CLOSED SETTING', 'Vangi Closed Setting'),
    ('STL', 'PIE-CUT', 'Pie-Cut'),
    ('STL', 'KATTI TV', 'Katti Tv'),
    ('STL', 'MINCHI PIPE', 'Minchi Pipe'),
    ('STL', 'COUPLE', 'Couple'),
    ('STL', 'VANGI STONE', 'Vangi Stone'),
    ('STL', 'CHAND BALI STONE', 'Chand Bali Stone'),
    ('STL', 'BALI', 'Bali'),
    ('STL', 'CHAND BALI ENAMEL', 'Chand Bali Enamel'),
    ('STL', 'CHAND BALI GOD', 'Chand Bali God'),
    ('STL', 'CHAND BALI LAKSHMI', 'Chand Bali Lakshmi'),
    ('STL', 'CHAND BALI NAKSHI', 'Chand Bali Nakshi'),
    ('STL', 'CHAND BALI RAM PARIVAR', 'Chand Bali Ram Parivar');

-- CHECK
SELECT
    cf.attribute_code, cf.old_value, cf.new_value, e.id AS enum_value_id, e.value AS current_db_value,
    (SELECT COUNT(*) FROM product_attribute_value pav WHERE pav.product_attribute_enum_value_id = e.id) AS product_refs,
    (SELECT COUNT(*) FROM product_template_attribute_value ptav WHERE ptav.product_attribute_enum_value_id = e.id) AS template_refs,
    EXISTS (SELECT 1 FROM product_attribute_enum_value other
             WHERE other.product_attribute_id = e.product_attribute_id
               AND LOWER(other.value) = LOWER(cf.new_value) AND other.id <> e.id) AS target_already_exists_as_different_row
FROM step1_case_fixes cf
JOIN product_attribute pa ON pa.attribute_code = cf.attribute_code
JOIN product_attribute_enum_value e ON e.product_attribute_id = pa.id AND e.value = cf.old_value
ORDER BY cf.attribute_code, cf.old_value;
-- target_already_exists_as_different_row = true rows are skipped automatically
-- by the UPDATE below; investigate before assuming they're fine.

-- UPDATE
BEGIN;
UPDATE product_attribute_enum_value e
SET value = cf.new_value
FROM step1_case_fixes cf
JOIN product_attribute pa ON pa.attribute_code = cf.attribute_code
WHERE e.product_attribute_id = pa.id
  AND e.value = cf.old_value
  AND NOT EXISTS (SELECT 1 FROM product_attribute_enum_value other
                   WHERE other.product_attribute_id = e.product_attribute_id
                     AND LOWER(other.value) = LOWER(cf.new_value) AND other.id <> e.id);
COMMIT;

-- VERIFY
SELECT cf.attribute_code, cf.old_value, cf.new_value, e.id AS enum_value_id,
    EXISTS (SELECT 1 FROM product_attribute_enum_value stale
             WHERE stale.product_attribute_id = e.product_attribute_id AND stale.value = cf.old_value) AS old_value_still_present
FROM step1_case_fixes cf
JOIN product_attribute pa ON pa.attribute_code = cf.attribute_code
JOIN product_attribute_enum_value e ON e.product_attribute_id = pa.id AND e.value = cf.new_value
ORDER BY cf.attribute_code, cf.old_value;
