DROP TABLE IF EXISTS sheet_combos;
CREATE TEMP TABLE sheet_combos (category text, product_type text, collection text, style text);
INSERT INTO sheet_combos (category, product_type, collection, style) VALUES
    ('Anklet', 'Gold 14K', 'Italian', 'Fancy'),
    ('Anklet', 'Gold 18K', '18 Karat', '18 Karat'),
    ('Anklet', 'Gold 18K', 'Bombay', 'Box Chain'),
    ('Anklet', 'Gold 18K', 'Italian', 'Charms'),
    ('Anklet', 'Gold 18K', 'Italian', 'Plain'),
    ('Anklet', 'Gold 18K', 'Italian', 'Rhodium'),
    ('Anklet', 'Gold 18K', 'Italian', 'Stone'),
    ('Anklet', 'Gold 18K', 'Moulding', 'Rhodium'),
    ('Anklet', 'Gold 22k', 'Bombay', 'Net'),
    ('Anklet', 'Gold 22k', 'Bombay', 'Plain'),
    ('Anklet', 'Gold 22k', 'Bombay', 'Rhodium'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Box Chain'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Cheth'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Don'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Double Sachin'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Double Sewag'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Ettukanni'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Gold Finger'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Highway'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Mutharanjanam'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Parantha'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Rail'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Sewag'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Single Aranjal'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Sundari'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Tight Aranjal'),
    ('Anklet', 'Gold 22k', 'Kerala', 'Urvasi'),
    ('Anklet', 'Gold 22k', 'Kerala Traditional', 'Black Beeds'),
    ('Anklet', 'Gold 22k', 'Moulding', 'Fancy'),
    ('Anklet', 'Gold 22k', 'Moulding', 'Stone Special'),
    ('Anklet', 'Gold 22k', 'Rajkot', 'Parasparam'),
    ('Anklet', 'Gold 22k', 'Rajkot', 'Parasparam Rodium'),
    ('Anklet', 'Gold 22k', 'Rajkot', 'Plain'),
    ('Anklet', 'Gold 22k', 'Rajkot', 'Rhodium'),
    ('Anklet', 'Gold 22k', 'Singapore', 'Enamel'),
    ('Anklet', 'Gold 22k', 'Singapore', 'Fancy'),
    ('Anklet', 'Gold 22k', 'Singapore', 'Plain'),
    ('Anklet', 'Gold 22k', 'Singapore', 'Rhodium'),
    ('Anklet', 'Gold 22k', 'Singapore', 'Stone'),
    ('Anklet', 'Precious', 'Moulding', 'Savariya'),
    ('Anklet', 'Precious', 'Precious', 'Savariya'),
    ('Back Chain', 'Gold 18K', '18 Karat', 'Back Chain'),
    ('Back Chain', 'Gold 18K', 'Italian', 'Plain'),
    ('Bangle', 'Diamond', 'Moulding', 'Closed Setting'),
    ('Bangle', 'Diamond', 'Moulding', 'Cluster'),
    ('Bangle', 'Diamond', 'Moulding', 'Fancy'),
    ('Bangle', 'Diamond', 'Moulding', 'Lakshmi'),
    ('Bangle', 'Diamond', 'Moulding', 'Open Close Setting'),
    ('Bangle', 'Diamond', 'Moulding', 'Solitaire'),
    ('Bangle', 'Gold 18K', '18 Karat', '18 Karat'),
    ('Bangle', 'Gold 18K', 'Moulding', 'Plain'),
    ('Bangle', 'Gold 18K', 'Moulding', 'Rhodium'),
    ('Bangle', 'Gold 18K', 'Moulding', 'Stone'),
    ('Bangle', 'Gold 18K', 'Nagas', 'Radha Krishna'),
    ('Bangle', 'Gold 22k', 'Antique', 'Enamel'),
    ('Bangle', 'Gold 22k', 'Antique', 'Fancy'),
    ('Bangle', 'Gold 22k', 'Antique', 'Kundan'),
    ('Bangle', 'Gold 22k', 'Antique', 'Meenakari'),
    ('Bangle', 'Gold 22k', 'Antique', 'Nakashi'),
    ('Bangle', 'Gold 22k', 'Antique', 'Plain'),
    ('Bangle', 'Gold 22k', 'Antique', 'Stone'),
    ('Bangle', 'Gold 22k', 'Bombay', 'CNC Cutting'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Enamel'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Flower'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Half Round'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Half Round Enamel'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Half Round Stone'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Pipe'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Pipe Enamel'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Pipe Rhodium'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Plain'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Rhodium'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Rhodium CNC Cutting'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Round Pipe'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Stone'),
    ('Bangle', 'Gold 22k', 'Bombay', 'Thread'),
    ('Bangle', 'Gold 22k', 'Chettinadu', 'Lakshmi'),
    ('Bangle', 'Gold 22k', 'Chettinadu', 'Lakshmi Stone'),
    ('Bangle', 'Gold 22k', 'Chettinadu', 'Nakashi'),
    ('Bangle', 'Gold 22k', 'Cnc', 'Enamel'),
    ('Bangle', 'Gold 22k', 'Cnc', 'Eye'),
    ('Bangle', 'Gold 22k', 'Cnc', 'God'),
    ('Bangle', 'Gold 22k', 'Cnc', 'Jaguar'),
    ('Bangle', 'Gold 22k', 'Cnc', 'Leaf'),
    ('Bangle', 'Gold 22k', 'Cnc', 'Plain'),
    ('Bangle', 'Gold 22k', 'Cnc', 'Rhodium'),
    ('Bangle', 'Gold 22k', 'Cnc', 'Simba'),
    ('Bangle', 'Gold 22k', 'Cnc', 'Stone'),
    ('Bangle', 'Gold 22k', 'Coimbatore', 'Closed Setting'),
    ('Bangle', 'Gold 22k', 'Coimbatore', 'Stone'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Belvery'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Black Beeds'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Coorgi'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Coorgi stone'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Coral'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Jade'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Patly'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Pearl'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Plain'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Rava'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Solid'),
    ('Bangle', 'Gold 22k', 'Karnataka', 'Stone'),
    ('Bangle', 'Gold 22k', 'Karnataka Traditional', 'Coorgi'),
    ('Bangle', 'Gold 22k', 'Karnataka Traditional', 'Coorgi stone'),
    ('Bangle', 'Gold 22k', 'Karnataka Traditional', 'Lakshmi'),
    ('Bangle', 'Gold 22k', 'Karnataka Traditional', 'Lakshmi Coral'),
    ('Bangle', 'Gold 22k', 'Karnataka Traditional', 'Lakshmi Stone'),
    ('Bangle', 'Gold 22k', 'Karnataka Traditional', 'Nellore'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Baby'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Ball Joint'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Drishyam'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Drishyam Enamel'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Dye'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Fancy'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Half Round'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Kerala'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Lakshmi'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Lakshmi Stone'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Nagapadam'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Palakka'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Pipe'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Piriyan Pipe'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Plain'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Polla Ozhukkan'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Punjabi Polla'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Punjabi Solid'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Round Pipe'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Solid'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Solid Rodium'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Square Open'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Square Pipe'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Square Pipe Rodium'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Thala'),
    ('Bangle', 'Gold 22k', 'Kerala', 'Traditional'),
    ('Bangle', 'Gold 22k', 'Kerala Traditional', 'Dasavatharam'),
    ('Bangle', 'Gold 22k', 'Kerala Traditional', 'Lakshmi'),
    ('Bangle', 'Gold 22k', 'Kerala Traditional', 'Palakka'),
    ('Bangle', 'Gold 22k', 'Kerala Traditional', 'Traditional'),
    ('Bangle', 'Gold 22k', 'Kolkata', 'Enamel'),
    ('Bangle', 'Gold 22k', 'Kolkata', 'Pipe'),
    ('Bangle', 'Gold 22k', 'Kolkata', 'Pipe Enamel'),
    ('Bangle', 'Gold 22k', 'Kolkata', 'Plain'),
    ('Bangle', 'Gold 22k', 'Kolkata', 'Screw'),
    ('Bangle', 'Gold 22k', 'Kolkata', 'Screw Enamel'),
    ('Bangle', 'Gold 22k', 'Moulding', 'Fancy'),
    ('Bangle', 'Gold 22k', 'Moulding', 'Moulding Stone'),
    ('Bangle', 'Gold 22k', 'Moulding', 'Plain'),
    ('Bangle', 'Gold 22k', 'Moulding', 'Rhodium'),
    ('Bangle', 'Gold 22k', 'Moulding', 'Signity'),
    ('Bangle', 'Gold 22k', 'Moulding', 'Stone'),
    ('Bangle', 'Gold 22k', 'Nagas', 'God'),
    ('Bangle', 'Gold 22k', 'Nagas', 'Lakshmi'),
    ('Bangle', 'Gold 22k', 'Nagas', 'Lakshmi Stone'),
    ('Bangle', 'Gold 22k', 'Nagas', 'Meenakshi'),
    ('Bangle', 'Gold 22k', 'Nagas', 'Nakashi'),
    ('Bangle', 'Gold 22k', 'Nagas', 'Peacock'),
    ('Bangle', 'Gold 22k', 'Nagas', 'Radha Krishna'),
    ('Bangle', 'Gold 22k', 'Nagas', 'Ram Parivar'),
    ('Bangle', 'Gold 22k', 'Nagas', 'Stone'),
    ('Bangle', 'Gold 22k', 'Rajkot', 'Black Beeds'),
    ('Bangle', 'Gold 22k', 'Rajkot', 'Enamel'),
    ('Bangle', 'Gold 22k', 'Rajkot', 'Plain'),
    ('Bangle', 'Gold 22k', 'Rajkot', 'Rhodium'),
    ('Bangle', 'Gold 22k', 'Rajkot', 'Stone'),
    ('Bangle', 'Gold 22k', 'Semi Antique', 'Nakashi'),
    ('Bangle', 'Gold 22k', 'Semi Nagas', 'Lakshmi'),
    ('Bangle', 'Gold 22k', 'Semi Nagas', 'Nakashi'),
    ('Bangle', 'Gold 22k', 'SIGNITY', 'Closed Setting'),
    ('Bangle', 'Gold 22k', 'SIGNITY', 'Closed Setting God'),
    ('Bangle', 'Gold 22k', 'SIGNITY', 'Stone'),
    ('Bangle', 'Gold 22k', 'Singapore', 'CNC'),
    ('Bangle', 'Gold 22k', 'Singapore', 'Enamel'),
    ('Bangle', 'Gold 22k', 'Singapore', 'Plain'),
    ('Bangle', 'Gold 22k', 'Singapore', 'Singapore'),
    ('Bangle', 'Gold 22k', 'Singapore', 'Singapore Stone'),
    ('Bangle', 'Gold 22k', 'Singapore', 'Stone'),
    ('Bangle', 'Gold 22k', 'Turkish', 'Plain'),
    ('Bangle', 'Gold 22k', 'Turkish', 'Rhodium'),
    ('Bangle', 'Gold 22k', 'Turkish', 'Semi Turkish'),
    ('Bangle', 'Gold 22k', 'Turkish', 'Turkish'),
    ('Bangle', 'Platinum', 'Platinum', 'Fancy'),
    ('Bangle', 'Platinum', 'Platinum', 'Fusion'),
    ('Bangle', 'Polki', 'Polki', 'Fancy'),
    ('Bangle', 'Precious', 'Moulding', 'Filigree'),
    ('Bangle', 'Precious', 'Moulding', 'Gemstone'),
    ('Bangle', 'Precious', 'Moulding', 'Lakshmi'),
    ('Bangle', 'Precious', 'Moulding', 'Navaratna'),
    ('Bangle', 'Precious', 'Nagas', 'God'),
    ('Bangle', 'Precious', 'Nagas', 'Lakshmi'),
    ('Bangle', 'Precious', 'Nagas', 'Nakashi'),
    ('Bangle', 'Precious', 'Nagas', 'Radha Krishna'),
    ('Bangle', 'Precious', 'Nagas', 'Ram Parivar'),
    ('Bangle', 'Precious', 'Nagas', 'Vanki'),
    ('Bangle', 'Precious', 'Precious', 'Precious'),
    ('Bangle', 'Precious', 'Turkish', 'Filigree'),
    ('Bangle', 'Precious', 'Turkish', 'Gemstone'),
    ('Bangle', 'Uncut', 'Moulding', 'Filigree'),
    ('Bangle', 'Uncut', 'Moulding', 'Gemstone'),
    ('Bangle', 'Uncut', 'Moulding', 'Lakshmi'),
    ('Bangle', 'Uncut', 'Moulding', 'Navaratna'),
    ('Bangle', 'Uncut', 'Nagas', 'God'),
    ('Bangle', 'Uncut', 'Nagas', 'Lakshmi'),
    ('Bangle', 'Uncut', 'Nagas', 'Nakashi'),
    ('Bangle', 'Uncut', 'Nagas', 'Ram Parivar'),
    ('Bangle', 'Uncut', 'Nagas', 'Vanki'),
    ('Bangle', 'Uncut', 'Turkish', 'Gemstone'),
    ('Bangle', 'Uncut', 'Turkish', 'Lakshmi'),
    ('Bangle', 'Uncut', 'Uncut', 'Uncut'),
    ('Bracelet', 'Diamond', '14 Kt Ornaments', 'Oval'),
    ('Bracelet', 'Diamond', 'Moulding', 'Fancy'),
    ('Bracelet', 'Diamond', 'Moulding', 'Oval'),
    ('Bracelet', 'Diamond', 'Moulding', 'Tennis'),
    ('Bracelet', 'Diamond', 'Navaratna Jewellery', 'Navaratna Oval'),
    ('Bracelet', 'Gold 14K', '14 Kt Ornaments', '14 Karat Ornaments'),
    ('Bracelet', 'Gold 14K', '14 Kt Ornaments', 'Fancy'),
    ('Bracelet', 'Gold 14K', '14 Kt Ornaments', 'Oval'),
    ('Bracelet', 'Gold 14K', 'Italian', 'Cera'),
    ('Bracelet', 'Gold 14K', 'Italian', 'Cupod'),
    ('Bracelet', 'Gold 14K', 'Italian', 'Flora'),
    ('Bracelet', 'Gold 14K', 'Italian', 'Yin-Yang'),
    ('Bracelet', 'Gold 14K', 'Ovel Bracelet', '14 Karat Ornaments'),
    ('Bracelet', 'Gold 18K', '18 Karat', '18 Karat'),
    ('Bracelet', 'Gold 18K', 'Italian', 'Black Beeds'),
    ('Bracelet', 'Gold 18K', 'Italian', 'Plain'),
    ('Bracelet', 'Gold 18K', 'Italian', 'Rhodium'),
    ('Bracelet', 'Gold 18K', 'Italian', 'Stone'),
    ('Bracelet', 'Gold 18K', 'Moulding', 'Enamel'),
    ('Bracelet', 'Gold 18K', 'Moulding', 'Plain'),
    ('Bracelet', 'Gold 18K', 'Moulding', 'Stone'),
    ('Bracelet', 'Gold 22k', 'Antique', 'Fancy'),
    ('Bracelet', 'Gold 22k', 'Antique', 'Kundan'),
    ('Bracelet', 'Gold 22k', 'Antique', 'Mehndi Stone'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Biscuit'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Black Beeds'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Cartier'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Cuban'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Fancy'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Hollow'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Indo Italian'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Madrasi'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Mehndi Rodium'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Navabi'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'New Magic'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Plain'),
    ('Bracelet', 'Gold 22k', 'Bombay', 'Rhodium'),
    ('Bracelet', 'Gold 22k', 'Coimbatore', 'Lotus'),
    ('Bracelet', 'Gold 22k', 'Coimbatore', 'Plain'),
    ('Bracelet', 'Gold 22k', 'Karnataka', 'Black Beeds'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Anavaal'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Don'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Double Sachin'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Double Sewag'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Dye'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Karingali'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Kerala'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Parantha'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Parasparam Rodium'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Red Sandal'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Rudraksham'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Sachin'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Sandal Bracelet'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Sewag'),
    ('Bracelet', 'Gold 22k', 'Kerala', 'Thulasi'),
    ('Bracelet', 'Gold 22k', 'Kerala Traditional', 'Black Beeds'),
    ('Bracelet', 'Gold 22k', 'Kerala Traditional', 'Karingali'),
    ('Bracelet', 'Gold 22k', 'Kerala Traditional', 'Red Sandal'),
    ('Bracelet', 'Gold 22k', 'Kerala Traditional', 'Rudraksham'),
    ('Bracelet', 'Gold 22k', 'Kerala Traditional', 'Stone Special'),
    ('Bracelet', 'Gold 22k', 'Kerala Traditional', 'Thulasi'),
    ('Bracelet', 'Gold 22k', 'Kerala Traditional', 'Traditional'),
    ('Bracelet', 'Gold 22k', 'Kolkata', 'Plain'),
    ('Bracelet', 'Gold 22k', 'Kolkata', 'Stone'),
    ('Bracelet', 'Gold 22k', 'MADRASI', 'Madrasi Sp'),
    ('Bracelet', 'Gold 22k', 'Moulding', 'Fancy'),
    ('Bracelet', 'Gold 22k', 'Moulding', 'Mehndi Plain'),
    ('Bracelet', 'Gold 22k', 'Moulding', 'Mehndi Stone'),
    ('Bracelet', 'Gold 22k', 'Moulding', 'Moulding Stone'),
    ('Bracelet', 'Gold 22k', 'Moulding', 'Paper Cast'),
    ('Bracelet', 'Gold 22k', 'Moulding', 'Plain'),
    ('Bracelet', 'Gold 22k', 'Moulding', 'Rainbow'),
    ('Bracelet', 'Gold 22k', 'Moulding', 'Rhodium'),
    ('Bracelet', 'Gold 22k', 'Moulding', 'Simba'),
    ('Bracelet', 'Gold 22k', 'Moulding', 'Stone'),
    ('Bracelet', 'Gold 22k', 'Nagas', 'God'),
    ('Bracelet', 'Gold 22k', 'Nagas', 'Lakshmi'),
    ('Bracelet', 'Gold 22k', 'Nagas', 'Nakashi'),
    ('Bracelet', 'Gold 22k', 'Nagas', 'Sita Ram'),
    ('Bracelet', 'Gold 22k', 'Rajkot', 'Beeds'),
    ('Bracelet', 'Gold 22k', 'Rajkot', 'Black Beeds'),
    ('Bracelet', 'Gold 22k', 'Rajkot', 'Parasparam'),
    ('Bracelet', 'Gold 22k', 'Rajkot', 'Plain'),
    ('Bracelet', 'Gold 22k', 'Rajkot', 'Rhodium'),
    ('Bracelet', 'Gold 22k', 'Rajkot', 'Stone'),
    ('Bracelet', 'Gold 22k', 'Semi Antique', 'Nakashi'),
    ('Bracelet', 'Gold 22k', 'Singapore', 'Cuban'),
    ('Bracelet', 'Gold 22k', 'Singapore', 'Deluxe'),
    ('Bracelet', 'Gold 22k', 'Singapore', 'Enamel'),
    ('Bracelet', 'Gold 22k', 'Singapore', 'Plain'),
    ('Bracelet', 'Gold 22k', 'Singapore', 'Rhodium'),
    ('Bracelet', 'Gold 22k', 'Singapore', 'Simba'),
    ('Bracelet', 'Gold 22k', 'Singapore', 'Singapore'),
    ('Bracelet', 'Gold 22k', 'Singapore', 'Singapore Stone'),
    ('Bracelet', 'Gold 22k', 'Singapore', 'Special'),
    ('Bracelet', 'Gold 22k', 'Singapore', 'Stone'),
    ('Bracelet', 'Gold 22k', 'Turkish', 'Plain'),
    ('Bracelet', 'Gold 22k', 'Turkish', 'Rhodium'),
    ('Bracelet', 'Gold 22k', 'Turkish', 'Turkish'),
    ('Bracelet', 'Gold 22k', 'Turkish', 'Turkish Special'),
    ('Bracelet', 'Platinum', 'Platinum', 'Fancy'),
    ('Bracelet', 'Platinum', 'Platinum', 'Fusion'),
    ('Bracelet', 'Polki', 'Polki', 'Fancy'),
    ('Bracelet', 'Polki', 'Polki', 'Jadau'),
    ('Bracelet', 'Precious', 'Moulding', 'Gemstone'),
    ('Bracelet', 'Precious', 'Precious', 'Precious'),
    ('Bracelet', 'Precious', 'Turkish', 'Gemstone'),
    ('Bracelet', 'Precious', 'Uncut', 'Precious'),
    ('Bracelet', 'Uncut', 'Moulding', 'Gemstone'),
    ('Bracelet', 'Uncut', 'Uncut', 'Uncut'),
    ('Chain', 'Gold 18K', '18 Karat', '18 Karat'),
    ('Chain', 'Gold 18K', 'Bombay', 'Box Chain'),
    ('Chain', 'Gold 18K', 'Bombay', 'Boxchain Rose Gold'),
    ('Chain', 'Gold 18K', 'Bombay', 'Boxchain Yellow Gold'),
    ('Chain', 'Gold 18K', 'Italian', 'Box Chain'),
    ('Chain', 'Gold 18K', 'Moulding', 'Plain'),
    ('Chain', 'Gold 18K', 'Moulding', 'Rhodium'),
    ('Chain', 'Gold 22k', 'Bombay', 'Biscuit'),
    ('Chain', 'Gold 22k', 'Bombay', 'Fancy'),
    ('Chain', 'Gold 22k', 'Bombay', 'Indo Italian'),
    ('Chain', 'Gold 22k', 'Bombay', 'Madhira'),
    ('Chain', 'Gold 22k', 'Bombay', 'Madhira Cutting'),
    ('Chain', 'Gold 22k', 'Bombay', 'Navabi'),
    ('Chain', 'Gold 22k', 'Bombay', 'Navabi Katta'),
    ('Chain', 'Gold 22k', 'Bombay', 'Plain'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Anushka'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Bahubali'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Ball Basha'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Ball-Uri'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Ball-Uri Katti'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Basha'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Battani'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Battani Layer'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Battani Mix'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Battani Mix Layer'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Biscuit'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Bulb'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Bulb Layer'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Chandramukhi'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Curb'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Fancy'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Flower'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Gentleman'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Heart'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Hollow Cbt'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Ipl'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Ipl Cutting'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Kattappa'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Lotus'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Mudichi Thara'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Mugappu'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Mugappu God'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Mugappu Lakshmi'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Mugappu Lakshmi Stone'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Mugappu Peacock'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Mugappu Stone'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Mullberry'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Navabi Katta'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Pyramid'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Pyramid Mix'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Round Kurumulak'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'S-Leaf'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Savitham Katta'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Solid Rope'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Square Kurumulak'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Square Rope'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Thali Kodi'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Tight Aranjal'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Tyre'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Tyre Layer'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Tyre Mix'),
    ('Chain', 'Gold 22k', 'Coimbatore', 'Tyre Mix Layer'),
    ('Chain', 'Gold 22k', 'Karnataka', 'Kattappa'),
    ('Chain', 'Gold 22k', 'Kerala', '4S Chain'),
    ('Chain', 'Gold 22k', 'Kerala', 'Ball-Uri'),
    ('Chain', 'Gold 22k', 'Kerala', 'Ball-Uri Katta'),
    ('Chain', 'Gold 22k', 'Kerala', 'Box Chain'),
    ('Chain', 'Gold 22k', 'Kerala', 'Celo'),
    ('Chain', 'Gold 22k', 'Kerala', 'Celo Katta'),
    ('Chain', 'Gold 22k', 'Kerala', 'Cheth'),
    ('Chain', 'Gold 22k', 'Kerala', 'Dhruvam'),
    ('Chain', 'Gold 22k', 'Kerala', 'Disco'),
    ('Chain', 'Gold 22k', 'Kerala', 'Don'),
    ('Chain', 'Gold 22k', 'Kerala', 'Double Sachin'),
    ('Chain', 'Gold 22k', 'Kerala', 'Double Sewag'),
    ('Chain', 'Gold 22k', 'Kerala', 'Double Side Kumala'),
    ('Chain', 'Gold 22k', 'Kerala', 'Fancy'),
    ('Chain', 'Gold 22k', 'Kerala', 'Gold Finger'),
    ('Chain', 'Gold 22k', 'Kerala', 'Gopuram'),
    ('Chain', 'Gold 22k', 'Kerala', 'Highway'),
    ('Chain', 'Gold 22k', 'Kerala', 'Hollow Rope'),
    ('Chain', 'Gold 22k', 'Kerala', 'Indian Rupee'),
    ('Chain', 'Gold 22k', 'Kerala', 'Kanaka Mala'),
    ('Chain', 'Gold 22k', 'Kerala', 'Kilukkam'),
    ('Chain', 'Gold 22k', 'Kerala', 'Lotus'),
    ('Chain', 'Gold 22k', 'Kerala', 'Manimala'),
    ('Chain', 'Gold 22k', 'Kerala', 'Mogambo'),
    ('Chain', 'Gold 22k', 'Kerala', 'Monkeypen'),
    ('Chain', 'Gold 22k', 'Kerala', 'Mugappu God'),
    ('Chain', 'Gold 22k', 'Kerala', 'Mulla'),
    ('Chain', 'Gold 22k', 'Kerala', 'Mullberry'),
    ('Chain', 'Gold 22k', 'Kerala', 'Neela Thamara'),
    ('Chain', 'Gold 22k', 'Kerala', 'One Side Kumala'),
    ('Chain', 'Gold 22k', 'Kerala', 'Oval Kanni'),
    ('Chain', 'Gold 22k', 'Kerala', 'Parantha'),
    ('Chain', 'Gold 22k', 'Kerala', 'Parasparam Plain'),
    ('Chain', 'Gold 22k', 'Kerala', 'Parasparam Rodium'),
    ('Chain', 'Gold 22k', 'Kerala', 'Pulimurugan'),
    ('Chain', 'Gold 22k', 'Kerala', 'Puzhu S'),
    ('Chain', 'Gold 22k', 'Kerala', 'Rail'),
    ('Chain', 'Gold 22k', 'Kerala', 'Rosary'),
    ('Chain', 'Gold 22k', 'Kerala', 'Round Kurumulak'),
    ('Chain', 'Gold 22k', 'Kerala', 'S-Leaf'),
    ('Chain', 'Gold 22k', 'Kerala', 'Sachin'),
    ('Chain', 'Gold 22k', 'Kerala', 'Savitham'),
    ('Chain', 'Gold 22k', 'Kerala', 'Savitham Katta'),
    ('Chain', 'Gold 22k', 'Kerala', 'Sewag'),
    ('Chain', 'Gold 22k', 'Kerala', 'Single Aranjal'),
    ('Chain', 'Gold 22k', 'Kerala', 'Solid Rope'),
    ('Chain', 'Gold 22k', 'Kerala', 'Special'),
    ('Chain', 'Gold 22k', 'Kerala', 'Square Kurumulak'),
    ('Chain', 'Gold 22k', 'Kerala', 'Square Sundari'),
    ('Chain', 'Gold 22k', 'Kerala', 'Sundari'),
    ('Chain', 'Gold 22k', 'Kerala', 'Thara'),
    ('Chain', 'Gold 22k', 'Kerala', 'Thoradu'),
    ('Chain', 'Gold 22k', 'Kerala', 'Tight Aranjal'),
    ('Chain', 'Gold 22k', 'Kerala', 'Uri'),
    ('Chain', 'Gold 22k', 'Kerala', 'Uri-Katta'),
    ('Chain', 'Gold 22k', 'Kerala', 'Urvasi'),
    ('Chain', 'Gold 22k', 'Kerala', 'V Chain'),
    ('Chain', 'Gold 22k', 'Kerala Special', 'Cbt'),
    ('Chain', 'Gold 22k', 'Kerala Special', 'Mc Gf Special'),
    ('Chain', 'Gold 22k', 'Kerala Traditional', 'Manikasu'),
    ('Chain', 'Gold 22k', 'Kerala Traditional', 'Traditional'),
    ('Chain', 'Gold 22k', 'Nagas', 'Mugappu God'),
    ('Chain', 'Gold 22k', 'Rajkot', 'Parasparam'),
    ('Chain', 'Gold 22k', 'Rajkot', 'Plain'),
    ('Chain', 'Gold 22k', 'Rajkot', 'Rhodium'),
    ('Chain', 'Gold 22k', 'Rajkot', 'Rosary'),
    ('Chain', 'Gold 22k', 'Singapore', 'Biscuit'),
    ('Chain', 'Gold 22k', 'Singapore', 'Cuban'),
    ('Chain', 'Gold 22k', 'Singapore', 'Fancy'),
    ('Chain', 'Gold 22k', 'Singapore', 'Indo Italian'),
    ('Chain', 'Gold 22k', 'Singapore', 'Kaju Katli'),
    ('Chain', 'Gold 22k', 'Singapore', 'Mugappu God'),
    ('Chain', 'Gold 22k', 'Singapore', 'Mugappu Stone'),
    ('Chain', 'Platinum', 'Platinum', 'Fancy'),
    ('Chain', 'Platinum', 'Platinum', 'Fusion'),
    ('Chutti', 'Diamond', 'Moulding', 'Fancy'),
    ('Chutti', 'Diamond', 'Moulding', 'God'),
    ('Chutti', 'Diamond', 'Moulding', 'Lakshmi'),
    ('Chutti', 'Diamond', 'Moulding', 'Ram Parivar'),
    ('Chutti', 'Gold 18K', 'Nagas', 'Meenakshi'),
    ('Chutti', 'Gold 22k', 'Antique', 'Kundan'),
    ('Chutti', 'Gold 22k', 'Antique', 'Nakashi'),
    ('Chutti', 'Gold 22k', 'Bombay', 'Plain'),
    ('Chutti', 'Gold 22k', 'Kolkata', 'Nakashi'),
    ('Chutti', 'Gold 22k', 'Kolkata', 'Plain'),
    ('Chutti', 'Gold 22k', 'Kolkata', 'Stone'),
    ('Chutti', 'Gold 22k', 'Nagas', 'God'),
    ('Chutti', 'Gold 22k', 'Nagas', 'Lakshmi'),
    ('Chutti', 'Gold 22k', 'Nagas', 'Nakashi'),
    ('Chutti', 'Gold 22k', 'Nagas', 'Radha Krishna'),
    ('Chutti', 'Gold 22k', 'Nagas', 'Ram Parivar'),
    ('Chutti', 'Polki', 'Polki', 'Fancy'),
    ('Chutti', 'Precious', 'Moulding', 'Gemstone'),
    ('Chutti', 'Precious', 'Turkish', 'Gemstone'),
    ('Chutti', 'Uncut', 'Moulding', 'Gemstone'),
    ('Chutti', 'Uncut', 'Nagas', 'Lakshmi'),
    ('Chutti', 'Uncut', 'Nagas', 'Nakashi'),
    ('Chutti', 'Uncut', 'Nagas', 'Ram Parivar'),
    ('Chutti', 'Uncut', 'Turkish', 'Gemstone'),
    ('Hip Chain', 'Gold 22k', 'Kerala', 'Ettukanni'),
    ('Hip Chain', 'Gold 22k', 'Kerala', 'Gold Finger'),
    ('Hip Chain', 'Gold 22k', 'Kerala', 'Mutharanjanam'),
    ('Hip Chain', 'Gold 22k', 'Kerala', 'Parantha'),
    ('Hip Chain', 'Gold 22k', 'Kerala', 'Single Aranjal'),
    ('Hip Chain', 'Gold 22k', 'Kerala', 'Tight Aranjal'),
    ('Hip Chain', 'Gold 22k', 'Kerala', 'Urvasi'),
    ('Idols', 'Gold 22k', 'Statue Jewellery', 'Statue'),
    ('Matti Chain', 'Gold 22k', 'Antique', 'Elakkathali'),
    ('Matti Chain', 'Gold 22k', 'Antique', 'Fancy'),
    ('Matti Chain', 'Gold 22k', 'Bombay', 'Plain'),
    ('Matti Chain', 'Gold 22k', 'Bombay', 'Stone'),
    ('Matti Chain', 'Gold 22k', 'Coimbatore', 'Enamel'),
    ('Matti Chain', 'Gold 22k', 'Coimbatore', 'Plain'),
    ('Matti Chain', 'Gold 22k', 'Kerala', 'Kerala'),
    ('Matti Chain', 'Gold 22k', 'Kerala', 'Urvasi'),
    ('Matti Chain', 'Gold 22k', 'Kolkata', 'Enamel'),
    ('Matti Chain', 'Gold 22k', 'Kolkata', 'Plain'),
    ('Matti Chain', 'Gold 22k', 'Nagas', 'Nakashi'),
    ('Matti Chain', 'Precious', 'Moulding', 'Gemstone'),
    ('Necklace', 'Diamond', 'Moulding', 'Charms'),
    ('Necklace', 'Diamond', 'Moulding', 'Classic'),
    ('Necklace', 'Diamond', 'Moulding', 'Closed Setting'),
    ('Necklace', 'Diamond', 'Moulding', 'Cluster'),
    ('Necklace', 'Diamond', 'Moulding', 'Fancy'),
    ('Necklace', 'Diamond', 'Moulding', 'God'),
    ('Necklace', 'Diamond', 'Moulding', 'Lakshmi'),
    ('Necklace', 'Diamond', 'Moulding', 'Mangalsutra'),
    ('Necklace', 'Diamond', 'Moulding', 'Meenakshi'),
    ('Necklace', 'Diamond', 'Moulding', 'Navaratna'),
    ('Necklace', 'Diamond', 'Moulding', 'Open Close Setting'),
    ('Necklace', 'Diamond', 'Moulding', 'Radha Krishna'),
    ('Necklace', 'Diamond', 'Moulding', 'Solitaire'),
    ('Necklace', 'Diamond', 'Moulding', 'Twisted'),
    ('Necklace', 'Diamond', 'Nagas', 'Lakshmi'),
    ('Necklace', 'Diamond', 'Nagas', 'Radha Krishna'),
    ('Necklace', 'Gold 14K', '14 Kt Ornaments', '14 Karat Ornaments'),
    ('Necklace', 'Gold 14K', '14 Kt Ornaments', 'Fancy'),
    ('Necklace', 'Gold 14K', 'Italian', 'Cera'),
    ('Necklace', 'Gold 14K', 'Italian', 'Cupod'),
    ('Necklace', 'Gold 14K', 'Italian', 'Fancy'),
    ('Necklace', 'Gold 14K', 'Italian', 'Flora'),
    ('Necklace', 'Gold 14K', 'Italian', 'Yin-Yang'),
    ('Necklace', 'Gold 14K', 'Moulding', 'Fancy'),
    ('Necklace', 'Gold 18K', '18 Karat', '18 Karat'),
    ('Necklace', 'Gold 18K', 'Italian', 'Black Beeds'),
    ('Necklace', 'Gold 18K', 'Italian', 'Plain'),
    ('Necklace', 'Gold 18K', 'Italian', 'Rhodium'),
    ('Necklace', 'Gold 18K', 'Moulding', 'Plain'),
    ('Necklace', 'Gold 18K', 'Moulding', 'Rhodium'),
    ('Necklace', 'Gold 18K', 'Moulding', 'Rosary'),
    ('Necklace', 'Gold 18K', 'Moulding', 'Stone'),
    ('Necklace', 'Gold 18K', 'Nagas', 'Meenakshi'),
    ('Necklace', 'Gold 22k', 'Antique', 'Chakkiri'),
    ('Necklace', 'Gold 22k', 'Antique', 'Elakkathali'),
    ('Necklace', 'Gold 22k', 'Antique', 'Fancy'),
    ('Necklace', 'Gold 22k', 'Antique', 'Kundan'),
    ('Necklace', 'Gold 22k', 'Antique', 'Lakshmi'),
    ('Necklace', 'Gold 22k', 'Antique', 'Mangalsutra'),
    ('Necklace', 'Gold 22k', 'Antique', 'Nakashi'),
    ('Necklace', 'Gold 22k', 'Antique', 'Stone'),
    ('Necklace', 'Gold 22k', 'Bengali', 'Plain'),
    ('Necklace', 'Gold 22k', 'Bengali', 'Rhodium'),
    ('Necklace', 'Gold 22k', 'Bengali', 'Stone'),
    ('Necklace', 'Gold 22k', 'Bengali', 'Thread'),
    ('Necklace', 'Gold 22k', 'Bengali', 'Thread Locket'),
    ('Necklace', 'Gold 22k', 'Bombay', 'Enamel'),
    ('Necklace', 'Gold 22k', 'Bombay', 'Mangalsutra'),
    ('Necklace', 'Gold 22k', 'Bombay', 'Plain'),
    ('Necklace', 'Gold 22k', 'Bombay', 'Stone'),
    ('Necklace', 'Gold 22k', 'Chettinadu', 'God'),
    ('Necklace', 'Gold 22k', 'Chettinadu', 'Lakshmi'),
    ('Necklace', 'Gold 22k', 'Chettinadu', 'Nakashi'),
    ('Necklace', 'Gold 22k', 'Chettinadu', 'Plain'),
    ('Necklace', 'Gold 22k', 'Coimbatore', 'Addigai'),
    ('Necklace', 'Gold 22k', 'Coimbatore', 'Adukku Kasu'),
    ('Necklace', 'Gold 22k', 'Coimbatore', 'Enamel'),
    ('Necklace', 'Gold 22k', 'Coimbatore', 'Lakshmi'),
    ('Necklace', 'Gold 22k', 'Coimbatore', 'Mango'),
    ('Necklace', 'Gold 22k', 'Coimbatore', 'Padakka'),
    ('Necklace', 'Gold 22k', 'Coimbatore', 'Pearl Mala'),
    ('Necklace', 'Gold 22k', 'Coimbatore', 'Plain'),
    ('Necklace', 'Gold 22k', 'Coimbatore', 'Stone'),
    ('Necklace', 'Gold 22k', 'Karnataka', 'Avil Mala'),
    ('Necklace', 'Gold 22k', 'Karnataka', 'Black Beeds'),
    ('Necklace', 'Gold 22k', 'Karnataka', 'Coorgi stone'),
    ('Necklace', 'Gold 22k', 'Karnataka', 'Coral'),
    ('Necklace', 'Gold 22k', 'Karnataka', 'Jade'),
    ('Necklace', 'Gold 22k', 'Karnataka', 'Navaratna Mala'),
    ('Necklace', 'Gold 22k', 'Karnataka', 'Pearl Mala'),
    ('Necklace', 'Gold 22k', 'Karnataka', 'Stone Mala'),
    ('Necklace', 'Gold 22k', 'Karnataka Traditional', 'Coral'),
    ('Necklace', 'Gold 22k', 'Karnataka Traditional', 'Lakshmi'),
    ('Necklace', 'Gold 22k', 'Karnataka Traditional', 'Mandakasara'),
    ('Necklace', 'Gold 22k', 'Karnataka Traditional', 'Mangalsutra'),
    ('Necklace', 'Gold 22k', 'Karnataka Traditional', 'Mohanmala'),
    ('Necklace', 'Gold 22k', 'Karnataka Traditional', 'Nellore'),
    ('Necklace', 'Gold 22k', 'Karnataka Traditional', 'Thulasi'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Adukku Kasu'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Coral'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Crystal'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Karingali'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Kasumala'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Kasumala Stone'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Kerala'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Lakshmi'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Lakshmi Stone'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Lappa'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Lappa Layer'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Mango Palaka'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Matte'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Matte Stone'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Mullamuttu'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Mullamuttu Stone'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Nagapadam'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Palakka'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Palakka Thread Locket'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Pearl'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Pearl Mala'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Plain'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Red Sandal'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Rosary'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Rudraksham'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Stone'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Stone Special'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Thread Locket'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Thread Locket God'),
    ('Necklace', 'Gold 22k', 'Kerala', 'Thulasi'),
    ('Necklace', 'Gold 22k', 'Kerala Traditional', 'Black Beeds'),
    ('Necklace', 'Gold 22k', 'Kerala Traditional', 'Coral'),
    ('Necklace', 'Gold 22k', 'Kerala Traditional', 'Elakkathali'),
    ('Necklace', 'Gold 22k', 'Kerala Traditional', 'Palakka'),
    ('Necklace', 'Gold 22k', 'Kerala Traditional', 'Red Sandal Sp'),
    ('Necklace', 'Gold 22k', 'Kerala Traditional', 'Rudraksham Sp'),
    ('Necklace', 'Gold 22k', 'Kerala Traditional', 'Thulasi'),
    ('Necklace', 'Gold 22k', 'Kerala Traditional', 'Traditional'),
    ('Necklace', 'Gold 22k', 'Kerala Traditional', 'Traditional thread locket'),
    ('Necklace', 'Gold 22k', 'Kerala Traditional', 'Traditional Thread Locket Palakka'),
    ('Necklace', 'Gold 22k', 'Kolkata', 'Enamel'),
    ('Necklace', 'Gold 22k', 'Kolkata', 'Mangalsutra'),
    ('Necklace', 'Gold 22k', 'Kolkata', 'Plain'),
    ('Necklace', 'Gold 22k', 'Kolkata', 'Rhodium'),
    ('Necklace', 'Gold 22k', 'Kolkata', 'Stone'),
    ('Necklace', 'Gold 22k', 'Moulding', 'Enamel'),
    ('Necklace', 'Gold 22k', 'Moulding', 'Fancy'),
    ('Necklace', 'Gold 22k', 'Moulding', 'Mangalsutra'),
    ('Necklace', 'Gold 22k', 'Moulding', 'Moulding Stone'),
    ('Necklace', 'Gold 22k', 'Moulding', 'Plain'),
    ('Necklace', 'Gold 22k', 'Moulding', 'Rhodium'),
    ('Necklace', 'Gold 22k', 'Moulding', 'Signity'),
    ('Necklace', 'Gold 22k', 'Moulding', 'Stone'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Balaji'),
    ('Necklace', 'Gold 22k', 'Nagas', 'God'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Lakshmi'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Lakshmi Stone'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Mangalsutra'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Meenakshi'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Nakashi'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Navaratna'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Radha Krishna'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Ram Parivar'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Semi Nagas'),
    ('Necklace', 'Gold 22k', 'Nagas', 'Sita Ram'),
    ('Necklace', 'Gold 22k', 'Rajkot', 'Beeds'),
    ('Necklace', 'Gold 22k', 'Rajkot', 'Black Beeds'),
    ('Necklace', 'Gold 22k', 'Rajkot', 'Mangalsutra'),
    ('Necklace', 'Gold 22k', 'Rajkot', 'Plain'),
    ('Necklace', 'Gold 22k', 'Rajkot', 'Rhodium'),
    ('Necklace', 'Gold 22k', 'Rajkot', 'Rosary'),
    ('Necklace', 'Gold 22k', 'Rajkot', 'Stone'),
    ('Necklace', 'Gold 22k', 'Semi Antique', 'Nakashi'),
    ('Necklace', 'Gold 22k', 'Semi Nagas', 'Nakashi'),
    ('Necklace', 'Gold 22k', 'Semi Turkish', 'Plain'),
    ('Necklace', 'Gold 22k', 'Semi Turkish', 'Rhodium'),
    ('Necklace', 'Gold 22k', 'SIGNITY', 'Lakshmi'),
    ('Necklace', 'Gold 22k', 'Singapore', 'Enamel'),
    ('Necklace', 'Gold 22k', 'Singapore', 'Plain'),
    ('Necklace', 'Gold 22k', 'Singapore', 'Rhodium'),
    ('Necklace', 'Gold 22k', 'Singapore', 'Singapore Stone'),
    ('Necklace', 'Gold 22k', 'Singapore', 'Stone'),
    ('Necklace', 'Gold 22k', 'Turkish', 'Mangalsutra'),
    ('Necklace', 'Gold 22k', 'Turkish', 'Plain'),
    ('Necklace', 'Gold 22k', 'Turkish', 'Rhodium'),
    ('Necklace', 'Gold 22k', 'Turkish', 'Stone'),
    ('Necklace', 'Platinum', 'Platinum', 'Fancy'),
    ('Necklace', 'Platinum', 'Platinum', 'Fusion'),
    ('Necklace', 'Polki', 'Polki', 'Fancy'),
    ('Necklace', 'Polki', 'Polki', 'Jadau'),
    ('Necklace', 'Polki', 'Polki', 'Nakashi'),
    ('Necklace', 'Polki', 'Polki', 'Navaratna'),
    ('Necklace', 'Polki', 'Polki', 'Open Close Setting'),
    ('Necklace', 'Precious', 'Moulding', 'Designer'),
    ('Necklace', 'Precious', 'Moulding', 'Fancy'),
    ('Necklace', 'Precious', 'Moulding', 'Filigree'),
    ('Necklace', 'Precious', 'Moulding', 'Gemstone'),
    ('Necklace', 'Precious', 'Moulding', 'Lakshmi'),
    ('Necklace', 'Precious', 'Moulding', 'Navaratna'),
    ('Necklace', 'Precious', 'Nagas', 'Adukku Kasu'),
    ('Necklace', 'Precious', 'Nagas', 'Filigree'),
    ('Necklace', 'Precious', 'Nagas', 'Gemstone'),
    ('Necklace', 'Precious', 'Nagas', 'God'),
    ('Necklace', 'Precious', 'Nagas', 'Jade'),
    ('Necklace', 'Precious', 'Nagas', 'Kanti'),
    ('Necklace', 'Precious', 'Nagas', 'Lakshmi'),
    ('Necklace', 'Precious', 'Nagas', 'Mango'),
    ('Necklace', 'Precious', 'Nagas', 'Nakashi'),
    ('Necklace', 'Precious', 'Nagas', 'Radha Krishna'),
    ('Necklace', 'Precious', 'Nagas', 'Ram Parivar'),
    ('Necklace', 'Precious', 'Turkish', 'Filigree'),
    ('Necklace', 'Precious', 'Turkish', 'Gemstone'),
    ('Necklace', 'Precious', 'Turkish', 'Lappa'),
    ('Necklace', 'Precious', 'Turkish', 'Layer'),
    ('Necklace', 'Uncut', 'Kerala', 'Mullamuttu'),
    ('Necklace', 'Uncut', 'Moulding', 'Designer'),
    ('Necklace', 'Uncut', 'Moulding', 'Filigree'),
    ('Necklace', 'Uncut', 'Moulding', 'Gemstone'),
    ('Necklace', 'Uncut', 'Moulding', 'Lakshmi'),
    ('Necklace', 'Uncut', 'Moulding', 'Layer'),
    ('Necklace', 'Uncut', 'Moulding', 'Mangalsutra'),
    ('Necklace', 'Uncut', 'Moulding', 'Nakashi'),
    ('Necklace', 'Uncut', 'Nagas', 'Adukku Kasu'),
    ('Necklace', 'Uncut', 'Nagas', 'God'),
    ('Necklace', 'Uncut', 'Nagas', 'Kanti'),
    ('Necklace', 'Uncut', 'Nagas', 'Kasumala'),
    ('Necklace', 'Uncut', 'Nagas', 'Lakshmi'),
    ('Necklace', 'Uncut', 'Nagas', 'Nakashi'),
    ('Necklace', 'Uncut', 'Nagas', 'Radha Krishna'),
    ('Necklace', 'Uncut', 'Nagas', 'Ram Parivar'),
    ('Necklace', 'Uncut', 'Turkish', 'Filigree'),
    ('Necklace', 'Uncut', 'Turkish', 'Gemstone'),
    ('Necklace', 'Uncut', 'Turkish', 'Layer'),
    ('Necklace', 'Uncut', 'Uncut', 'Uncut'),
    ('Nose Pin', 'Diamond', 'Moulding', 'Bugadi'),
    ('Nose Pin', 'Diamond', 'Moulding', 'Closed Setting'),
    ('Nose Pin', 'Diamond', 'Moulding', 'Cluster'),
    ('Nose Pin', 'Diamond', 'Moulding', 'Fancy'),
    ('Nose Pin', 'Diamond', 'Moulding', 'FLORAL'),
    ('Nose Pin', 'Diamond', 'Moulding', 'J Type'),
    ('Nose Pin', 'Diamond', 'Moulding', 'Saniya'),
    ('Nose Pin', 'Diamond', 'Moulding', 'Single Stone'),
    ('Nose Pin', 'Diamond', 'Moulding', 'Star'),
    ('Nose Pin', 'Diamond', 'Moulding', 'Swastik'),
    ('Nose Pin', 'Diamond', 'Navaratna Jewellery', 'Navaratna'),
    ('Nose Pin', 'Gold 18K', '18 Karat', '18 Karat'),
    ('Nose Pin', 'Gold 18K', 'Moulding', 'Stone'),
    ('Nose Pin', 'Precious', 'Precious', 'Precious'),
    ('Odiyyanam', 'Diamond', 'Moulding', 'God'),
    ('Odiyyanam', 'Diamond', 'Moulding', 'Lakshmi'),
    ('Odiyyanam', 'Gold 18K', 'Nagas', 'Meenakshi'),
    ('Odiyyanam', 'Gold 22k', 'Nagas', 'God'),
    ('Odiyyanam', 'Gold 22k', 'Nagas', 'Lakshmi'),
    ('Odiyyanam', 'Gold 22k', 'Nagas', 'Nakashi'),
    ('Odiyyanam', 'Gold 22k', 'Nagas', 'Radha Krishna'),
    ('Odiyyanam', 'Gold 22k', 'Nagas', 'Ram Parivar'),
    ('Odiyyanam', 'Precious', 'Nagas', 'God'),
    ('Odiyyanam', 'Precious', 'Nagas', 'Lakshmi'),
    ('Odiyyanam', 'Precious', 'Nagas', 'Radha Krishna'),
    ('Odiyyanam', 'Uncut', 'Nagas', 'God'),
    ('Odiyyanam', 'Uncut', 'Nagas', 'Lakshmi'),
    ('Odiyyanam', 'Uncut', 'Nagas', 'Nakashi'),
    ('Ovel Bracelet', 'Diamond', 'Moulding', 'Cluster'),
    ('Ovel Bracelet', 'Diamond', 'Moulding', 'Fancy'),
    ('Ovel Bracelet', 'Diamond', 'Moulding', 'Lakshmi'),
    ('Ovel Bracelet', 'Diamond', 'Moulding', 'Nakashi'),
    ('Ovel Bracelet', 'Diamond', 'Moulding', 'Navaratna'),
    ('Ovel Bracelet', 'Diamond', 'Moulding', 'Oval'),
    ('Ovel Bracelet', 'Diamond', 'Moulding', 'Twisted'),
    ('Ovel Bracelet', 'Diamond', 'Navaratna Jewellery', 'Navaratna'),
    ('Ovel Bracelet', 'Gold 14K', 'Italian', 'Cera'),
    ('Ovel Bracelet', 'Gold 14K', 'Italian', 'Cupod'),
    ('Ovel Bracelet', 'Gold 14K', 'Italian', 'Flora'),
    ('Ovel Bracelet', 'Gold 14K', 'Italian', 'Yin-Yang'),
    ('Ovel Bracelet', 'Gold 18K', '18 Karat', '18 Karat'),
    ('Ovel Bracelet', 'Gold 18K', 'Moulding', 'Plain'),
    ('Ovel Bracelet', 'Gold 18K', 'Moulding', 'Stone'),
    ('Ovel Bracelet', 'Platinum', 'Platinum', 'Fancy'),
    ('Ovel Bracelet', 'Platinum', 'Platinum', 'Fusion'),
    ('Ovel Bracelet', 'Polki', 'Polki', 'Jadau'),
    ('Ovel Bracelet', 'Polki', 'Polki', 'Navaratna'),
    ('Ovel Bracelet', 'Polki', 'Polki', 'Open Close Setting'),
    ('Ovel Bracelet', 'Precious', 'Moulding', 'Filigree'),
    ('Ovel Bracelet', 'Precious', 'Moulding', 'Gemstone'),
    ('Ovel Bracelet', 'Precious', 'Moulding', 'Navaratna'),
    ('Ovel Bracelet', 'Precious', 'Nagas', 'Nakashi'),
    ('Ovel Bracelet', 'Precious', 'Precious', 'Precious'),
    ('Ovel Bracelet', 'Precious', 'Uncut', 'Precious'),
    ('Ovel Bracelet', 'Uncut', 'Moulding', 'Filigree'),
    ('Ovel Bracelet', 'Uncut', 'Moulding', 'Gemstone'),
    ('Pendant', 'Diamond', 'Moulding', 'Alphabet'),
    ('Pendant', 'Diamond', 'Moulding', 'Fancy'),
    ('Pendant', 'Diamond', 'Moulding', 'Hanging Thali'),
    ('Pendant', 'Diamond', 'Moulding', 'Lakshmi'),
    ('Pendant', 'Diamond', 'Moulding', 'Mangalsutra'),
    ('Pendant', 'Diamond', 'Moulding', 'Minnu'),
    ('Pendant', 'Diamond', 'Moulding', 'Mugappu'),
    ('Pendant', 'Diamond', 'Moulding', 'Mugappu God'),
    ('Pendant', 'Diamond', 'Moulding', 'Mugappu Lakshmi'),
    ('Pendant', 'Diamond', 'Moulding', 'Open Close Setting'),
    ('Pendant', 'Diamond', 'Moulding', 'Solitaire'),
    ('Pendant', 'Diamond', 'Moulding', 'Tanmaniya'),
    ('Pendant', 'Diamond', 'Moulding', 'Thali'),
    ('Pendant', 'Diamond', 'Navaratna Jewellery', 'Navaratna'),
    ('Pendant', 'Gold 14K', '14 Kt Ornaments', '14 Karat Ornaments'),
    ('Pendant', 'Gold 14K', '14 Kt Ornaments', 'Fancy'),
    ('Pendant', 'Gold 14K', 'Italian', 'Cera'),
    ('Pendant', 'Gold 14K', 'Italian', 'Cupod'),
    ('Pendant', 'Gold 14K', 'Italian', 'Fancy'),
    ('Pendant', 'Gold 14K', 'Italian', 'Flora'),
    ('Pendant', 'Gold 14K', 'Italian', 'Yin-Yang'),
    ('Pendant', 'Gold 14K', 'Moulding', 'Fancy'),
    ('Pendant', 'Gold 18K', '18 Karat', '18 Karat'),
    ('Pendant', 'Gold 18K', 'Italian', 'Rhodium'),
    ('Pendant', 'Gold 18K', 'Moulding', 'Name'),
    ('Pendant', 'Gold 18K', 'Moulding', 'Plain'),
    ('Pendant', 'Gold 18K', 'Moulding', 'Stone'),
    ('Pendant', 'Gold 22k', 'Antique', 'Fancy'),
    ('Pendant', 'Gold 22k', 'Antique', 'Kundan'),
    ('Pendant', 'Gold 22k', 'Antique', 'Nakashi'),
    ('Pendant', 'Gold 22k', 'Antique', 'Stone'),
    ('Pendant', 'Gold 22k', 'Bombay', 'Plain'),
    ('Pendant', 'Gold 22k', 'Bombay', 'Stone'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Addigai'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Arasa Illai Thali'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Coral'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Lakshmi'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Lakshmi Coin'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Lakshmi Dollar'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Mango Stone Thali'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Manjima God'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Mugappu'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Ohm Dollar'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Peacock Thali'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Pearl Thali'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Pillayar Thali'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Plain'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Pottu Thali'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Silluvai Dollar'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Siluvai Thali'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Sokkar Meenakshi Thali'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Stone'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Tamil Thali'),
    ('Pendant', 'Gold 22k', 'Coimbatore', 'Uruttu Potharam'),
    ('Pendant', 'Gold 22k', 'Karnataka', 'Disco Kasu'),
    ('Pendant', 'Gold 22k', 'Karnataka Traditional', 'Gini Buttu'),
    ('Pendant', 'Gold 22k', 'Karnataka Traditional', 'Islamic Thali'),
    ('Pendant', 'Gold 22k', 'Karnataka Traditional', 'Kaasu'),
    ('Pendant', 'Gold 22k', 'Karnataka Traditional', 'Karwar'),
    ('Pendant', 'Gold 22k', 'Karnataka Traditional', 'Lakshmi'),
    ('Pendant', 'Gold 22k', 'Karnataka Traditional', 'M Thali'),
    ('Pendant', 'Gold 22k', 'Karnataka Traditional', 'Mangalore Thali'),
    ('Pendant', 'Gold 22k', 'Karnataka Traditional', 'Mysore Thali'),
    ('Pendant', 'Gold 22k', 'Karnataka Traditional', 'Mysur Thali'),
    ('Pendant', 'Gold 22k', 'Karnataka Traditional', 'Nellore'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Alphabet'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Cross'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Elas'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Elas Round'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Elas Tube'),
    ('Pendant', 'Gold 22k', 'Kerala', 'God'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Kerala Fancy'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Kumbala Om Thali'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Kumbala Plain Thali'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Manjima Cross'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Manjima God'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Manjima Guruvayurappan'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Manjima Jesus'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Manjima Krishna'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Manjima Lakshmi'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Manjima Om'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Manjima Saraswathi'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Minnu'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Nagapadam'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Name'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Palakka'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Pathakam'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Pipe Cross'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Plain'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Plain Thali'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Rudraksham'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Sleeva Cross'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Sleeva Thali'),
    ('Pendant', 'Gold 22k', 'Kerala', 'Solid Cross'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Christian Thali'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Cross'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Minnu'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Moulding'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Name'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Om Thali'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Paksha Thali'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Palakka'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Thali God'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Thali Plain'),
    ('Pendant', 'Gold 22k', 'Kerala Traditional', 'Traditional'),
    ('Pendant', 'Gold 22k', 'Kolkata', 'Enamel'),
    ('Pendant', 'Gold 22k', 'Kolkata', 'Plain'),
    ('Pendant', 'Gold 22k', 'Kolkata', 'Stone'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Alphabet'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Cross'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Enamel'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Fancy'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Fish'),
    ('Pendant', 'Gold 22k', 'Moulding', 'God'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Moulding Stone'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Name'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Om'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Paper Cast'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Plain'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Rhodium'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Signity'),
    ('Pendant', 'Gold 22k', 'Moulding', 'Stone'),
    ('Pendant', 'Gold 22k', 'Nagas', 'Gandaberunda'),
    ('Pendant', 'Gold 22k', 'Nagas', 'God'),
    ('Pendant', 'Gold 22k', 'Nagas', 'Lakshmi'),
    ('Pendant', 'Gold 22k', 'Nagas', 'Nakashi'),
    ('Pendant', 'Gold 22k', 'Nagas', 'Ram Parivar'),
    ('Pendant', 'Gold 22k', 'Rajkot', 'Moulding'),
    ('Pendant', 'Gold 22k', 'Rajkot', 'Plain'),
    ('Pendant', 'Gold 22k', 'Rajkot', 'Rhodium'),
    ('Pendant', 'Gold 22k', 'Rajkot', 'Watti'),
    ('Pendant', 'Gold 22k', 'Semi Antique', 'Nakashi'),
    ('Pendant', 'Gold 22k', 'SIGNITY', 'Closed Setting'),
    ('Pendant', 'Gold 22k', 'Singapore', 'Enamel'),
    ('Pendant', 'Gold 22k', 'Singapore', 'Plain'),
    ('Pendant', 'Gold 22k', 'Singapore', 'Simba'),
    ('Pendant', 'Gold 22k', 'Singapore', 'Singapore'),
    ('Pendant', 'Gold 22k', 'Tamil Traditional', 'Tamil Thali'),
    ('Pendant', 'Gold 22k', 'Turkish', 'Plain'),
    ('Pendant', 'Gold 22k', 'Turkish', 'Turkish'),
    ('Pendant', 'Platinum', 'Platinum', 'Fancy'),
    ('Pendant', 'Platinum', 'Platinum', 'Fusion'),
    ('Pendant', 'Polki', 'Polki', 'Fancy'),
    ('Pendant', 'Polki', 'Polki', 'Jadau'),
    ('Pendant', 'Precious', 'Birth Stone', 'Gemstone'),
    ('Pendant', 'Precious', 'Moulding', 'Gemstone'),
    ('Pendant', 'Precious', 'Nagas', 'Lakshmi'),
    ('Pendant', 'Precious', 'Precious', 'Precious'),
    ('Pendant', 'Precious', 'Turkish', 'Gemstone'),
    ('Pendant', 'Uncut', 'Moulding', 'Gemstone'),
    ('Pendant', 'Uncut', 'Moulding', 'Lakshmi'),
    ('Pendant', 'Uncut', 'Moulding', 'Tiger Nail'),
    ('Pendant', 'Uncut', 'Uncut', 'Uncut'),
    ('Ring', 'Diamond', 'Moulding', 'Closed Setting'),
    ('Ring', 'Diamond', 'Moulding', 'Cluster'),
    ('Ring', 'Diamond', 'Moulding', 'Couple'),
    ('Ring', 'Diamond', 'Moulding', 'Fancy'),
    ('Ring', 'Diamond', 'Moulding', 'God'),
    ('Ring', 'Diamond', 'Moulding', 'Lakshmi'),
    ('Ring', 'Diamond', 'Moulding', 'Pie-Cut'),
    ('Ring', 'Diamond', 'Moulding', 'Radha Krishna'),
    ('Ring', 'Diamond', 'Moulding', 'Solitaire'),
    ('Ring', 'Diamond', 'Moulding', 'Twisted'),
    ('Ring', 'Diamond', 'Moulding', 'Vanki'),
    ('Ring', 'Diamond', 'Navaratna Jewellery', 'Navaratna'),
    ('Ring', 'Gold 14K', '14 Kt Ornaments', '14 Karat Ornaments'),
    ('Ring', 'Gold 14K', '14 Kt Ornaments', 'Fancy'),
    ('Ring', 'Gold 14K', 'Italian', 'Cera'),
    ('Ring', 'Gold 14K', 'Italian', 'Cupod'),
    ('Ring', 'Gold 14K', 'Italian', 'Fancy'),
    ('Ring', 'Gold 14K', 'Italian', 'Flora'),
    ('Ring', 'Gold 14K', 'Italian', 'Yin-Yang'),
    ('Ring', 'Gold 18K', '18 Karat', '18 Karat'),
    ('Ring', 'Gold 18K', 'Moulding', 'Name'),
    ('Ring', 'Gold 18K', 'Moulding', 'Plain'),
    ('Ring', 'Gold 18K', 'Moulding', 'Rhodium'),
    ('Ring', 'Gold 18K', 'Moulding', 'Stone'),
    ('Ring', 'Gold 18K', 'Nagas', 'Meenakshi'),
    ('Ring', 'Gold 22k', 'Antique', 'Enamel'),
    ('Ring', 'Gold 22k', 'Antique', 'Fancy'),
    ('Ring', 'Gold 22k', 'Antique', 'Kundan'),
    ('Ring', 'Gold 22k', 'Antique', 'Nakashi'),
    ('Ring', 'Gold 22k', 'Bombay', 'Enamel'),
    ('Ring', 'Gold 22k', 'Bombay', 'Plain'),
    ('Ring', 'Gold 22k', 'Bombay', 'Rhodium'),
    ('Ring', 'Gold 22k', 'Bombay', 'Stone'),
    ('Ring', 'Gold 22k', 'Chettinadu', 'Cocktail'),
    ('Ring', 'Gold 22k', 'Coimbatore', 'Closed Setting'),
    ('Ring', 'Gold 22k', 'Coimbatore', 'Plain'),
    ('Ring', 'Gold 22k', 'Coimbatore', 'Stone'),
    ('Ring', 'Gold 22k', 'Coimbatore', 'Vangi Closed Setting'),
    ('Ring', 'Gold 22k', 'Coimbatore', 'Vanki'),
    ('Ring', 'Gold 22k', 'Karnataka Traditional', 'Karwar'),
    ('Ring', 'Gold 22k', 'Karnataka Traditional', 'Nellore'),
    ('Ring', 'Gold 22k', 'Kerala', 'Anavaal'),
    ('Ring', 'Gold 22k', 'Kerala', 'God'),
    ('Ring', 'Gold 22k', 'Kerala', 'Katti Ozhukkan'),
    ('Ring', 'Gold 22k', 'Kerala', 'Katti Tv'),
    ('Ring', 'Gold 22k', 'Kerala', 'Kerala'),
    ('Ring', 'Gold 22k', 'Kerala', 'Minchi Pipe'),
    ('Ring', 'Gold 22k', 'Kerala', 'Name'),
    ('Ring', 'Gold 22k', 'Kerala', 'Plain'),
    ('Ring', 'Gold 22k', 'Kerala', 'Polla Ozhukkan'),
    ('Ring', 'Gold 22k', 'Kerala', 'Polla Tv'),
    ('Ring', 'Gold 22k', 'Kerala', 'Rosary'),
    ('Ring', 'Gold 22k', 'Kerala', 'Stone'),
    ('Ring', 'Gold 22k', 'Kerala', 'Turkish'),
    ('Ring', 'Gold 22k', 'Kerala Traditional', 'Anavaal'),
    ('Ring', 'Gold 22k', 'Kerala Traditional', 'Palakka'),
    ('Ring', 'Gold 22k', 'Kerala Traditional', 'Traditional'),
    ('Ring', 'Gold 22k', 'Kolkata', 'Enamel'),
    ('Ring', 'Gold 22k', 'Kolkata', 'Plain'),
    ('Ring', 'Gold 22k', 'Kolkata', 'Stone'),
    ('Ring', 'Gold 22k', 'Kolkata', 'Vanki'),
    ('Ring', 'Gold 22k', 'Moulding', 'Casting'),
    ('Ring', 'Gold 22k', 'Moulding', 'Couple'),
    ('Ring', 'Gold 22k', 'Moulding', 'Fancy'),
    ('Ring', 'Gold 22k', 'Moulding', 'God'),
    ('Ring', 'Gold 22k', 'Moulding', 'Katti Ozhukkan'),
    ('Ring', 'Gold 22k', 'Moulding', 'Moulding Stone'),
    ('Ring', 'Gold 22k', 'Moulding', 'Nagas'),
    ('Ring', 'Gold 22k', 'Moulding', 'Name'),
    ('Ring', 'Gold 22k', 'Moulding', 'Paper Cast'),
    ('Ring', 'Gold 22k', 'Moulding', 'Plain'),
    ('Ring', 'Gold 22k', 'Moulding', 'Rainbow'),
    ('Ring', 'Gold 22k', 'Moulding', 'Rhodium'),
    ('Ring', 'Gold 22k', 'Moulding', 'Signity'),
    ('Ring', 'Gold 22k', 'Moulding', 'Stone'),
    ('Ring', 'Gold 22k', 'Moulding', 'Vangi Stone'),
    ('Ring', 'Gold 22k', 'Moulding', 'Vanki'),
    ('Ring', 'Gold 22k', 'Nagas', 'God'),
    ('Ring', 'Gold 22k', 'Nagas', 'Lakshmi'),
    ('Ring', 'Gold 22k', 'Nagas', 'Nakashi'),
    ('Ring', 'Gold 22k', 'Nagas', 'Radha Krishna'),
    ('Ring', 'Gold 22k', 'Nagas', 'Vangi Stone'),
    ('Ring', 'Gold 22k', 'Rajkot', 'Plain'),
    ('Ring', 'Gold 22k', 'Rajkot', 'Rhodium'),
    ('Ring', 'Gold 22k', 'Rajkot', 'Stone'),
    ('Ring', 'Gold 22k', 'SIGNITY', 'Closed Setting'),
    ('Ring', 'Gold 22k', 'SIGNITY', 'Vanki'),
    ('Ring', 'Gold 22k', 'Singapore', 'Enamel'),
    ('Ring', 'Gold 22k', 'Singapore', 'Plain'),
    ('Ring', 'Gold 22k', 'Singapore', 'Singapore'),
    ('Ring', 'Gold 22k', 'Singapore', 'Singapore Stone'),
    ('Ring', 'Gold 22k', 'Singapore', 'Stone'),
    ('Ring', 'Gold 22k', 'Turkish', 'Plain'),
    ('Ring', 'Gold 22k', 'Turkish', 'Rhodium'),
    ('Ring', 'Gold 22k', 'Turkish', 'Turkish'),
    ('Ring', 'Platinum', 'Platinum', 'Fancy'),
    ('Ring', 'Platinum', 'Platinum', 'Fusion'),
    ('Ring', 'Polki', 'Polki', 'Fancy'),
    ('Ring', 'Polki', 'Polki', 'Jadau'),
    ('Ring', 'Precious', 'Birth Stone', 'Gemstone'),
    ('Ring', 'Precious', 'Moulding', 'Gemstone'),
    ('Ring', 'Precious', 'Moulding', 'Navaratna'),
    ('Ring', 'Precious', 'Nagas', 'Vanki'),
    ('Ring', 'Precious', 'Precious', 'Precious'),
    ('Ring', 'Precious', 'Turkish', 'Gemstone'),
    ('Ring', 'Uncut', 'Moulding', 'Gemstone'),
    ('Ring', 'Uncut', 'Uncut', 'Uncut'),
    ('Stud', 'Diamond', 'Moulding', 'Bugadi'),
    ('Stud', 'Diamond', 'Moulding', 'Classic'),
    ('Stud', 'Diamond', 'Moulding', 'Closed Setting'),
    ('Stud', 'Diamond', 'Moulding', 'Cluster'),
    ('Stud', 'Diamond', 'Moulding', 'Fancy'),
    ('Stud', 'Diamond', 'Moulding', 'Lakshmi'),
    ('Stud', 'Diamond', 'Moulding', 'Meenakshi'),
    ('Stud', 'Diamond', 'Moulding', 'Open Close Setting'),
    ('Stud', 'Diamond', 'Moulding', 'Ram Parivar'),
    ('Stud', 'Diamond', 'Moulding', 'Solitaire'),
    ('Stud', 'Diamond', 'Moulding', 'Twisted'),
    ('Stud', 'Diamond', 'Navaratna Jewellery', 'Navaratna'),
    ('Stud', 'Gold 14K', '14 Kt Ornaments', '14 Karat Ornaments'),
    ('Stud', 'Gold 14K', '14 Kt Ornaments', 'Fancy'),
    ('Stud', 'Gold 14K', 'Italian', 'Cera'),
    ('Stud', 'Gold 14K', 'Italian', 'Cupod'),
    ('Stud', 'Gold 14K', 'Italian', 'Fancy'),
    ('Stud', 'Gold 14K', 'Italian', 'Flora'),
    ('Stud', 'Gold 14K', 'Italian', 'Yin-Yang'),
    ('Stud', 'Gold 14K', 'Moulding', 'Fancy'),
    ('Stud', 'Gold 18K', '18 Karat', '18 Karat'),
    ('Stud', 'Gold 18K', 'Italian', 'Plain'),
    ('Stud', 'Gold 18K', 'Italian', 'Rhodium'),
    ('Stud', 'Gold 18K', 'Moulding', 'Plain'),
    ('Stud', 'Gold 18K', 'Moulding', 'Rhodium'),
    ('Stud', 'Gold 18K', 'Moulding', 'Stone'),
    ('Stud', 'Gold 18K', 'Nagas', 'Meenakshi'),
    ('Stud', 'Gold 22k', 'Antique', 'Elakkathali'),
    ('Stud', 'Gold 22k', 'Antique', 'Fancy'),
    ('Stud', 'Gold 22k', 'Antique', 'Kundan'),
    ('Stud', 'Gold 22k', 'Antique', 'Nagas'),
    ('Stud', 'Gold 22k', 'Antique', 'Nakashi'),
    ('Stud', 'Gold 22k', 'Antique', 'Stone'),
    ('Stud', 'Gold 22k', 'Bombay', 'Enamel'),
    ('Stud', 'Gold 22k', 'Bombay', 'Jhumka'),
    ('Stud', 'Gold 22k', 'Bombay', 'Jhumka Stone'),
    ('Stud', 'Gold 22k', 'Bombay', 'Plain'),
    ('Stud', 'Gold 22k', 'Bombay', 'Rhodium'),
    ('Stud', 'Gold 22k', 'Bombay', 'Stone'),
    ('Stud', 'Gold 22k', 'Chettinadu', 'Chand Bali'),
    ('Stud', 'Gold 22k', 'Chettinadu', 'Chand Bali Stone'),
    ('Stud', 'Gold 22k', 'Chettinadu', 'Jhumka'),
    ('Stud', 'Gold 22k', 'Chettinadu', 'Jhumka Stone'),
    ('Stud', 'Gold 22k', 'Chettinadu', 'Lakshmi'),
    ('Stud', 'Gold 22k', 'Chettinadu', 'Nakashi'),
    ('Stud', 'Gold 22k', 'Coimbatore', 'Adukku Kasu'),
    ('Stud', 'Gold 22k', 'Coimbatore', 'Bali'),
    ('Stud', 'Gold 22k', 'Coimbatore', 'Cbt'),
    ('Stud', 'Gold 22k', 'Coimbatore', 'Closed Setting'),
    ('Stud', 'Gold 22k', 'Coimbatore', 'Jhumka'),
    ('Stud', 'Gold 22k', 'Coimbatore', 'Jhumka Stone'),
    ('Stud', 'Gold 22k', 'Coimbatore', 'Lakshmi'),
    ('Stud', 'Gold 22k', 'Coimbatore', 'Matte'),
    ('Stud', 'Gold 22k', 'Coimbatore', 'Plain'),
    ('Stud', 'Gold 22k', 'Coimbatore', 'Stone'),
    ('Stud', 'Gold 22k', 'Karnataka', 'Stone'),
    ('Stud', 'Gold 22k', 'Karnataka Traditional', 'Karwar'),
    ('Stud', 'Gold 22k', 'Karnataka Traditional', 'Nellore'),
    ('Stud', 'Gold 22k', 'Karnataka Traditional', 'Nellore Bali'),
    ('Stud', 'Gold 22k', 'Karnataka Traditional', 'Nellore Chand Bali'),
    ('Stud', 'Gold 22k', 'Karnataka Traditional', 'Nellore God'),
    ('Stud', 'Gold 22k', 'Karnataka Traditional', 'Nellore Jimkka'),
    ('Stud', 'Gold 22k', 'Karnataka Traditional', 'Nellore Jimkka God'),
    ('Stud', 'Gold 22k', 'Karnataka Traditional', 'Nellore Jimkka Lakshmi'),
    ('Stud', 'Gold 22k', 'Karnataka Traditional', 'Nellore Lakshmi'),
    ('Stud', 'Gold 22k', 'Karnataka Traditional', 'Nellore Nakashi'),
    ('Stud', 'Gold 22k', 'Kerala', 'Bali'),
    ('Stud', 'Gold 22k', 'Kerala', 'God'),
    ('Stud', 'Gold 22k', 'Kerala', 'Jhumka'),
    ('Stud', 'Gold 22k', 'Kerala', 'Karwar'),
    ('Stud', 'Gold 22k', 'Kerala', 'Kerala'),
    ('Stud', 'Gold 22k', 'Kerala', 'Lakshmi'),
    ('Stud', 'Gold 22k', 'Kerala', 'Lakshmi Stone'),
    ('Stud', 'Gold 22k', 'Kerala', 'Palakka'),
    ('Stud', 'Gold 22k', 'Kerala', 'Plain'),
    ('Stud', 'Gold 22k', 'Kerala', 'Stone'),
    ('Stud', 'Gold 22k', 'Kerala Traditional', 'Palakka'),
    ('Stud', 'Gold 22k', 'Kerala Traditional', 'Traditional'),
    ('Stud', 'Gold 22k', 'Kolkata', 'Chand Bali'),
    ('Stud', 'Gold 22k', 'Kolkata', 'Chand Bali Enamel'),
    ('Stud', 'Gold 22k', 'Kolkata', 'Chand Bali Stone'),
    ('Stud', 'Gold 22k', 'Kolkata', 'Enamel'),
    ('Stud', 'Gold 22k', 'Kolkata', 'Jhumka'),
    ('Stud', 'Gold 22k', 'Kolkata', 'Jhumka Enamel'),
    ('Stud', 'Gold 22k', 'Kolkata', 'Jhumka Stone'),
    ('Stud', 'Gold 22k', 'Kolkata', 'Plain'),
    ('Stud', 'Gold 22k', 'Kolkata', 'Stone'),
    ('Stud', 'Gold 22k', 'Moulding', 'Fancy'),
    ('Stud', 'Gold 22k', 'Moulding', 'Moulding Stone'),
    ('Stud', 'Gold 22k', 'Moulding', 'Plain'),
    ('Stud', 'Gold 22k', 'Moulding', 'Rainbow'),
    ('Stud', 'Gold 22k', 'Moulding', 'Rhodium'),
    ('Stud', 'Gold 22k', 'Moulding', 'Signity'),
    ('Stud', 'Gold 22k', 'Moulding', 'Stone'),
    ('Stud', 'Gold 22k', 'Nagas', 'Chand Bali God'),
    ('Stud', 'Gold 22k', 'Nagas', 'Chand Bali Lakshmi'),
    ('Stud', 'Gold 22k', 'Nagas', 'Chand Bali Nakshi'),
    ('Stud', 'Gold 22k', 'Nagas', 'Chand Bali Ram Parivar'),
    ('Stud', 'Gold 22k', 'Nagas', 'God'),
    ('Stud', 'Gold 22k', 'Nagas', 'Jhumka God'),
    ('Stud', 'Gold 22k', 'Nagas', 'Jhumka Lakshmi'),
    ('Stud', 'Gold 22k', 'Nagas', 'Jhumka Nakshi'),
    ('Stud', 'Gold 22k', 'Nagas', 'Jhumka Ram Parivar'),
    ('Stud', 'Gold 22k', 'Nagas', 'Lakshmi'),
    ('Stud', 'Gold 22k', 'Nagas', 'Nakashi'),
    ('Stud', 'Gold 22k', 'Nagas', 'Radha Krishna'),
    ('Stud', 'Gold 22k', 'Nagas', 'Ram Parivar'),
    ('Stud', 'Gold 22k', 'Rajkot', 'Bali'),
    ('Stud', 'Gold 22k', 'Rajkot', 'Plain'),
    ('Stud', 'Gold 22k', 'Rajkot', 'Rhodium'),
    ('Stud', 'Gold 22k', 'Rajkot', 'Stone'),
    ('Stud', 'Gold 22k', 'Semi Antique', 'Nakashi'),
    ('Stud', 'Gold 22k', 'Semi Turkish', 'Plain'),
    ('Stud', 'Gold 22k', 'SIGNITY', 'Closed Setting'),
    ('Stud', 'Gold 22k', 'Singapore', 'Enamel'),
    ('Stud', 'Gold 22k', 'Singapore', 'Plain'),
    ('Stud', 'Gold 22k', 'Singapore', 'Rhodium'),
    ('Stud', 'Gold 22k', 'Singapore', 'Singapore'),
    ('Stud', 'Gold 22k', 'Singapore', 'Singapore Stone'),
    ('Stud', 'Gold 22k', 'Singapore', 'Stone'),
    ('Stud', 'Gold 22k', 'Turkish', 'Plain'),
    ('Stud', 'Gold 22k', 'Turkish', 'Rhodium'),
    ('Stud', 'Gold 22k', 'Turkish', 'Stone'),
    ('Stud', 'Gold 22k', 'Turkish', 'Turkish'),
    ('Stud', 'Gold 22k', 'Turkish', 'Turkish stone'),
    ('Stud', 'Platinum', 'Platinum', 'Fancy'),
    ('Stud', 'Platinum', 'Platinum', 'Fusion'),
    ('Stud', 'Polki', 'Polki', 'Designer'),
    ('Stud', 'Polki', 'Polki', 'Fancy'),
    ('Stud', 'Polki', 'Polki', 'Jadau'),
    ('Stud', 'Precious', 'Moulding', 'Filigree'),
    ('Stud', 'Precious', 'Moulding', 'Gemstone'),
    ('Stud', 'Precious', 'Nagas', 'God'),
    ('Stud', 'Precious', 'Nagas', 'Lakshmi'),
    ('Stud', 'Precious', 'Nagas', 'Nakashi'),
    ('Stud', 'Precious', 'Nagas', 'Radha Krishna'),
    ('Stud', 'Precious', 'Nagas', 'Ram Parivar'),
    ('Stud', 'Precious', 'Precious', 'Precious'),
    ('Stud', 'Precious', 'Turkish', 'Gemstone'),
    ('Stud', 'Uncut', 'Moulding', 'Gemstone'),
    ('Stud', 'Uncut', 'Moulding', 'Jhumka'),
    ('Stud', 'Uncut', 'Moulding', 'Lakshmi'),
    ('Stud', 'Uncut', 'Nagas', 'Lakshmi'),
    ('Stud', 'Uncut', 'Nagas', 'Nakashi'),
    ('Stud', 'Uncut', 'Nagas', 'Ram Parivar'),
    ('Stud', 'Uncut', 'Uncut', 'Uncut');

DROP TABLE IF EXISTS live_combos;
CREATE TEMP TABLE live_combos AS
WITH current_loc AS (
    SELECT DISTINCT ON (product_id) product_id, location_id
    FROM product_location
    WHERE end_time = '2100-01-01 00:00:00+00'
    ORDER BY product_id, start_time DESC
),
pivot AS (
    SELECT
        p.id AS product_id,
        p.product_code,
        p.product_name,
        MAX(CASE WHEN pa.attribute_code = 'CTY' THEN e.value END) AS category,
        MAX(CASE WHEN pa.attribute_code = 'TYP' THEN e.value END) AS product_type,
        MAX(CASE WHEN pa.attribute_code = 'COL' THEN e.value END) AS collection,
        MAX(CASE WHEN pa.attribute_code = 'STL' THEN e.value END) AS style,
        (cl.location_id IS NOT NULL) AS is_unsold
    FROM product p
    JOIN current_loc cl ON cl.product_id = p.id
    JOIN product_attribute_value pav ON pav.product_id = p.id
    JOIN product_attribute pa ON pa.id = pav.attribute_id AND pa.attribute_code IN ('CTY', 'TYP', 'COL', 'STL')
    JOIN product_attribute_enum_value e ON e.id = pav.product_attribute_enum_value_id
	WHERE NOT p.is_box
    GROUP BY p.id, p.product_code, p.product_name, cl.location_id
)
SELECT pv.*
FROM pivot pv
WHERE NOT EXISTS (
        SELECT 1 FROM sheet_combos s
        WHERE LOWER(s.category) = LOWER(pv.category)
          AND LOWER(s.product_type) = LOWER(pv.product_type)
          AND LOWER(s.collection) = LOWER(pv.collection)
          AND LOWER(s.style) = LOWER(pv.style))
  AND LOWER(COALESCE(pv.product_type, '')) NOT IN ('silver', 'repair')
  AND LOWER(COALESCE(pv.category, '')) NOT IN ('silver', 'old ornaments')
  AND LOWER(COALESCE(pv.collection, '')) <> 'box items';

-- Query 1 -- combinations with in-stock products that the sheet doesn't list.
SELECT category, product_type, collection, style,
       COUNT(*) FILTER (WHERE is_unsold) AS unsold_products,
       COUNT(*) FILTER (WHERE NOT is_unsold) AS sold_products
FROM live_combos
GROUP BY category, product_type, collection, style
HAVING COUNT(*) FILTER (WHERE is_unsold) > 0
ORDER BY unsold_products DESC, category, product_type, collection, style;

-- Query 2 -- the individual unsold products.
SELECT product_id, product_code AS barcode, product_name, category, product_type, collection, style
FROM live_combos
WHERE is_unsold
ORDER BY category, product_type, collection, style, product_code;
