-- ============================================================================
-- MIGRATION CHECK, PART 1 -- run FIRST, before add_revised_collections_and_
-- styles.sql, on the database about to be migrated (e.g. prod).
--
-- Saves the untouched state into schema migration_check (real tables, so
-- they survive between sessions): every product, template, attribute value
-- and hierarchy edge, plus the correction rules exactly as the Excel
-- (product_categorization_latest.xlsx, "For IT") states them. Part 2
-- (verify_migration_after.sql) recalculates from these alone what every
-- product and template must look like afterwards -- it does not reuse the
-- migration's own logic -- and reports anything that differs.
--
-- Nothing outside schema migration_check is changed. Take it while nothing
-- else is writing (sold/unsold status is captured here, and the migration
-- must see the same status). Drop the schema when you're done:
--     DROP SCHEMA migration_check CASCADE;
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS migration_check;

DROP TABLE IF EXISTS migration_check.enum_before;
CREATE TABLE migration_check.enum_before AS
SELECT e.id, pa.attribute_code, e.value, e.product_attribute_enum_value_code AS code, e.is_enabled
FROM product_attribute_enum_value e
JOIN product_attribute pa ON pa.id = e.product_attribute_id;

DROP TABLE IF EXISTS migration_check.product_before;
CREATE TABLE migration_check.product_before AS
SELECT
    p.id,
    p.product_name,
    MAX(CASE WHEN pa.attribute_code = 'CTY' THEN pav.product_attribute_enum_value_id END) AS cty_id,
    MAX(CASE WHEN pa.attribute_code = 'TYP' THEN pav.product_attribute_enum_value_id END) AS typ_id,
    MAX(CASE WHEN pa.attribute_code = 'COL' THEN pav.product_attribute_enum_value_id END) AS col_id,
    MAX(CASE WHEN pa.attribute_code = 'STL' THEN pav.product_attribute_enum_value_id END) AS stl_id,
    EXISTS (SELECT 1 FROM product_location pl
            WHERE pl.product_id = p.id AND pl.end_time = '2100-01-01 00:00:00+00'
              AND pl.location_id IS NOT NULL) AS is_unsold
FROM product p
LEFT JOIN product_attribute_value pav ON pav.product_id = p.id
LEFT JOIN product_attribute pa ON pa.id = pav.attribute_id
GROUP BY p.id;

DROP TABLE IF EXISTS migration_check.template_before;
CREATE TABLE migration_check.template_before AS
SELECT
    pt.id,
    pt.product_template_code AS code,
    pt.is_enabled,
    MAX(CASE WHEN pa.attribute_code = 'CTY' THEN t.product_attribute_enum_value_id END) AS cty_id,
    MAX(CASE WHEN pa.attribute_code = 'TYP' THEN t.product_attribute_enum_value_id END) AS typ_id,
    MAX(CASE WHEN pa.attribute_code = 'COL' THEN t.product_attribute_enum_value_id END) AS col_id,
    MAX(CASE WHEN pa.attribute_code = 'STL' THEN t.product_attribute_enum_value_id END) AS stl_id,
    MAX(CASE WHEN pa.attribute_code = 'SPC' THEN t.product_attribute_enum_value_id END) AS spc_id,
    COUNT(t.id) AS attr_count
FROM product_template pt
LEFT JOIN product_template_attribute_value t ON t.product_template_id = pt.id
LEFT JOIN product_attribute pa ON pa.id = t.product_attribute_id
GROUP BY pt.id;

DROP TABLE IF EXISTS migration_check.edge_before;
CREATE TABLE migration_check.edge_before AS
SELECT id, product_attribute_enum_value_id, parent_product_attribute_enum_value_id
FROM product_attribute_enum_hierarchy;

-- The Excel's corrections, as written (old values exactly as in the sheet;
-- NULL = that attribute is not changed). Only 'Ball Uri Katta' -> 'Ball-Uri
-- Katta' is corrected (agreed typo: no such style exists).
DROP TABLE IF EXISTS migration_check.rules;
CREATE TABLE migration_check.rules (
    sheet_row integer, category text, product_type text, collection text, style text,
    new_category text, new_collection text, new_style text);
INSERT INTO migration_check.rules VALUES
    (3, 'Anklet', 'Gold 18K', '18 Carat', '18 Karat', NULL, '18 Karat', NULL),
    (4, 'Anklet', 'Gold 22k', 'Bombay', 'Bombay', NULL, NULL, 'Plain'),
    (5, 'Anklet', 'Gold 22k', 'Bombay', 'NET', NULL, NULL, 'Net'),
    (7, 'Anklet', 'Gold 22k', 'Bombay', 'Rodium', NULL, NULL, 'Rhodium'),
    (8, 'Anklet', 'Gold 22k', 'Coimbatore', 'Fancy', NULL, 'Bombay', 'Plain'),
    (9, 'Anklet', 'Precious', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Savariya'),
    (10, 'Anklet', 'Gold 14K', 'ITALIAN', 'CLASSIC', NULL, 'Italian', 'Fancy'),
    (11, 'Anklet', 'Gold 18K', 'ITALIAN', 'CHARMS', NULL, 'Italian', 'Charms'),
    (12, 'Anklet', 'Gold 18K', 'ITALIAN', 'Plain', NULL, 'Italian', NULL),
    (13, 'Anklet', 'Gold 18K', 'ITALIAN', 'Rodium', NULL, 'Italian', 'Rhodium'),
    (14, 'Anklet', 'Gold 18K', 'ITALIAN', 'Stone', NULL, 'Italian', NULL),
    (15, 'Anklet', 'Gold 22k', 'Kerala', 'Black Beeds', NULL, 'Kerala Traditional', NULL),
    (17, 'Anklet', 'Gold 22k', 'Kerala', 'CHETH', NULL, NULL, 'Cheth'),
    (23, 'Anklet', 'Gold 22k', 'Kerala', 'HIGHWAY', NULL, NULL, 'Highway'),
    (26, 'Anklet', 'Gold 22k', 'Kerala', 'PARASPARAM RODIUM', NULL, 'Rajkot', 'Parasparam Rodium'),
    (30, 'Anklet', 'Gold 22k', 'Kerala', 'Stone Special', NULL, 'Moulding', NULL),
    (32, 'Anklet', 'Gold 22k', 'Kerala', 'TIGHT ARANJAL', NULL, NULL, 'Tight Aranjal'),
    (34, 'Anklet', 'Gold 22k', 'Kerala Special', 'CH-CHETH', NULL, 'Kerala', 'Cheth'),
    (35, 'Anklet', 'Gold 22k', 'Kerala Special', 'Parasparam', NULL, 'Rajkot', NULL),
    (36, 'Anklet', 'Gold 18K', 'MECHINE', 'Box Chain', NULL, 'Bombay', NULL),
    (37, 'Anklet', 'Gold 18K', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (38, 'Anklet', 'Gold 22k', 'Moulding', 'Moulding', NULL, NULL, 'Fancy'),
    (39, 'Anklet', 'Precious', 'Precious', 'Precious', NULL, NULL, 'Savariya'),
    (40, 'Anklet', 'Gold 22k', 'Rajkot', 'Black Beeds', NULL, 'Kerala Traditional', NULL),
    (42, 'Anklet', 'Gold 22k', 'Rajkot', 'Rajkot', NULL, NULL, 'Plain'),
    (43, 'Anklet', 'Gold 22k', 'Rajkot', 'Rodium', NULL, NULL, 'Rhodium'),
    (46, 'Anklet', 'Gold 22k', 'Singapore', 'Rodium', NULL, NULL, 'Rhodium'),
    (47, 'Anklet', 'Gold 22k', 'Singapore', 'Singapore', NULL, NULL, 'Plain'),
    (49, 'Back Chain', 'Gold 18K', '18 Carat', 'Back Chain', NULL, '18 Karat', NULL),
    (51, 'Bangle', 'Gold 18K', '18 Carat', '18 Karat', NULL, '18 Karat', NULL),
    (55, 'Bangle', 'Gold 22k', 'Antique', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (58, 'Bangle', 'Gold 22k', 'Antique Premium', 'Antique', NULL, 'Antique', 'Fancy'),
    (59, 'Bangle', 'Gold 22k', 'BENGALI', 'THREAD', NULL, 'Bombay', 'Thread'),
    (60, 'Bangle', 'Gold 22k', 'Bengali special', 'Bengali', NULL, 'Bombay', 'Plain'),
    (61, 'Bangle', 'Gold 22k', 'Bombay', 'Bombay', NULL, NULL, 'Plain'),
    (65, 'Bangle', 'Gold 22k', 'Bombay', 'HALF ROUND ENAMEL', NULL, NULL, 'Half Round Enamel'),
    (66, 'Bangle', 'Gold 22k', 'Bombay', 'HALF ROUND STONE', NULL, NULL, 'Half Round Stone'),
    (67, 'Bangle', 'Gold 22k', 'Bombay', 'PIPE', NULL, NULL, 'Pipe'),
    (68, 'Bangle', 'Gold 22k', 'Bombay', 'PIPE ENAMEL', NULL, NULL, 'Pipe Enamel'),
    (69, 'Bangle', 'Gold 22k', 'Bombay', 'PIPE RODIUM', NULL, NULL, 'Pipe Rhodium'),
    (71, 'Bangle', 'Gold 22k', 'Bombay', 'Rodium', NULL, NULL, 'Rhodium'),
    (73, 'Bangle', 'Gold 22k', 'Bombay', 'SOLID RODIUM', NULL, NULL, 'Rhodium'),
    (75, 'Bangle', 'Gold 22k', 'Bombay Special', 'CNC', NULL, 'Bombay', 'CNC Cutting'),
    (76, 'Bangle', 'Gold 22k', 'Bombay Special', 'CNC CLASSIC', NULL, 'Bombay', 'CNC Cutting'),
    (77, 'Bangle', 'Gold 22k', 'Bombay Special', 'CNC NORMAL', NULL, 'Bombay', 'CNC Cutting'),
    (78, 'Bangle', 'Gold 22k', 'Bombay Special', 'CNC PREMIUM', NULL, 'Bombay', 'CNC Cutting'),
    (79, 'Bangle', 'Gold 22k', 'Bombay Special', 'Rodium', NULL, 'Bombay', 'Rhodium CNC Cutting'),
    (80, 'Bangle', 'Diamond', 'BRIDAL', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (81, 'Bangle', 'Diamond', 'BRIDAL', 'Lakshmi', NULL, 'Moulding', NULL),
    (82, 'Bangle', 'Gold 22k', 'Chettinadu', 'Chettinadu', NULL, NULL, 'Nakashi'),
    (84, 'Bangle', 'Gold 22k', 'Chettinadu', 'LAKSHMI STONE', NULL, NULL, 'Lakshmi Stone'),
    (85, 'Bangle', 'Gold 22k', 'Chettinadu', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (86, 'Bangle', 'Gold 22k', 'Cnc', 'Enamel', NULL, 'CNC', NULL),
    (87, 'Bangle', 'Gold 22k', 'Cnc', 'EYE', NULL, 'CNC', 'Eye'),
    (88, 'Bangle', 'Gold 22k', 'Cnc', 'God', NULL, 'CNC', NULL),
    (89, 'Bangle', 'Gold 22k', 'Cnc', 'JAGUAR', NULL, 'CNC', 'Jaguar'),
    (90, 'Bangle', 'Gold 22k', 'Cnc', 'LEAF', NULL, 'CNC', 'Leaf'),
    (91, 'Bangle', 'Gold 22k', 'Cnc', 'Plain', NULL, 'CNC', NULL),
    (92, 'Bangle', 'Gold 22k', 'Cnc', 'Rodium', NULL, 'CNC', 'Rhodium'),
    (93, 'Bangle', 'Gold 22k', 'Cnc', 'SIMBA', NULL, 'CNC', 'Simba'),
    (94, 'Bangle', 'Gold 22k', 'Cnc', 'Solid', NULL, 'CNC', 'Plain'),
    (95, 'Bangle', 'Gold 22k', 'Cnc', 'Stone', NULL, 'CNC', NULL),
    (96, 'Bangle', 'Gold 22k', 'Coimbatore', 'CLOSED SETTING', NULL, NULL, 'Closed Setting'),
    (98, 'Bangle', 'Gold 22k', 'Culcutta', 'Culcutta plain', NULL, 'Kolkata', 'Plain'),
    (99, 'Bangle', 'Gold 22k', 'Culcutta', 'Enamel', NULL, 'Kolkata', NULL),
    (100, 'Bangle', 'Gold 22k', 'Culcutta', 'PIPE', NULL, 'Kolkata', 'Pipe'),
    (101, 'Bangle', 'Gold 22k', 'Culcutta', 'PIPE ENAMEL', NULL, 'Kolkata', 'Pipe Enamel'),
    (102, 'Bangle', 'Gold 22k', 'Culcutta', 'Plain', NULL, 'Kolkata', NULL),
    (103, 'Bangle', 'Gold 22k', 'Culcutta', 'Screw', NULL, 'Kolkata', NULL),
    (104, 'Bangle', 'Gold 22k', 'Culcutta', 'SCREW ENAMEL', NULL, 'Kolkata', 'Screw Enamel'),
    (105, 'Bangle', 'Diamond', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (106, 'Bangle', 'Diamond', 'DESIGNER', 'CLUSTER', NULL, 'Moulding', 'Cluster'),
    (107, 'Bangle', 'Diamond', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (108, 'Bangle', 'Diamond', 'HERITAGE', 'CLOSED SETTING', NULL, 'Moulding', 'Closed Setting'),
    (109, 'Bangle', 'Diamond', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (110, 'Bangle', 'Diamond', 'HERITAGE', 'OPEN CLOSE SETTING', NULL, 'Moulding', 'Open Close Setting'),
    (111, 'Bangle', 'Precious', 'HERITAGE', 'FILIGREE', NULL, 'Moulding', 'Filigree'),
    (112, 'Bangle', 'Precious', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (113, 'Bangle', 'Precious', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (114, 'Bangle', 'Precious', 'HERITAGE', 'Navaratna', NULL, 'Moulding', NULL),
    (115, 'Bangle', 'Uncut', 'HERITAGE', 'FILIGREE', NULL, 'Moulding', 'Filigree'),
    (116, 'Bangle', 'Uncut', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (117, 'Bangle', 'Uncut', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (118, 'Bangle', 'Uncut', 'HERITAGE', 'Navaratna', NULL, 'Moulding', NULL),
    (119, 'Bangle', 'Gold 22k', 'Karnataka', 'BELVERY', NULL, NULL, 'Belvery'),
    (124, 'Bangle', 'Gold 22k', 'Karnataka', 'EYE', NULL, 'CNC', 'Eye'),
    (126, 'Bangle', 'Gold 22k', 'Karnataka', 'Lakshmi', NULL, 'Karnataka Traditional', NULL),
    (127, 'Bangle', 'Gold 22k', 'Karnataka', 'LAKSHMI CORAL', NULL, 'Karnataka Traditional', 'Lakshmi Coral'),
    (128, 'Bangle', 'Gold 22k', 'Karnataka', 'LAKSHMI STONE', NULL, 'Karnataka Traditional', 'Lakshmi Stone'),
    (132, 'Bangle', 'Gold 22k', 'Karnataka', 'RAVA', NULL, NULL, 'Rava'),
    (137, 'Bangle', 'Gold 22k', 'Kerala', 'Dhasavatharam', NULL, 'Kerala Traditional', 'Dasavatharam'),
    (138, 'Bangle', 'Gold 22k', 'Kerala', 'DRISHYAM', NULL, NULL, 'Drishyam'),
    (139, 'Bangle', 'Gold 22k', 'Kerala', 'DRISHYAM ENAMEL', NULL, NULL, 'Drishyam Enamel'),
    (145, 'Bangle', 'Gold 22k', 'Kerala', 'LAKSHMI STONE', NULL, NULL, 'Lakshmi Stone'),
    (148, 'Bangle', 'Gold 22k', 'Kerala', 'PIPE', NULL, NULL, 'Pipe'),
    (149, 'Bangle', 'Gold 22k', 'Kerala', 'PIRIYAN PIPE', NULL, NULL, 'Piriyan Pipe'),
    (156, 'Bangle', 'Gold 22k', 'Kerala', 'SOLID RODIUM', NULL, NULL, 'Solid Rodium'),
    (157, 'Bangle', 'Gold 22k', 'Kerala', 'SQUARE OPEN', NULL, NULL, 'Square Open'),
    (159, 'Bangle', 'Gold 22k', 'Kerala', 'SQUARE PIPE RODIUM', NULL, NULL, 'Square Pipe Rodium'),
    (164, 'Bangle', 'Gold 18K', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (166, 'Bangle', 'Gold 22k', 'Moulding', 'Moulding', NULL, NULL, 'Fancy'),
    (169, 'Bangle', 'Gold 22k', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (172, 'Bangle', 'Gold 18K', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (175, 'Bangle', 'Gold 22k', 'Nagas', 'LAKSHMI STONE', NULL, NULL, 'Lakshmi Stone'),
    (176, 'Bangle', 'Gold 22k', 'Nagas', 'MEENAKSHI', NULL, NULL, 'Meenakshi'),
    (177, 'Bangle', 'Gold 22k', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (178, 'Bangle', 'Gold 22k', 'Nagas', 'PEACOCK', NULL, NULL, 'Peacock'),
    (179, 'Bangle', 'Gold 22k', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (180, 'Bangle', 'Gold 22k', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (184, 'Bangle', 'Precious', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (185, 'Bangle', 'Precious', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (186, 'Bangle', 'Precious', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (187, 'Bangle', 'Precious', 'Nagas', 'Vangi', NULL, NULL, 'Vanki'),
    (190, 'Bangle', 'Uncut', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (191, 'Bangle', 'Uncut', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (192, 'Bangle', 'Uncut', 'Nagas', 'Vangi', NULL, NULL, 'Vanki'),
    (193, 'Bangle', 'Gold 22k', 'Nagas Premium', 'Nagas', NULL, 'Nagas', 'Nakashi'),
    (194, 'Bangle', 'Gold 22k', 'Nagas Premium', 'special nagas', NULL, 'Nagas', 'Nakashi'),
    (195, 'Bangle', 'Gold 22k', 'Nellore', 'Nellore', NULL, 'Karnataka Traditional', NULL),
    (196, 'Bangle', 'Gold 22k', 'Nellore', 'Stone', NULL, 'Karnataka Traditional', 'Nellore'),
    (197, 'Bangle', 'Platinum', 'Platinum', 'Platinum', NULL, NULL, 'Fancy'),
    (198, 'Bangle', 'Platinum', 'Platinum', 'Platinum Fusion', NULL, NULL, 'Fusion'),
    (199, 'Bangle', 'Platinum', 'PLATINUM FUSION', 'CLASSIC', NULL, 'Platinum', 'Fusion'),
    (200, 'Bangle', 'Polki', 'Polki', 'Polki', NULL, NULL, 'Fancy'),
    (205, 'Bangle', 'Gold 22k', 'Rajkot', 'Rajkot', NULL, NULL, 'Plain'),
    (206, 'Bangle', 'Gold 22k', 'Rajkot', 'RAJKOT SP', NULL, NULL, 'Plain'),
    (207, 'Bangle', 'Gold 22k', 'Rajkot', 'Rodium', NULL, NULL, 'Rhodium'),
    (209, 'Bangle', 'Gold 22k', 'Semi Antique', 'Semi Antique', NULL, NULL, 'Nakashi'),
    (211, 'Bangle', 'Gold 22k', 'Semi Nagas', 'Semi Nagas', NULL, NULL, 'Nakashi'),
    (212, 'Bangle', 'Diamond', 'SIGNATURE', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (213, 'Bangle', 'Diamond', 'SIGNATURE', 'CLOSED SETTING', NULL, 'Moulding', 'Closed Setting'),
    (214, 'Bangle', 'Diamond', 'SIGNATURE', 'CLUSTER', NULL, 'Moulding', 'Cluster'),
    (215, 'Bangle', 'Gold 22k', 'SIGNITY', 'CLOSED SETTING', NULL, NULL, 'Closed Setting'),
    (216, 'Bangle', 'Gold 22k', 'SIGNITY', 'CLOSED SETTING GOD', NULL, NULL, 'Closed Setting God'),
    (218, 'Bangle', 'Gold 22k', 'Singapore', 'CNC', NULL, NULL, 'Cnc'),
    (222, 'Bangle', 'Gold 22k', 'Singapore', 'SINGAPORE STONE', NULL, NULL, 'Singapore Stone'),
    (224, 'Bangle', 'Diamond', 'SOLITAIRE', 'SOLITAIRE', NULL, 'Moulding', 'Solitaire'),
    (225, 'Bangle', 'Gold 22k', 'Traditional', 'Coorgi', NULL, 'Karnataka Traditional', NULL),
    (226, 'Bangle', 'Gold 22k', 'Traditional', 'Coorgi stone', NULL, 'Karnataka Traditional', NULL),
    (227, 'Bangle', 'Gold 22k', 'Traditional', 'Lakshmi', NULL, 'Karnataka Traditional', NULL),
    (228, 'Bangle', 'Gold 22k', 'Traditional', 'Palakka', NULL, 'Kerala Traditional', NULL),
    (229, 'Bangle', 'Gold 22k', 'Traditional', 'Traditional', NULL, 'Kerala Traditional', NULL),
    (231, 'Bangle', 'Gold 22k', 'Turkish', 'Rodium', NULL, NULL, 'Rhodium'),
    (234, 'Bangle', 'Precious', 'Turkish', 'FILIGREE', NULL, NULL, 'Filigree'),
    (235, 'Bangle', 'Precious', 'Turkish', 'GEMSTONE', NULL, NULL, 'Gemstone'),
    (236, 'Bangle', 'Uncut', 'Turkish', 'GEMSTONE', NULL, NULL, 'Gemstone'),
    (239, 'Bracelet', 'Gold 14K', '14 Carat Ornaments', '14 Karat Ornaments', NULL, '14 Kt Ornaments', NULL),
    (240, 'Bracelet', 'Gold 14K', '14 Carat Ornaments', 'Diamond', NULL, '14 Kt Ornaments', 'Fancy'),
    (241, 'Bracelet', 'Gold 14K', '14 Carat Ornaments', 'Oval', NULL, '14 Kt Ornaments', NULL),
    (242, 'Bracelet', 'Gold 18K', '18 Carat', '18 Karat', NULL, '18 Karat', NULL),
    (244, 'Bracelet', 'Gold 22k', 'Antique', 'MEHNDI STONE', NULL, NULL, 'Mehndi Stone'),
    (245, 'Bracelet', 'Gold 22k', 'Antique Premium', 'Antique', NULL, 'Antique', 'Fancy'),
    (246, 'Bracelet', 'Gold 22k', 'Bombay', 'BISCUIT', NULL, NULL, 'Biscuit'),
    (248, 'Bracelet', 'Gold 22k', 'Bombay', 'Bombay', NULL, NULL, 'Plain'),
    (249, 'Bracelet', 'Gold 22k', 'Bombay', 'CARTIER', NULL, NULL, 'Cartier'),
    (250, 'Bracelet', 'Gold 22k', 'Bombay', 'CUBAN', NULL, NULL, 'Cuban'),
    (252, 'Bracelet', 'Gold 22k', 'Bombay', 'HOLLOW', NULL, NULL, 'Hollow'),
    (255, 'Bracelet', 'Gold 22k', 'Bombay', 'MEHNDI RODIUM', NULL, NULL, 'Mehndi Rodium'),
    (256, 'Bracelet', 'Gold 22k', 'Bombay', 'NAVABI', NULL, NULL, 'Navabi'),
    (257, 'Bracelet', 'Gold 22k', 'Bombay', 'NEW MAGIC', NULL, NULL, 'New Magic'),
    (259, 'Bracelet', 'Gold 22k', 'Bombay', 'Rodium', NULL, NULL, 'Rhodium'),
    (262, 'Bracelet', 'Gold 22k', 'Culcutta', 'Culcutta', NULL, 'Kolkata', 'Plain'),
    (263, 'Bracelet', 'Gold 22k', 'Culcutta', 'Culcutta plain', NULL, 'Kolkata', 'Plain'),
    (264, 'Bracelet', 'Gold 22k', 'Culcutta', 'Culcutta Stone', NULL, 'Kolkata', 'Stone'),
    (265, 'Bracelet', 'Gold 22k', 'Culcutta', 'Plain', NULL, 'Kolkata', NULL),
    (266, 'Bracelet', 'Diamond', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (267, 'Bracelet', 'Diamond', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (268, 'Bracelet', 'Diamond', 'Diamond', 'Oval', NULL, 'Moulding', NULL),
    (269, 'Bracelet', 'Diamond', 'Diamond SI Jewellery', 'Diamond SI', NULL, 'Moulding', 'Fancy'),
    (270, 'Bracelet', 'Polki', 'HERITAGE', 'JADAU', NULL, 'Polki', 'Jadau'),
    (271, 'Bracelet', 'Precious', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (272, 'Bracelet', 'Uncut', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (273, 'Bracelet', 'Gold 14K', 'ITALIAN', 'CERA', NULL, NULL, 'Cera'),
    (274, 'Bracelet', 'Gold 14K', 'ITALIAN', 'CUPOD', NULL, NULL, 'Cupod'),
    (275, 'Bracelet', 'Gold 14K', 'ITALIAN', 'FLORA', NULL, NULL, 'Flora'),
    (276, 'Bracelet', 'Gold 14K', 'ITALIAN', 'YIN-YANG', NULL, NULL, 'Yin-Yang'),
    (279, 'Bracelet', 'Gold 18K', 'ITALIAN', 'Rodium', NULL, 'Italian', 'Rhodium'),
    (281, 'Bracelet', 'Gold 22k', 'KARINGALI', 'KARINGALI', NULL, 'Kerala Traditional', 'Karingali'),
    (284, 'Bracelet', 'Gold 22k', 'Kerala', 'Black Beeds', NULL, 'Kerala Traditional', NULL),
    (289, 'Bracelet', 'Gold 22k', 'Kerala', 'KARINGALI', NULL, NULL, 'Karingali'),
    (292, 'Bracelet', 'Gold 22k', 'Kerala', 'Parasparam', NULL, 'Rajkot', NULL),
    (293, 'Bracelet', 'Gold 22k', 'Kerala', 'PARASPARAM RODIUM', NULL, NULL, 'Parasparam Rodium'),
    (297, 'Bracelet', 'Gold 22k', 'Kerala', 'SANDAL BRACELET', NULL, NULL, 'Sandal Bracelet'),
    (300, 'Bracelet', 'Gold 22k', 'Kerala Special', 'Red Sandal', NULL, 'Kerala Traditional', NULL),
    (301, 'Bracelet', 'Gold 22k', 'Kerala Special', 'Rudraksham', NULL, 'Kerala Traditional', NULL),
    (302, 'Bracelet', 'Gold 22k', 'Kerala Special', 'Thulasi', NULL, 'Kerala Traditional', NULL),
    (303, 'Bracelet', 'Gold 22k', 'MADRASI', 'MADRASI SP', NULL, NULL, 'Madrasi Sp'),
    (307, 'Bracelet', 'Gold 22k', 'Moulding', 'MEHNDI PLAIN', NULL, NULL, 'Mehndi Plain'),
    (308, 'Bracelet', 'Gold 22k', 'Moulding', 'MEHNDI STONE', NULL, NULL, 'Mehndi Stone'),
    (309, 'Bracelet', 'Gold 22k', 'Moulding', 'Moulding', NULL, NULL, 'Fancy'),
    (311, 'Bracelet', 'Gold 22k', 'Moulding', 'Papper Cast', NULL, NULL, 'Paper Cast'),
    (313, 'Bracelet', 'Gold 22k', 'Moulding', 'RAINBOW', NULL, NULL, 'Rainbow'),
    (314, 'Bracelet', 'Gold 22k', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (315, 'Bracelet', 'Gold 22k', 'Moulding', 'SIMBA', NULL, NULL, 'Simba'),
    (319, 'Bracelet', 'Gold 22k', 'Nagas', 'Nagas', NULL, NULL, 'Nakashi'),
    (320, 'Bracelet', 'Gold 22k', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (321, 'Bracelet', 'Gold 22k', 'Nagas', 'SITA RAM', NULL, NULL, 'Sita Ram'),
    (323, 'Bracelet', 'Platinum', 'Platinum', 'CLASSIC', NULL, NULL, 'Fancy'),
    (324, 'Bracelet', 'Platinum', 'Platinum', 'Platinum', NULL, NULL, 'Fancy'),
    (325, 'Bracelet', 'Platinum', 'Platinum', 'Platinum Fusion', NULL, NULL, 'Fusion'),
    (326, 'Bracelet', 'Platinum', 'PLATINUM FUSION', 'CLASSIC', NULL, 'Platinum', 'Fusion'),
    (327, 'Bracelet', 'Polki', 'Polki', 'Polki', NULL, NULL, 'Fancy'),
    (330, 'Bracelet', 'Gold 22k', 'Rajkot', 'Parasparam', NULL, 'Rajkot', NULL),
    (332, 'Bracelet', 'Gold 22k', 'Rajkot', 'Rajkot', NULL, NULL, 'Plain'),
    (333, 'Bracelet', 'Gold 22k', 'Rajkot', 'Rajkot Beeds', NULL, NULL, 'Beeds'),
    (334, 'Bracelet', 'Gold 22k', 'Rajkot', 'Rodium', NULL, NULL, 'Rhodium'),
    (336, 'Bracelet', 'Gold 22k', 'Semi Antique', 'Semi Antique', NULL, NULL, 'Nakashi'),
    (337, 'Bracelet', 'Diamond', 'SIGNATURE', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (338, 'Bracelet', 'Diamond', 'SIGNATURE', 'TENNIS', NULL, 'Moulding', 'Tennis'),
    (339, 'Bracelet', 'Gold 22k', 'Singapore', 'CUBAN', NULL, NULL, 'Cuban'),
    (340, 'Bracelet', 'Gold 22k', 'Singapore', 'DELUXE', NULL, NULL, 'Deluxe'),
    (343, 'Bracelet', 'Gold 22k', 'Singapore', 'Rodium', NULL, NULL, 'Rhodium'),
    (344, 'Bracelet', 'Gold 22k', 'Singapore', 'SIMBA', NULL, NULL, 'Simba'),
    (346, 'Bracelet', 'Gold 22k', 'Singapore', 'SINGAPORE STONE', NULL, NULL, 'Singapore Stone'),
    (349, 'Bracelet', 'Gold 22k', 'Traditional', 'Black Beeds', NULL, 'Kerala Traditional', NULL),
    (350, 'Bracelet', 'Gold 22k', 'Traditional', 'Stone Special', NULL, 'Kerala Traditional', NULL),
    (351, 'Bracelet', 'Gold 22k', 'Traditional', 'Traditional', NULL, 'Kerala Traditional', NULL),
    (353, 'Bracelet', 'Gold 22k', 'Turkish', 'Rodium', NULL, NULL, 'Rhodium'),
    (355, 'Bracelet', 'Gold 22k', 'Turkish', 'TURKISH SPECIAL', NULL, NULL, 'Turkish Special'),
    (356, 'Bracelet', 'Precious', 'Turkish', 'GEMSTONE', NULL, NULL, 'Gemstone'),
    (359, 'Chain', 'Gold 18K', '18 Carat', '18 Karat', NULL, '18 Karat', NULL),
    (360, 'Chain', 'Gold 22k', 'Bombay', 'BISCUIT', NULL, NULL, 'Biscuit'),
    (361, 'Chain', 'Gold 22k', 'Bombay', 'Bombay', NULL, NULL, 'Plain'),
    (364, 'Chain', 'Gold 22k', 'Bombay', 'MADHIRA', NULL, NULL, 'Madhira'),
    (365, 'Chain', 'Gold 22k', 'Bombay', 'MADHIRA CUTTING', NULL, NULL, 'Madhira Cutting'),
    (366, 'Chain', 'Gold 22k', 'Bombay', 'NAVABI', NULL, NULL, 'Navabi'),
    (367, 'Chain', 'Gold 22k', 'Bombay', 'NAVABI KATTA', NULL, NULL, 'Navabi Katta'),
    (368, 'Chain', 'Gold 22k', 'Chain Special', 'Special', NULL, 'Bombay', 'Indo Italian'),
    (369, 'Chain', 'Gold 22k', 'Coimbatore', 'ANUSHKA', NULL, NULL, 'Anushka'),
    (370, 'Chain', 'Gold 22k', 'Coimbatore', 'BAHUBALI', NULL, NULL, 'Bahubali'),
    (371, 'Chain', 'Gold 22k', 'Coimbatore', 'BALL BASHA', NULL, NULL, 'Ball Basha'),
    (374, 'Chain', 'Gold 22k', 'Coimbatore', 'BASHA', NULL, NULL, 'Basha'),
    (375, 'Chain', 'Gold 22k', 'Coimbatore', 'BATTANI', NULL, NULL, 'Battani'),
    (376, 'Chain', 'Gold 22k', 'Coimbatore', 'BATTANI LAYER', NULL, NULL, 'Battani Layer'),
    (377, 'Chain', 'Gold 22k', 'Coimbatore', 'BATTANI MIX', NULL, NULL, 'Battani Mix'),
    (378, 'Chain', 'Gold 22k', 'Coimbatore', 'BATTANI MIX LAYER', NULL, NULL, 'Battani Mix Layer'),
    (379, 'Chain', 'Gold 22k', 'Coimbatore', 'BISCUIT', NULL, NULL, 'Biscuit'),
    (380, 'Chain', 'Gold 22k', 'Coimbatore', 'BULB', NULL, NULL, 'Bulb'),
    (381, 'Chain', 'Gold 22k', 'Coimbatore', 'BULB LAYER', NULL, NULL, 'Bulb Layer'),
    (382, 'Chain', 'Gold 22k', 'Coimbatore', 'CHANDRAMUKHI', NULL, NULL, 'Chandramukhi'),
    (383, 'Chain', 'Gold 22k', 'Coimbatore', 'COIMBATORE FANCY', NULL, NULL, 'Fancy'),
    (385, 'Chain', 'Gold 22k', 'Coimbatore', 'GENTLEMAN', NULL, NULL, 'Gentleman'),
    (386, 'Chain', 'Gold 22k', 'Coimbatore', 'HEART', NULL, NULL, 'Heart'),
    (387, 'Chain', 'Gold 22k', 'Coimbatore', 'HOLLOW CBT', NULL, NULL, 'Hollow Cbt'),
    (388, 'Chain', 'Gold 22k', 'Coimbatore', 'IPL', NULL, NULL, 'Ipl'),
    (389, 'Chain', 'Gold 22k', 'Coimbatore', 'IPL CUTTING', NULL, NULL, 'Ipl Cutting'),
    (390, 'Chain', 'Gold 22k', 'Coimbatore', 'KARBH', NULL, NULL, 'Curb'),
    (391, 'Chain', 'Gold 22k', 'Coimbatore', 'KATTAPPA', NULL, NULL, 'Kattappa'),
    (393, 'Chain', 'Gold 22k', 'Coimbatore', 'MUDICHI THARA', NULL, NULL, 'Mudichi Thara'),
    (396, 'Chain', 'Gold 22k', 'Coimbatore', 'MUGAPPU LAKSHMI', NULL, NULL, 'Mugappu Lakshmi'),
    (397, 'Chain', 'Gold 22k', 'Coimbatore', 'MUGAPPU LAKSHMI STONE', NULL, NULL, 'Mugappu Lakshmi Stone'),
    (398, 'Chain', 'Gold 22k', 'Coimbatore', 'MUGAPPU PEACOCK', NULL, NULL, 'Mugappu Peacock'),
    (399, 'Chain', 'Gold 22k', 'Coimbatore', 'mugappu special', NULL, NULL, 'Mugappu'),
    (401, 'Chain', 'Gold 22k', 'Coimbatore', 'MULLBERRY', NULL, NULL, 'Mullberry'),
    (402, 'Chain', 'Gold 22k', 'Coimbatore', 'NAVABI KATTA', NULL, NULL, 'Navabi Katta'),
    (403, 'Chain', 'Gold 22k', 'Coimbatore', 'PYRAMID', NULL, NULL, 'Pyramid'),
    (404, 'Chain', 'Gold 22k', 'Coimbatore', 'PYRAMID MIX', NULL, NULL, 'Pyramid Mix'),
    (410, 'Chain', 'Gold 22k', 'Coimbatore', 'SQUARE ROPE', NULL, NULL, 'Square Rope'),
    (411, 'Chain', 'Gold 22k', 'Coimbatore', 'THALI KODI', NULL, NULL, 'Thali Kodi'),
    (412, 'Chain', 'Gold 22k', 'Coimbatore', 'TIGHT ARANJAL', NULL, NULL, 'Tight Aranjal'),
    (413, 'Chain', 'Gold 22k', 'Coimbatore', 'TYRE', NULL, NULL, 'Tyre'),
    (414, 'Chain', 'Gold 22k', 'Coimbatore', 'TYRE LAYER', NULL, NULL, 'Tyre Layer'),
    (415, 'Chain', 'Gold 22k', 'Coimbatore', 'TYRE MIX', NULL, NULL, 'Tyre Mix'),
    (416, 'Chain', 'Gold 22k', 'Coimbatore', 'TYRE MIX LAYER', NULL, NULL, 'Tyre Mix Layer'),
    (418, 'Chain', 'Gold 22k', 'Karnataka', 'KATTAPPA', NULL, NULL, 'Kattappa'),
    (421, 'Chain', 'Gold 22k', 'Kerala', 'BALL-URI KATTA', NULL, NULL, 'Ball-Uri Katta'),
    (422, 'Chain', 'Gold 22k', 'Kerala', 'Ball-Uri Katti', NULL, NULL, 'Ball-Uri Katta'),
    (426, 'Chain', 'Gold 22k', 'Kerala', 'DHRUVAM', NULL, NULL, 'Dhruvam'),
    (427, 'Chain', 'Gold 22k', 'Kerala', 'DISCO', NULL, NULL, 'Disco'),
    (431, 'Chain', 'Gold 22k', 'Kerala', 'DOUBLE SIDE KUMALA', NULL, NULL, 'Double Side Kumala'),
    (434, 'Chain', 'Gold 22k', 'Kerala', 'GOPURAM', NULL, NULL, 'Gopuram'),
    (435, 'Chain', 'Gold 22k', 'Kerala', 'HIGHWAY', NULL, NULL, 'Highway'),
    (437, 'Chain', 'Gold 22k', 'Kerala', 'INDIAN RUPEE', NULL, NULL, 'Indian Rupee'),
    (438, 'Chain', 'Gold 22k', 'Kerala', 'KANAKA MALA', NULL, NULL, 'Kanaka Mala'),
    (439, 'Chain', 'Gold 22k', 'Kerala', 'KILUKKAM', NULL, NULL, 'Kilukkam'),
    (442, 'Chain', 'Gold 22k', 'Kerala', 'MOGAMBO', NULL, NULL, 'Mogambo'),
    (443, 'Chain', 'Gold 22k', 'Kerala', 'MONKEYPEN', NULL, NULL, 'Monkeypen'),
    (446, 'Chain', 'Gold 22k', 'Kerala', 'MULLBERRY', NULL, NULL, 'Mullberry'),
    (447, 'Chain', 'Gold 22k', 'Kerala', 'NEELA THAMARA', NULL, NULL, 'Neela Thamara'),
    (448, 'Chain', 'Gold 22k', 'Kerala', 'ONE SIDE KUMALA', NULL, NULL, 'One Side Kumala'),
    (449, 'Chain', 'Gold 22k', 'Kerala', 'OVAL KANNI', NULL, NULL, 'Oval Kanni'),
    (451, 'Chain', 'Gold 22k', 'Kerala', 'Parasparam', NULL, 'Rajkot', NULL),
    (452, 'Chain', 'Gold 22k', 'Kerala', 'PARASPARAM PLAIN', NULL, NULL, 'Parasparam Plain'),
    (453, 'Chain', 'Gold 22k', 'Kerala', 'PARASPARAM RODIUM', NULL, NULL, 'Parasparam Rodium'),
    (455, 'Chain', 'Gold 22k', 'Kerala', 'PUZHU S', NULL, NULL, 'Puzhu S'),
    (468, 'Chain', 'Gold 22k', 'Kerala', 'SQUARE SUNDARI', NULL, NULL, 'Square Sundari'),
    (470, 'Chain', 'Gold 22k', 'Kerala', 'THARA', NULL, NULL, 'Thara'),
    (472, 'Chain', 'Gold 22k', 'Kerala', 'TIGHT ARANJAL', NULL, NULL, 'Tight Aranjal'),
    (474, 'Chain', 'Gold 22k', 'Kerala', 'URI-KATTA', NULL, NULL, 'Uri-Katta'),
    (476, 'Chain', 'Gold 22k', 'Kerala', 'V Chain', NULL, NULL, 'V Chain'),
    (478, 'Chain', 'Gold 22k', 'Kerala Special', 'CH-CHETH', NULL, 'Kerala', 'Cheth'),
    (479, 'Chain', 'Gold 22k', 'Kerala Special', 'KANAKA MALA', NULL, 'Kerala', 'Kanaka Mala'),
    (480, 'Chain', 'Gold 22k', 'Kerala Special', 'MC GF SPECIAL', NULL, NULL, 'Mc Gf Special'),
    (481, 'Chain', 'Gold 22k', 'Kerala Special', 'Parasparam', NULL, 'Rajkot', NULL),
    (482, 'Chain', 'Gold 22k', 'Kerala Special', 'Pulimurugan', NULL, 'Kerala', NULL),
    (483, 'Chain', 'Gold 18K', 'MECHINE', 'Box Chain', NULL, 'Bombay', NULL),
    (484, 'Chain', 'Gold 18K', 'MECHINE', 'BOXCHAIN ROSE GOLD', NULL, 'Bombay', 'Boxchain Rose Gold'),
    (485, 'Chain', 'Gold 18K', 'MECHINE', 'BOXCHAIN YELLOW GOLD', NULL, 'Bombay', 'Boxchain Yellow Gold'),
    (486, 'Chain', 'Gold 22k', 'MECHINE', 'Gold Finger', NULL, 'Kerala', NULL),
    (488, 'Chain', 'Gold 18K', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (490, 'Chain', 'Platinum', 'Platinum', 'CLASSIC', NULL, NULL, 'Fancy'),
    (491, 'Chain', 'Platinum', 'Platinum', 'Platinum', NULL, NULL, 'Fancy'),
    (492, 'Chain', 'Platinum', 'Platinum', 'Platinum Fusion', NULL, NULL, 'Fusion'),
    (493, 'Chain', 'Platinum', 'PLATINUM FUSION', 'CLASSIC', NULL, 'Platinum', 'Fusion'),
    (494, 'Chain', 'Gold 22k', 'Rajkot', 'Rodium', NULL, NULL, 'Rhodium'),
    (496, 'Chain', 'Gold 22k', 'RAJKOT CHAIN', 'RAJKOT SP', NULL, 'Rajkot', 'Plain'),
    (497, 'Chain', 'Gold 22k', 'Singapore', 'BISCUIT', NULL, NULL, 'Biscuit'),
    (498, 'Chain', 'Gold 22k', 'Singapore', 'CUBAN', NULL, NULL, 'Cuban'),
    (501, 'Chain', 'Gold 22k', 'Singapore', 'KAJU KATLI', NULL, NULL, 'Kaju Katli'),
    (504, 'Chain', 'Gold 22k', 'Traditional', 'Manikasu', NULL, 'Kerala Traditional', NULL),
    (505, 'Chain', 'Gold 22k', 'Traditional', 'Traditional', NULL, 'Kerala Traditional', NULL),
    (507, 'Chutti', 'Gold 22k', 'Antique', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (508, 'Chutti', 'Gold 22k', 'Bombay', 'Bombay', NULL, NULL, 'Plain'),
    (510, 'Chutti', 'Diamond', 'BRIDAL', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (511, 'Chutti', 'Diamond', 'BRIDAL', 'God', NULL, 'Moulding', NULL),
    (512, 'Chutti', 'Diamond', 'BRIDAL', 'Lakshmi', NULL, 'Moulding', NULL),
    (513, 'Chutti', 'Gold 22k', 'Culcutta', 'Culcutta plain', NULL, 'Kolkata', 'Plain'),
    (514, 'Chutti', 'Gold 22k', 'Culcutta', 'NAKASHI', NULL, 'Kolkata', 'Nakashi'),
    (515, 'Chutti', 'Gold 22k', 'Culcutta', 'Plain', NULL, 'Kolkata', NULL),
    (516, 'Chutti', 'Gold 22k', 'Culcutta', 'Stone', NULL, 'Kolkata', NULL),
    (517, 'Chutti', 'Diamond', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (518, 'Chutti', 'Diamond', 'DESIGNER', 'Lakshmi', NULL, 'Moulding', NULL),
    (519, 'Chutti', 'Diamond', 'DESIGNER', 'RAM PARIVAR', NULL, 'Moulding', 'Ram Parivar'),
    (520, 'Chutti', 'Diamond', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (521, 'Chutti', 'Precious', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (522, 'Chutti', 'Uncut', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (523, 'Chutti', 'Gold 18K', 'Nagas', 'MEENAKSHI', NULL, NULL, 'Meenakshi'),
    (526, 'Chutti', 'Gold 22k', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (527, 'Chutti', 'Gold 22k', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (528, 'Chutti', 'Gold 22k', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (530, 'Chutti', 'Uncut', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (531, 'Chutti', 'Uncut', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (532, 'Chutti', 'Polki', 'Polki', 'CLASSIC', NULL, NULL, 'Fancy'),
    (533, 'Chutti', 'Precious', 'Turkish', 'GEMSTONE', NULL, NULL, 'Gemstone'),
    (534, 'Chutti', 'Uncut', 'Turkish', 'GEMSTONE', NULL, NULL, 'Gemstone'),
    (540, 'Hip Chain', 'Gold 22k', 'Kerala', 'TIGHT ARANJAL', NULL, NULL, 'Tight Aranjal'),
    (543, 'Matti Chain', 'Gold 22k', 'Antique', 'Antique', NULL, NULL, 'Fancy'),
    (544, 'Matti Chain', 'Gold 22k', 'Antique', 'Ilakka Thali', NULL, NULL, 'Elakkathali'),
    (549, 'Matti Chain', 'Gold 22k', 'Culcutta', 'Culcutta plain', NULL, 'Kolkata', 'Plain'),
    (550, 'Matti Chain', 'Gold 22k', 'Culcutta', 'Enamel', NULL, 'Kolkata', NULL),
    (551, 'Matti Chain', 'Gold 22k', 'Culcutta', 'Plain', NULL, 'Kolkata', NULL),
    (552, 'Matti Chain', 'Precious', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (555, 'Matti Chain', 'Gold 22k', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (556, 'Necklace', 'Gold 14K', '14 Carat Ornaments', '14 Karat Ornaments', NULL, '14 Kt Ornaments', NULL),
    (557, 'Necklace', 'Gold 14K', '14 Carat Ornaments', 'Diamond', NULL, '14 Kt Ornaments', 'Fancy'),
    (558, 'Necklace', 'Gold 18K', '18 Carat', '18 Karat', NULL, '18 Karat', NULL),
    (559, 'Necklace', 'Gold 22k', 'Antique', 'Antique', NULL, NULL, 'Fancy'),
    (561, 'Necklace', 'Gold 22k', 'Antique', 'Ilakka Thali', NULL, NULL, 'Elakkathali'),
    (565, 'Necklace', 'Gold 22k', 'Antique', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (567, 'Necklace', 'Gold 22k', 'BENGALI', 'Plain', NULL, 'Bengali', NULL),
    (568, 'Necklace', 'Gold 22k', 'BENGALI', 'Rodium', NULL, 'Bengali', 'Rhodium'),
    (569, 'Necklace', 'Gold 22k', 'BENGALI', 'Stone', NULL, 'Bengali', NULL),
    (570, 'Necklace', 'Gold 22k', 'BENGALI', 'THREAD', NULL, 'Bengali', 'Thread'),
    (571, 'Necklace', 'Gold 22k', 'BENGALI', 'Thread Locket', NULL, 'Bengali', NULL),
    (572, 'Necklace', 'Gold 22k', 'Bombay', 'Bombay', NULL, NULL, 'Plain'),
    (577, 'Necklace', 'Diamond', 'BRIDAL', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (578, 'Necklace', 'Diamond', 'BRIDAL', 'God', NULL, 'Moulding', NULL),
    (579, 'Necklace', 'Diamond', 'BRIDAL', 'Lakshmi', NULL, 'Moulding', NULL),
    (580, 'Necklace', 'Diamond', 'BRIDAL', 'RADHA KRISHNA', NULL, 'Moulding', 'Radha Krishna'),
    (581, 'Necklace', 'Gold 22k', 'Chettinadu', 'Chettinadu', NULL, NULL, 'Nakashi'),
    (584, 'Necklace', 'Gold 22k', 'Chettinadu', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (586, 'Necklace', 'Gold 22k', 'Coimbatore', 'ADDIGAI', NULL, NULL, 'Addigai'),
    (591, 'Necklace', 'Gold 22k', 'Coimbatore', 'PADAKKA', NULL, NULL, 'Padakka'),
    (592, 'Necklace', 'Gold 22k', 'Coimbatore', 'PEARL MALA', NULL, NULL, 'Pearl Mala'),
    (595, 'Necklace', 'Gold 22k', 'Culcutta', 'Bengali', NULL, 'Kolkata', 'Plain'),
    (596, 'Necklace', 'Gold 22k', 'Culcutta', 'Culcutta plain', NULL, 'Kolkata', 'Plain'),
    (597, 'Necklace', 'Gold 22k', 'Culcutta', 'Culcutta Stone', NULL, 'Kolkata', 'Stone'),
    (598, 'Necklace', 'Gold 22k', 'Culcutta', 'Enamel', NULL, 'Kolkata', NULL),
    (599, 'Necklace', 'Gold 22k', 'Culcutta', 'Mangalsutra', NULL, 'Kolkata', NULL),
    (600, 'Necklace', 'Gold 22k', 'Culcutta', 'Plain', NULL, 'Kolkata', NULL),
    (601, 'Necklace', 'Gold 22k', 'Culcutta', 'Rodium', NULL, 'Kolkata', 'Rhodium'),
    (602, 'Necklace', 'Gold 22k', 'Culcutta', 'Stone', NULL, 'Kolkata', NULL),
    (603, 'Necklace', 'Diamond', 'DESIGNER', 'CHARMS', NULL, 'Moulding', 'Charms'),
    (604, 'Necklace', 'Diamond', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (605, 'Necklace', 'Diamond', 'DESIGNER', 'CLUSTER', NULL, 'Moulding', 'Cluster'),
    (606, 'Necklace', 'Diamond', 'DESIGNER', 'Lakshmi', NULL, 'Moulding', NULL),
    (607, 'Necklace', 'Diamond', 'DESIGNER', 'Navaratna', NULL, 'Moulding', NULL),
    (608, 'Necklace', 'Diamond', 'DESIGNER', 'RADHA KRISHNA', NULL, 'Moulding', 'Radha Krishna'),
    (609, 'Necklace', 'Gold 14K', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (610, 'Necklace', 'Diamond', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (611, 'Necklace', 'Gold 14K', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (612, 'Necklace', 'Diamond', 'Diamond SI Jewellery', 'Diamond SI', NULL, 'Moulding', 'Fancy'),
    (613, 'Necklace', 'Diamond', 'HERITAGE', 'CLASSIC', NULL, 'Moulding', 'Classic'),
    (614, 'Necklace', 'Diamond', 'HERITAGE', 'CLOSED SETTING', NULL, 'Moulding', 'Closed Setting'),
    (615, 'Necklace', 'Diamond', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (616, 'Necklace', 'Diamond', 'HERITAGE', 'Mangalsutra', NULL, 'Moulding', NULL),
    (617, 'Necklace', 'Diamond', 'HERITAGE', 'MEENAKSHI', NULL, 'Moulding', 'Meenakshi'),
    (618, 'Necklace', 'Diamond', 'HERITAGE', 'OPEN CLOSE SETTING', NULL, 'Moulding', 'Open Close Setting'),
    (619, 'Necklace', 'Diamond', 'HERITAGE', 'RADHA KRISHNA', NULL, 'Moulding', 'Radha Krishna'),
    (620, 'Necklace', 'Polki', 'HERITAGE', 'JADAU', NULL, 'Polki', 'Jadau'),
    (621, 'Necklace', 'Polki', 'HERITAGE', 'OPEN CLOSE SETTING', NULL, 'Polki', 'Open Close Setting'),
    (622, 'Necklace', 'Precious', 'HERITAGE', 'Designer', NULL, 'Moulding', NULL),
    (623, 'Necklace', 'Precious', 'HERITAGE', 'FILIGREE', NULL, 'Moulding', 'Filigree'),
    (624, 'Necklace', 'Precious', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (625, 'Necklace', 'Precious', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (626, 'Necklace', 'Precious', 'HERITAGE', 'Navaratna', NULL, 'Moulding', NULL),
    (627, 'Necklace', 'Uncut', 'HERITAGE', 'Designer', NULL, 'Moulding', NULL),
    (628, 'Necklace', 'Uncut', 'HERITAGE', 'FILIGREE', NULL, 'Moulding', 'Filigree'),
    (629, 'Necklace', 'Uncut', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (630, 'Necklace', 'Uncut', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (631, 'Necklace', 'Uncut', 'HERITAGE', 'Layer', NULL, 'Moulding', NULL),
    (632, 'Necklace', 'Uncut', 'HERITAGE', 'Mangalsutra', NULL, 'Moulding', NULL),
    (633, 'Necklace', 'Uncut', 'HERITAGE', 'NAKASHI', NULL, 'Moulding', 'Nakashi'),
    (634, 'Necklace', 'Gold 14K', 'ITALIAN', 'CERA', NULL, 'Italian', 'Cera'),
    (635, 'Necklace', 'Gold 14K', 'ITALIAN', 'CLASSIC', NULL, 'Italian', 'Fancy'),
    (636, 'Necklace', 'Gold 14K', 'ITALIAN', 'CUPOD', NULL, 'Italian', 'Cupod'),
    (637, 'Necklace', 'Gold 14K', 'ITALIAN', 'FLORA', NULL, 'Italian', 'Flora'),
    (638, 'Necklace', 'Gold 14K', 'ITALIAN', 'YIN-YANG', NULL, 'Italian', 'Yin-Yang'),
    (639, 'Necklace', 'Gold 18K', 'ITALIAN', 'Black Beeds', NULL, 'Italian', NULL),
    (640, 'Necklace', 'Gold 18K', 'ITALIAN', 'Plain', NULL, 'Italian', NULL),
    (641, 'Necklace', 'Gold 18K', 'ITALIAN', 'Rodium', NULL, 'Italian', 'Rhodium'),
    (642, 'Necklace', 'Gold 22k', 'Karnataka', 'AVIL MALA', NULL, NULL, 'Avil Mala'),
    (646, 'Necklace', 'Gold 22k', 'Karnataka', 'CORAL MALA', NULL, 'Karnataka Traditional', 'Coral'),
    (648, 'Necklace', 'Gold 22k', 'Karnataka', 'MANDAKASARA', NULL, 'Karnataka Traditional', 'Mandakasara'),
    (649, 'Necklace', 'Gold 22k', 'Karnataka', 'Mangalsutra', NULL, 'Karnataka Traditional', NULL),
    (650, 'Necklace', 'Gold 22k', 'Karnataka', 'MOHANMALA', NULL, 'Karnataka Traditional', 'Mohanmala'),
    (651, 'Necklace', 'Gold 22k', 'Karnataka', 'NAVARATNA MALA', NULL, NULL, 'Navaratna Mala'),
    (652, 'Necklace', 'Gold 22k', 'Karnataka', 'PEARL MALA', NULL, NULL, 'Pearl Mala'),
    (653, 'Necklace', 'Gold 22k', 'Karnataka', 'STONE MALA', NULL, NULL, 'Stone Mala'),
    (654, 'Necklace', 'Gold 22k', 'Karnataka', 'Thulasi', NULL, 'Karnataka Traditional', NULL),
    (656, 'Necklace', 'Gold 22k', 'Kerala', 'Black Beeds', NULL, 'Kerala Traditional', NULL),
    (658, 'Necklace', 'Gold 22k', 'Kerala', 'CRYSTAL', NULL, NULL, 'Crystal'),
    (659, 'Necklace', 'Gold 22k', 'Kerala', 'Ilakka Thali', NULL, 'Kerala Traditional', 'Elakkathali'),
    (660, 'Necklace', 'Gold 22k', 'Kerala', 'KARINGALI', NULL, NULL, 'Karingali'),
    (662, 'Necklace', 'Gold 22k', 'Kerala', 'KASUMALA STONE', NULL, NULL, 'Kasumala Stone'),
    (665, 'Necklace', 'Gold 22k', 'Kerala', 'LAKSHMI STONE', NULL, NULL, 'Lakshmi Stone'),
    (669, 'Necklace', 'Gold 22k', 'Kerala', 'MATTE', NULL, NULL, 'Matte'),
    (670, 'Necklace', 'Gold 22k', 'Kerala', 'MATTE STONE', NULL, NULL, 'Matte Stone'),
    (672, 'Necklace', 'Gold 22k', 'Kerala', 'MULLAMUTTU STONE', NULL, NULL, 'Mullamuttu Stone'),
    (675, 'Necklace', 'Gold 22k', 'Kerala', 'PALAKKA THREAD LOCKET', NULL, NULL, 'Palakka Thread Locket'),
    (677, 'Necklace', 'Gold 22k', 'Kerala', 'PEARL MALA', NULL, NULL, 'Pearl Mala'),
    (685, 'Necklace', 'Gold 22k', 'Kerala', 'THREAD LOCKET GOD', NULL, NULL, 'Thread Locket God'),
    (689, 'Necklace', 'Gold 18K', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (694, 'Necklace', 'Gold 22k', 'Moulding', 'Moulding', NULL, NULL, 'Fancy'),
    (697, 'Necklace', 'Gold 22k', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (701, 'Necklace', 'Diamond', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (702, 'Necklace', 'Gold 18K', 'Nagas', 'MEENAKSHI', NULL, NULL, 'Meenakshi'),
    (703, 'Necklace', 'Gold 22k', 'Nagas', 'BALAJI', NULL, NULL, 'Balaji'),
    (706, 'Necklace', 'Gold 22k', 'Nagas', 'LAKSHMI STONE', NULL, NULL, 'Lakshmi Stone'),
    (708, 'Necklace', 'Gold 22k', 'Nagas', 'MEENAKSHI', NULL, NULL, 'Meenakshi'),
    (709, 'Necklace', 'Gold 22k', 'Nagas', 'Nagas', NULL, NULL, 'Nakashi'),
    (710, 'Necklace', 'Gold 22k', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (712, 'Necklace', 'Gold 22k', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (713, 'Necklace', 'Gold 22k', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (715, 'Necklace', 'Gold 22k', 'Nagas', 'SITA RAM', NULL, NULL, 'Sita Ram'),
    (716, 'Necklace', 'Gold 22k', 'Nagas', 'special nagas', NULL, NULL, 'Nakashi'),
    (718, 'Necklace', 'Precious', 'Nagas', 'FILIGREE', NULL, NULL, 'Filigree'),
    (719, 'Necklace', 'Precious', 'Nagas', 'GEMSTONE', NULL, NULL, 'Gemstone'),
    (722, 'Necklace', 'Precious', 'Nagas', 'KANTI', NULL, NULL, 'Kanti'),
    (725, 'Necklace', 'Precious', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (726, 'Necklace', 'Precious', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (727, 'Necklace', 'Precious', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (730, 'Necklace', 'Uncut', 'Nagas', 'KANTI', NULL, NULL, 'Kanti'),
    (733, 'Necklace', 'Uncut', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (734, 'Necklace', 'Uncut', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (735, 'Necklace', 'Uncut', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (736, 'Necklace', 'Gold 22k', 'Nagas Premium', 'Nagas', NULL, 'Nagas', 'Nakashi'),
    (737, 'Necklace', 'Gold 22k', 'Nagas Premium', 'special nagas', NULL, 'Nagas', 'Nakashi'),
    (738, 'Necklace', 'Gold 22k', 'Nellore', 'Stone', NULL, 'Karnataka Traditional', 'Nellore'),
    (739, 'Necklace', 'Platinum', 'Platinum', 'CLASSIC', NULL, NULL, 'Fancy'),
    (740, 'Necklace', 'Platinum', 'Platinum', 'Platinum', NULL, NULL, 'Fancy'),
    (741, 'Necklace', 'Platinum', 'Platinum', 'Platinum Fusion', NULL, NULL, 'Fusion'),
    (742, 'Necklace', 'Platinum', 'PLATINUM FUSION', 'CLASSIC', NULL, 'Platinum', 'Fusion'),
    (744, 'Necklace', 'Polki', 'Polki', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (746, 'Necklace', 'Polki', 'Polki', 'OPEN CLOSE SETTING', NULL, NULL, 'Open Close Setting'),
    (747, 'Necklace', 'Polki', 'Polki', 'Polki', NULL, NULL, 'Fancy'),
    (748, 'Necklace', 'Precious', 'Precious', 'Precious', NULL, 'Moulding', 'Fancy'),
    (752, 'Necklace', 'Gold 22k', 'Rajkot', 'Rajkot', NULL, NULL, 'Plain'),
    (753, 'Necklace', 'Gold 22k', 'Rajkot', 'Rajkot Beeds', NULL, NULL, 'Beeds'),
    (754, 'Necklace', 'Gold 22k', 'Rajkot', 'Rodium', NULL, NULL, 'Rhodium'),
    (757, 'Necklace', 'Gold 22k', 'RAJKOT CHAIN', 'Rajkot', NULL, 'Rajkot', 'Plain'),
    (758, 'Necklace', 'Gold 22k', 'RED SANDAL', 'RED SANDAL SP', NULL, 'Kerala Traditional', 'Red Sandal Sp'),
    (759, 'Necklace', 'Gold 22k', 'RUDRAKSHAM', 'RUDRAKSHAM SP', NULL, 'Kerala Traditional', 'Rudraksham Sp'),
    (760, 'Necklace', 'Gold 22k', 'Semi Antique', 'Semi Antique', NULL, NULL, 'Nakashi'),
    (761, 'Necklace', 'Gold 22k', 'Semi Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (762, 'Necklace', 'Gold 22k', 'Semi Nagas', 'Semi Nagas', NULL, NULL, 'Nakashi'),
    (763, 'Necklace', 'Gold 22k', 'Semi Turkish', 'Rodium', NULL, NULL, 'Rhodium'),
    (764, 'Necklace', 'Gold 22k', 'Semi Turkish', 'Semi Turkish', NULL, NULL, 'Plain'),
    (765, 'Necklace', 'Diamond', 'SIGNATURE', 'CHARMS', NULL, 'Moulding', 'Charms'),
    (766, 'Necklace', 'Diamond', 'SIGNATURE', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (767, 'Necklace', 'Diamond', 'SIGNATURE', 'CLUSTER', NULL, 'Moulding', 'Cluster'),
    (768, 'Necklace', 'Diamond', 'SIGNATURE', 'Lakshmi', NULL, 'Moulding', NULL),
    (769, 'Necklace', 'Diamond', 'SIGNATURE', 'SOLITAIRE', NULL, 'Moulding', 'Solitaire'),
    (770, 'Necklace', 'Diamond', 'SIGNATURE', 'Twisted', NULL, 'Moulding', NULL),
    (774, 'Necklace', 'Gold 22k', 'Singapore', 'Rodium', NULL, NULL, 'Rhodium'),
    (775, 'Necklace', 'Gold 22k', 'Singapore', 'Singapore', NULL, NULL, 'Plain'),
    (776, 'Necklace', 'Gold 22k', 'Singapore', 'SINGAPORE STONE', NULL, NULL, 'Singapore Stone'),
    (778, 'Necklace', 'Diamond', 'SOLITAIRE', 'SOLITAIRE', NULL, 'Moulding', 'Solitaire'),
    (779, 'Necklace', 'Gold 22k', 'THULASI', 'THULASI SP', NULL, 'Kerala Traditional', 'Thulasi'),
    (780, 'Necklace', 'Gold 22k', 'Traditional', 'Black Beeds', NULL, 'Kerala Traditional', NULL),
    (781, 'Necklace', 'Gold 22k', 'Traditional', 'Coral', NULL, 'Kerala Traditional', NULL),
    (782, 'Necklace', 'Gold 22k', 'Traditional', 'Lakshmi', NULL, 'Karnataka Traditional', NULL),
    (783, 'Necklace', 'Gold 22k', 'Traditional', 'Mangalsutra', NULL, 'Karnataka Traditional', NULL),
    (784, 'Necklace', 'Gold 22k', 'Traditional', 'Palakka', NULL, 'Kerala Traditional', NULL),
    (785, 'Necklace', 'Gold 22k', 'Traditional', 'Palakka-A', NULL, 'Kerala Traditional', 'Palakka'),
    (786, 'Necklace', 'Gold 22k', 'Traditional', 'Palakka-C', NULL, 'Kerala Traditional', 'Palakka'),
    (787, 'Necklace', 'Gold 22k', 'Traditional', 'Traditional', NULL, 'Kerala Traditional', NULL),
    (788, 'Necklace', 'Gold 22k', 'Traditional', 'Traditional thread locket', NULL, 'Kerala Traditional', NULL),
    (789, 'Necklace', 'Gold 22k', 'Traditional', 'TRADITIONAL THREAD LOCKET PALAKKA', NULL, 'Kerala Traditional', 'Traditional Thread Locket Palakka'),
    (792, 'Necklace', 'Gold 22k', 'Turkish', 'Rodium', NULL, NULL, 'Rhodium'),
    (794, 'Necklace', 'Gold 22k', 'Turkish', 'Turkish', NULL, NULL, 'Plain'),
    (795, 'Necklace', 'Gold 22k', 'Turkish', 'TURKISH SPECIAL', NULL, NULL, 'Stone'),
    (796, 'Necklace', 'Precious', 'Turkish', 'FILIGREE', NULL, NULL, 'Filigree'),
    (797, 'Necklace', 'Precious', 'Turkish', 'GEMSTONE', NULL, NULL, 'Gemstone'),
    (800, 'Necklace', 'Uncut', 'Turkish', 'FILIGREE', NULL, NULL, 'Filigree'),
    (801, 'Necklace', 'Uncut', 'Turkish', 'GEMSTONE', NULL, NULL, 'Gemstone'),
    (804, 'Nose Pin', 'Gold 18K', '18 Carat', '18 Karat', NULL, '18 Karat', NULL),
    (805, 'Nose Pin', 'Diamond', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (809, 'Nose Pin', 'Diamond', 'SIGNATURE', 'BUGADI', NULL, 'Moulding', 'Bugadi'),
    (810, 'Nose Pin', 'Diamond', 'SIGNATURE', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (811, 'Nose Pin', 'Diamond', 'SIGNATURE', 'CLOSED SETTING', NULL, 'Moulding', 'Closed Setting'),
    (812, 'Nose Pin', 'Diamond', 'SIGNATURE', 'CLUSTER', NULL, 'Moulding', 'Cluster'),
    (813, 'Nose Pin', 'Diamond', 'SIGNATURE', 'Fancy', NULL, 'Moulding', NULL),
    (814, 'Nose Pin', 'Diamond', 'SIGNATURE', 'Flower', NULL, 'Moulding', 'Floral'),
    (815, 'Nose Pin', 'Diamond', 'SIGNATURE', 'J TYPE', NULL, 'Moulding', 'J Type'),
    (816, 'Nose Pin', 'Diamond', 'SIGNATURE', 'SANIYA', NULL, 'Moulding', 'Saniya'),
    (817, 'Nose Pin', 'Diamond', 'SIGNATURE', 'SINGLE STONE', NULL, 'Moulding', 'Single Stone'),
    (818, 'Nose Pin', 'Diamond', 'SIGNATURE', 'STAR', NULL, 'Moulding', 'Star'),
    (819, 'Nose Pin', 'Diamond', 'SIGNATURE', 'SWASTIK', NULL, 'Moulding', 'Swastik'),
    (820, 'Odiyyanam', 'Diamond', 'BRIDAL', 'God', NULL, 'Moulding', NULL),
    (821, 'Odiyyanam', 'Diamond', 'DESIGNER', 'Lakshmi', NULL, 'Moulding', NULL),
    (822, 'Odiyyanam', 'Gold 18K', 'Nagas', 'MEENAKSHI', NULL, NULL, 'Meenakshi'),
    (825, 'Odiyyanam', 'Gold 22k', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (826, 'Odiyyanam', 'Gold 22k', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (827, 'Odiyyanam', 'Gold 22k', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (830, 'Odiyyanam', 'Precious', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (833, 'Odiyyanam', 'Uncut', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (834, 'Ovel Bracelet', 'Diamond', '14 Carat Ornaments', 'Diamond', 'Bracelet', '14 Kt Ornaments', 'Oval'),
    (835, 'Ovel Bracelet', 'Gold 14K', '14 Carat Ornaments', '14 Karat Ornaments', 'Bracelet', '14 Kt Ornaments', 'Oval'),
    (836, 'Ovel Bracelet', 'Gold 14K', '14 Carat Ornaments', 'Diamond', 'Bracelet', '14 Kt Ornaments', 'Oval'),
    (837, 'Ovel Bracelet', 'Gold 14K', '14 Carat Ornaments', 'Oval', 'Bracelet', '14 Kt Ornaments', 'Oval'),
    (838, 'Ovel Bracelet', 'Gold 18K', '18 Carat', '18 Karat', NULL, '18 Karat', NULL),
    (839, 'Ovel Bracelet', 'Diamond', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (840, 'Ovel Bracelet', 'Diamond', 'DESIGNER', 'CLUSTER', NULL, 'Moulding', 'Cluster'),
    (841, 'Ovel Bracelet', 'Diamond', 'DESIGNER', 'Navaratna', NULL, 'Moulding', NULL),
    (842, 'Ovel Bracelet', 'Diamond', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (843, 'Ovel Bracelet', 'Diamond', 'Diamond', 'Oval', NULL, 'Moulding', NULL),
    (844, 'Ovel Bracelet', 'Diamond', 'Diamond SI Jewellery', 'Diamond SI', NULL, 'Moulding', 'Fancy'),
    (845, 'Ovel Bracelet', 'Diamond', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (846, 'Ovel Bracelet', 'Diamond', 'HERITAGE', 'NAKASHI', NULL, 'Moulding', 'Nakashi'),
    (847, 'Ovel Bracelet', 'Polki', 'HERITAGE', 'JADAU', NULL, 'Polki', 'Jadau'),
    (848, 'Ovel Bracelet', 'Polki', 'HERITAGE', 'Navaratna', NULL, 'Polki', NULL),
    (849, 'Ovel Bracelet', 'Polki', 'HERITAGE', 'OPEN CLOSE SETTING', NULL, 'Polki', 'Open Close Setting'),
    (850, 'Ovel Bracelet', 'Precious', 'HERITAGE', 'FILIGREE', NULL, 'Moulding', 'Filigree'),
    (851, 'Ovel Bracelet', 'Precious', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (852, 'Ovel Bracelet', 'Precious', 'HERITAGE', 'Navaratna', NULL, 'Moulding', NULL),
    (853, 'Ovel Bracelet', 'Uncut', 'HERITAGE', 'FILIGREE', NULL, 'Moulding', 'Filigree'),
    (854, 'Ovel Bracelet', 'Uncut', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (855, 'Ovel Bracelet', 'Gold 14K', 'ITALIAN', 'CERA', NULL, NULL, 'Cera'),
    (856, 'Ovel Bracelet', 'Gold 14K', 'ITALIAN', 'CUPOD', NULL, NULL, 'Cupod'),
    (857, 'Ovel Bracelet', 'Gold 14K', 'ITALIAN', 'FLORA', NULL, NULL, 'Flora'),
    (858, 'Ovel Bracelet', 'Gold 14K', 'ITALIAN', 'YIN-YANG', NULL, NULL, 'Yin-Yang'),
    (861, 'Ovel Bracelet', 'Precious', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (863, 'Ovel Bracelet', 'Gold 14K', 'Ovel Bracelet', '14 Karat Ornaments', 'Bracelet', NULL, NULL),
    (864, 'Ovel Bracelet', 'Platinum', 'Platinum', 'CLASSIC', NULL, NULL, 'Fancy'),
    (865, 'Ovel Bracelet', 'Platinum', 'PLATINUM FUSION', 'CLASSIC', NULL, 'Platinum', 'Fusion'),
    (867, 'Ovel Bracelet', 'Diamond', 'SIGNATURE', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (868, 'Ovel Bracelet', 'Diamond', 'SIGNATURE', 'Twisted', NULL, 'Moulding', NULL),
    (870, 'Pendant', 'Gold 14K', '14 Carat Ornaments', '14 Karat Ornaments', NULL, '14 Kt Ornaments', NULL),
    (871, 'Pendant', 'Gold 14K', '14 Carat Ornaments', 'Diamond', NULL, '14 Kt Ornaments', 'Fancy'),
    (872, 'Pendant', 'Gold 18K', '18 Carat', '18 Karat', NULL, '18 Karat', NULL),
    (873, 'Pendant', 'Gold 22k', 'Antique', 'Antique', NULL, NULL, 'Fancy'),
    (875, 'Pendant', 'Gold 22k', 'Antique', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (877, 'Pendant', 'Gold 22k', 'BENGALI', 'Plain', NULL, 'Bombay', NULL),
    (878, 'Pendant', 'Gold 22k', 'BENGALI', 'Stone', NULL, 'Bombay', NULL),
    (879, 'Pendant', 'Precious', 'BIRTH STONE', 'GEMSTONE', NULL, 'Birth Stone', 'Gemstone'),
    (880, 'Pendant', 'Gold 22k', 'Bombay', 'Bombay', NULL, NULL, 'Plain'),
    (882, 'Pendant', 'Gold 22k', 'Coimbatore', 'ADDIGAI', NULL, NULL, 'Addigai'),
    (883, 'Pendant', 'Gold 22k', 'Coimbatore', 'ARASA ILLAI THALI', NULL, NULL, 'Arasa Illai Thali'),
    (885, 'Pendant', 'Gold 22k', 'Coimbatore', 'LAKSHMI COIN', NULL, NULL, 'Lakshmi Coin'),
    (886, 'Pendant', 'Gold 22k', 'Coimbatore', 'LAKSHMI DOLLAR', NULL, NULL, 'Lakshmi Dollar'),
    (887, 'Pendant', 'Gold 22k', 'Coimbatore', 'MANGO STONE THALI', NULL, NULL, 'Mango Stone Thali'),
    (888, 'Pendant', 'Gold 22k', 'Coimbatore', 'MANJIMA GOD', NULL, NULL, 'Manjima God'),
    (890, 'Pendant', 'Gold 22k', 'Coimbatore', 'OHM DOLLAR', NULL, NULL, 'Ohm Dollar'),
    (891, 'Pendant', 'Gold 22k', 'Coimbatore', 'PEACOCK THALI', NULL, NULL, 'Peacock Thali'),
    (892, 'Pendant', 'Gold 22k', 'Coimbatore', 'PEARL THALI', NULL, NULL, 'Pearl Thali'),
    (893, 'Pendant', 'Gold 22k', 'Coimbatore', 'PERAL RED', NULL, NULL, 'Coral'),
    (894, 'Pendant', 'Gold 22k', 'Coimbatore', 'PILLAYAR THALI', NULL, NULL, 'Pillayar Thali'),
    (896, 'Pendant', 'Gold 22k', 'Coimbatore', 'POTTU THALI', NULL, NULL, 'Pottu Thali'),
    (897, 'Pendant', 'Gold 22k', 'Coimbatore', 'SILLUVAI DOLLAR', NULL, NULL, 'Silluvai Dollar'),
    (898, 'Pendant', 'Gold 22k', 'Coimbatore', 'SILUVAI THALI', NULL, NULL, 'Siluvai Thali'),
    (899, 'Pendant', 'Gold 22k', 'Coimbatore', 'SOKKAR MEENAKSHI THALI', NULL, NULL, 'Sokkar Meenakshi Thali'),
    (902, 'Pendant', 'Gold 22k', 'Coimbatore', 'URUTTU POTHARAM', NULL, NULL, 'Uruttu Potharam'),
    (903, 'Pendant', 'Gold 22k', 'Culcutta', 'Culcutta Enamel', NULL, 'Kolkata', 'Enamel'),
    (904, 'Pendant', 'Gold 22k', 'Culcutta', 'Culcutta plain', NULL, 'Kolkata', 'Plain'),
    (905, 'Pendant', 'Gold 22k', 'Culcutta', 'Culcutta Stone', NULL, 'Kolkata', 'Stone'),
    (906, 'Pendant', 'Gold 22k', 'Culcutta', 'Enamel', NULL, 'Kolkata', NULL),
    (907, 'Pendant', 'Gold 22k', 'Culcutta', 'Plain', NULL, 'Kolkata', NULL),
    (908, 'Pendant', 'Gold 22k', 'Culcutta', 'Stone', NULL, 'Kolkata', NULL),
    (909, 'Pendant', 'Diamond', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (910, 'Pendant', 'Diamond', 'DESIGNER', 'TANMANIYA', NULL, 'Moulding', 'Tanmaniya'),
    (911, 'Pendant', 'Gold 14K', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (912, 'Pendant', 'Diamond', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (913, 'Pendant', 'Gold 14K', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (914, 'Pendant', 'Diamond', 'Diamond SI Jewellery', 'Diamond SI', NULL, 'Moulding', 'Fancy'),
    (915, 'Pendant', 'Diamond', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (916, 'Pendant', 'Diamond', 'HERITAGE', 'Mangalsutra', NULL, 'Moulding', NULL),
    (917, 'Pendant', 'Diamond', 'HERITAGE', 'Mugappu', NULL, 'Moulding', NULL),
    (918, 'Pendant', 'Diamond', 'HERITAGE', 'Mugappu God', NULL, 'Moulding', NULL),
    (919, 'Pendant', 'Diamond', 'HERITAGE', 'MUGAPPU LAKSHMI', NULL, 'Moulding', 'Mugappu Lakshmi'),
    (920, 'Pendant', 'Diamond', 'HERITAGE', 'OPEN CLOSE SETTING', NULL, 'Moulding', 'Open Close Setting'),
    (921, 'Pendant', 'Polki', 'HERITAGE', 'JADAU', NULL, 'Polki', 'Jadau'),
    (922, 'Pendant', 'Precious', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (923, 'Pendant', 'Uncut', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (924, 'Pendant', 'Uncut', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (925, 'Pendant', 'Uncut', 'HERITAGE', 'TIGER NAIL', NULL, 'Moulding', 'Tiger Nail'),
    (926, 'Pendant', 'Gold 14K', 'ITALIAN', 'CERA', NULL, NULL, 'Cera'),
    (927, 'Pendant', 'Gold 14K', 'ITALIAN', 'CLASSIC', NULL, 'Italian', 'Fancy'),
    (928, 'Pendant', 'Gold 14K', 'ITALIAN', 'CUPOD', NULL, NULL, 'Cupod'),
    (929, 'Pendant', 'Gold 14K', 'ITALIAN', 'FLORA', NULL, NULL, 'Flora'),
    (930, 'Pendant', 'Gold 14K', 'ITALIAN', 'YIN-YANG', NULL, NULL, 'Yin-Yang'),
    (931, 'Pendant', 'Gold 18K', 'ITALIAN', 'Rodium', NULL, 'Italian', 'Rhodium'),
    (932, 'Pendant', 'Gold 22k', 'Karnataka', 'DISCO KASU', NULL, NULL, 'Disco Kasu'),
    (933, 'Pendant', 'Gold 22k', 'Karnataka', 'Gini Buttu', NULL, 'Karnataka Traditional', NULL),
    (934, 'Pendant', 'Gold 22k', 'Karnataka', 'Lakshmi', NULL, 'Karnataka Traditional', NULL),
    (935, 'Pendant', 'Gold 22k', 'Karnataka', 'LAKSHMI KAASHI', NULL, 'Karnataka Traditional', 'Kaasu'),
    (936, 'Pendant', 'Gold 22k', 'Karnataka', 'M Thali', NULL, 'Karnataka Traditional', NULL),
    (937, 'Pendant', 'Gold 22k', 'Karnataka', 'MYSUR THALI', NULL, 'Karnataka Traditional', 'Mysur Thali'),
    (938, 'Pendant', 'Gold 22k', 'Karwar', 'Karwar', NULL, 'Karnataka Traditional', NULL),
    (945, 'Pendant', 'Gold 22k', 'Kerala', 'KERALA FANCY', NULL, NULL, 'Kerala Fancy'),
    (946, 'Pendant', 'Gold 22k', 'Kerala', 'KUMBALA OHM THALI', NULL, NULL, 'Kumbala Om Thali'),
    (947, 'Pendant', 'Gold 22k', 'Kerala', 'KUMBALA PLAIN THALI', NULL, NULL, 'Kumbala Plain Thali'),
    (948, 'Pendant', 'Gold 22k', 'Kerala', 'MANJIMA CROSS', NULL, NULL, 'Manjima Cross'),
    (949, 'Pendant', 'Gold 22k', 'Kerala', 'MANJIMA GOD', NULL, NULL, 'Manjima God'),
    (950, 'Pendant', 'Gold 22k', 'Kerala', 'MANJIMA GURUVAYURAPPAN', NULL, NULL, 'Manjima Guruvayurappan'),
    (951, 'Pendant', 'Gold 22k', 'Kerala', 'MANJIMA JESUS', NULL, NULL, 'Manjima Jesus'),
    (952, 'Pendant', 'Gold 22k', 'Kerala', 'MANJIMA KRISHNA', NULL, NULL, 'Manjima Krishna'),
    (953, 'Pendant', 'Gold 22k', 'Kerala', 'MANJIMA LAKSHMI', NULL, NULL, 'Manjima Lakshmi'),
    (954, 'Pendant', 'Gold 22k', 'Kerala', 'MANJIMA OM', NULL, NULL, 'Manjima Om'),
    (955, 'Pendant', 'Gold 22k', 'Kerala', 'MANJIMA SARASWATHI', NULL, NULL, 'Manjima Saraswathi'),
    (959, 'Pendant', 'Gold 22k', 'Kerala', 'Ohm Thali', NULL, 'Kerala Traditional', 'Om Thali'),
    (962, 'Pendant', 'Gold 22k', 'Kerala', 'PIPE CROSS', NULL, NULL, 'Pipe Cross'),
    (965, 'Pendant', 'Gold 22k', 'Kerala', 'SLEEVA CROSS', NULL, NULL, 'Sleeva Cross'),
    (966, 'Pendant', 'Gold 22k', 'Kerala', 'SLEEVA THALI', NULL, NULL, 'Sleeva Thali'),
    (967, 'Pendant', 'Gold 22k', 'Kerala', 'SOLID CROSS', NULL, NULL, 'Solid Cross'),
    (968, 'Pendant', 'Gold 22k', 'Kerala Special', 'Bengali', NULL, 'Kerala', 'Plain'),
    (969, 'Pendant', 'Gold 22k', 'Kerala Special', 'Kerala', NULL, 'Kerala', 'Plain'),
    (976, 'Pendant', 'Gold 22k', 'Moulding', 'FISH', NULL, NULL, 'Fish'),
    (978, 'Pendant', 'Gold 22k', 'Moulding', 'Moulding', NULL, NULL, 'Fancy'),
    (981, 'Pendant', 'Gold 22k', 'Moulding', 'OHM', NULL, NULL, 'Om'),
    (982, 'Pendant', 'Gold 22k', 'Moulding', 'Papper Cast', NULL, NULL, 'Paper Cast'),
    (984, 'Pendant', 'Gold 22k', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (987, 'Pendant', 'Gold 22k', 'Nagas', 'GANDABERUNDA', NULL, NULL, 'Gandaberunda'),
    (990, 'Pendant', 'Gold 22k', 'Nagas', 'Nagas', NULL, NULL, 'Nakashi'),
    (991, 'Pendant', 'Gold 22k', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (992, 'Pendant', 'Gold 22k', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (995, 'Pendant', 'Gold 22k', 'Nellore', 'Nellore', NULL, 'Karnataka Traditional', NULL),
    (996, 'Pendant', 'Gold 22k', 'Nellore', 'Stone', NULL, 'Karnataka Traditional', 'Nellore'),
    (997, 'Pendant', 'Platinum', 'Platinum', 'CLASSIC', NULL, NULL, 'Fancy'),
    (998, 'Pendant', 'Platinum', 'Platinum', 'Platinum', NULL, NULL, 'Fancy'),
    (999, 'Pendant', 'Platinum', 'Platinum', 'Platinum Fusion', NULL, NULL, 'Fusion'),
    (1000, 'Pendant', 'Platinum', 'PLATINUM FUSION', 'CLASSIC', NULL, 'Platinum', 'Fusion'),
    (1001, 'Pendant', 'Polki', 'Polki', 'Polki', NULL, NULL, 'Fancy'),
    (1005, 'Pendant', 'Gold 22k', 'Rajkot', 'Rajkot', NULL, NULL, 'Plain'),
    (1006, 'Pendant', 'Gold 22k', 'Rajkot', 'Rodium', NULL, NULL, 'Rhodium'),
    (1007, 'Pendant', 'Gold 22k', 'Rajkot', 'WATTI', NULL, NULL, 'Watti'),
    (1008, 'Pendant', 'Gold 22k', 'Semi Antique', 'Semi Antique', NULL, NULL, 'Nakashi'),
    (1009, 'Pendant', 'Diamond', 'SIGNATURE', 'Alphabet', NULL, 'Moulding', NULL),
    (1010, 'Pendant', 'Diamond', 'SIGNATURE', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (1011, 'Pendant', 'Diamond', 'SIGNATURE', 'HANGING THALI', NULL, 'Moulding', 'Hanging Thali'),
    (1012, 'Pendant', 'Diamond', 'SIGNATURE', 'Minnu', NULL, 'Moulding', NULL),
    (1013, 'Pendant', 'Diamond', 'SIGNATURE', 'TANMANIYA', NULL, 'Moulding', 'Tanmaniya'),
    (1014, 'Pendant', 'Diamond', 'SIGNATURE', 'THALI', NULL, 'Moulding', 'Thali'),
    (1015, 'Pendant', 'Gold 22k', 'SIGNITY', 'CLOSED SETTING', NULL, NULL, 'Closed Setting'),
    (1018, 'Pendant', 'Gold 22k', 'Singapore', 'SIMBA', NULL, NULL, 'Simba'),
    (1020, 'Pendant', 'Diamond', 'SOLITAIRE', 'SOLITAIRE', NULL, 'Moulding', 'Solitaire'),
    (1021, 'Pendant', 'Gold 22k', 'Traditional', 'Christian Thali', NULL, 'Kerala Traditional', NULL),
    (1022, 'Pendant', 'Gold 22k', 'Traditional', 'Cross', NULL, 'Kerala Traditional', NULL),
    (1023, 'Pendant', 'Gold 22k', 'Traditional', 'Gini Buttu', NULL, 'Karnataka Traditional', NULL),
    (1024, 'Pendant', 'Gold 22k', 'Traditional', 'Islamic Thali', NULL, 'Karnataka Traditional', NULL),
    (1025, 'Pendant', 'Gold 22k', 'Traditional', 'M Thali', NULL, 'Karnataka Traditional', NULL),
    (1026, 'Pendant', 'Gold 22k', 'Traditional', 'Mangalore Thali', NULL, 'Karnataka Traditional', NULL),
    (1027, 'Pendant', 'Gold 22k', 'Traditional', 'Minnu', NULL, 'Kerala Traditional', NULL),
    (1028, 'Pendant', 'Gold 22k', 'Traditional', 'Moulding', NULL, 'Kerala Traditional', NULL),
    (1029, 'Pendant', 'Gold 22k', 'Traditional', 'Mysore Thali', NULL, 'Karnataka Traditional', NULL),
    (1030, 'Pendant', 'Gold 22k', 'Traditional', 'Name', NULL, 'Kerala Traditional', NULL),
    (1031, 'Pendant', 'Gold 22k', 'Traditional', 'Ohm Thali', NULL, 'Kerala Traditional', 'Om Thali'),
    (1032, 'Pendant', 'Gold 22k', 'Traditional', 'Paksha Thali', NULL, 'Kerala Traditional', NULL),
    (1033, 'Pendant', 'Gold 22k', 'Traditional', 'Palakka', NULL, 'Kerala Traditional', NULL),
    (1034, 'Pendant', 'Gold 22k', 'Traditional', 'Tamil Thali', NULL, 'Tamil Traditional', NULL),
    (1035, 'Pendant', 'Gold 22k', 'Traditional', 'Thali God', NULL, 'Kerala Traditional', NULL),
    (1036, 'Pendant', 'Gold 22k', 'Traditional', 'Thali Plain', NULL, 'Kerala Traditional', NULL),
    (1037, 'Pendant', 'Gold 22k', 'Traditional', 'Traditional', NULL, 'Kerala Traditional', NULL),
    (1040, 'Pendant', 'Precious', 'Turkish', 'GEMSTONE', NULL, NULL, 'Gemstone'),
    (1042, 'Ring', 'Gold 14K', '14 Carat Ornaments', '14 Karat Ornaments', NULL, '14 Kt Ornaments', NULL),
    (1043, 'Ring', 'Gold 14K', '14 Carat Ornaments', 'Diamond', NULL, '14 Kt Ornaments', 'Fancy'),
    (1044, 'Ring', 'Gold 18K', '18 Carat', '18 Karat', NULL, '18 Karat', NULL),
    (1045, 'Ring', 'Gold 22k', 'Antique', 'Antique', NULL, NULL, 'Fancy'),
    (1048, 'Ring', 'Gold 22k', 'Antique', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (1049, 'Ring', 'Gold 22k', 'BENGALI', 'Bengali', NULL, 'Bombay', 'Plain'),
    (1050, 'Ring', 'Gold 22k', 'BENGALI', 'Enamel', NULL, 'Bombay', NULL),
    (1051, 'Ring', 'Gold 22k', 'BENGALI', 'Plain', NULL, 'Bombay', NULL),
    (1052, 'Ring', 'Gold 22k', 'BENGALI', 'Stone', NULL, 'Bombay', NULL),
    (1053, 'Ring', 'Precious', 'BIRTH STONE', 'GEMSTONE', NULL, 'Birth Stone', 'Gemstone'),
    (1054, 'Ring', 'Gold 22k', 'Bombay', 'Bombay', NULL, NULL, 'Plain'),
    (1056, 'Ring', 'Gold 22k', 'Bombay', 'Rodium', NULL, NULL, 'Rhodium'),
    (1058, 'Ring', 'Gold 22k', 'Chettinadu', 'Chettinadu', NULL, NULL, 'Cocktail'),
    (1059, 'Ring', 'Gold 22k', 'Coimbatore', 'CLOSED SETTING', NULL, NULL, 'Closed Setting'),
    (1062, 'Ring', 'Gold 22k', 'Coimbatore', 'Vangi', NULL, NULL, 'Vanki'),
    (1063, 'Ring', 'Gold 22k', 'Coimbatore', 'VANGI CLOSED SETTING', NULL, NULL, 'Vangi Closed Setting'),
    (1064, 'Ring', 'Gold 22k', 'Culcutta', 'CALCUTTA VANGI RING ENAMEL', NULL, 'Kolkata', 'Vanki'),
    (1065, 'Ring', 'Gold 22k', 'Culcutta', 'Culcutta plain', NULL, 'Kolkata', 'Plain'),
    (1066, 'Ring', 'Gold 22k', 'Culcutta', 'Culcutta Stone', NULL, 'Kolkata', 'Stone'),
    (1067, 'Ring', 'Gold 22k', 'Culcutta', 'Enamel', NULL, 'Kolkata', NULL),
    (1068, 'Ring', 'Gold 22k', 'Culcutta', 'Plain', NULL, 'Kolkata', NULL),
    (1069, 'Ring', 'Gold 22k', 'Culcutta', 'Vangi', NULL, 'Kolkata', 'Vanki'),
    (1070, 'Ring', 'Diamond', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (1071, 'Ring', 'Diamond', 'DESIGNER', 'CLUSTER', NULL, 'Moulding', 'Cluster'),
    (1072, 'Ring', 'Diamond', 'DESIGNER', 'PIE-CUT', NULL, 'Moulding', 'Pie-Cut'),
    (1073, 'Ring', 'Diamond', 'DESIGNER', 'Vangi', NULL, 'Moulding', 'Vanki'),
    (1074, 'Ring', 'Diamond', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (1075, 'Ring', 'Diamond', 'Diamond SI Jewellery', 'Diamond SI', NULL, 'Moulding', 'Fancy'),
    (1076, 'Ring', 'Diamond', 'HERITAGE', 'CLOSED SETTING', NULL, 'Moulding', 'Closed Setting'),
    (1077, 'Ring', 'Diamond', 'HERITAGE', 'God', NULL, 'Moulding', NULL),
    (1078, 'Ring', 'Diamond', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (1079, 'Ring', 'Polki', 'HERITAGE', 'JADAU', NULL, 'Polki', 'Jadau'),
    (1080, 'Ring', 'Precious', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (1081, 'Ring', 'Precious', 'HERITAGE', 'Navaratna', NULL, 'Moulding', NULL),
    (1082, 'Ring', 'Uncut', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (1083, 'Ring', 'Gold 14K', 'ITALIAN', 'CERA', NULL, NULL, 'Cera'),
    (1084, 'Ring', 'Gold 14K', 'ITALIAN', 'CLASSIC', NULL, 'Italian', 'Fancy'),
    (1085, 'Ring', 'Gold 14K', 'ITALIAN', 'CUPOD', NULL, NULL, 'Cupod'),
    (1086, 'Ring', 'Gold 14K', 'ITALIAN', 'FLORA', NULL, NULL, 'Flora'),
    (1087, 'Ring', 'Gold 14K', 'ITALIAN', 'YIN-YANG', NULL, NULL, 'Yin-Yang'),
    (1088, 'Ring', 'Gold 22k', 'Karnataka', 'Karwar', NULL, 'Karnataka Traditional', NULL),
    (1089, 'Ring', 'Gold 22k', 'Karwar', 'Karwar', NULL, 'Karnataka Traditional', NULL),
    (1093, 'Ring', 'Gold 22k', 'Kerala', 'KATTI TV', NULL, NULL, 'Katti Tv'),
    (1095, 'Ring', 'Gold 22k', 'Kerala', 'MINCHI PIPE', NULL, NULL, 'Minchi Pipe'),
    (1103, 'Ring', 'Gold 22k', 'Kerala Special', 'Kerala', NULL, 'Kerala', 'Plain'),
    (1106, 'Ring', 'Gold 18K', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (1109, 'Ring', 'Gold 22k', 'Moulding', 'COUPLE', NULL, NULL, 'Couple'),
    (1112, 'Ring', 'Gold 22k', 'Moulding', 'Moulding', NULL, NULL, 'Fancy'),
    (1116, 'Ring', 'Gold 22k', 'Moulding', 'Papper Cast', NULL, NULL, 'Paper Cast'),
    (1118, 'Ring', 'Gold 22k', 'Moulding', 'RAINBOW', NULL, NULL, 'Rainbow'),
    (1119, 'Ring', 'Gold 22k', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (1122, 'Ring', 'Gold 22k', 'Moulding', 'Vangi', NULL, NULL, 'Vanki'),
    (1123, 'Ring', 'Gold 22k', 'Moulding', 'VANGI STONE', NULL, NULL, 'Vangi Stone'),
    (1124, 'Ring', 'Gold 18K', 'Nagas', 'MEENAKSHI', NULL, NULL, 'Meenakshi'),
    (1127, 'Ring', 'Gold 22k', 'Nagas', 'Nagas', NULL, NULL, 'Nakashi'),
    (1128, 'Ring', 'Gold 22k', 'Nagas', 'NAGAS NORMAL', NULL, NULL, 'Nakashi'),
    (1129, 'Ring', 'Gold 22k', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (1130, 'Ring', 'Gold 22k', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (1131, 'Ring', 'Gold 22k', 'Nagas', 'VANGI STONE', NULL, NULL, 'Vangi Stone'),
    (1132, 'Ring', 'Precious', 'Nagas', 'Vangi', NULL, NULL, 'Vanki'),
    (1134, 'Ring', 'Gold 22k', 'Nellore', 'Nellore', NULL, 'Karnataka Traditional', NULL),
    (1135, 'Ring', 'Gold 22k', 'Nellore', 'Stone', NULL, 'Karnataka Traditional', 'Nellore'),
    (1136, 'Ring', 'Platinum', 'Platinum', 'CLASSIC', NULL, NULL, 'Fancy'),
    (1137, 'Ring', 'Platinum', 'Platinum', 'Platinum', NULL, NULL, 'Fancy'),
    (1138, 'Ring', 'Platinum', 'Platinum', 'Platinum Fusion', NULL, NULL, 'Fusion'),
    (1139, 'Ring', 'Platinum', 'PLATINUM FUSION', 'CLASSIC', NULL, 'Platinum', 'Fusion'),
    (1140, 'Ring', 'Polki', 'Polki', 'Polki', NULL, NULL, 'Fancy'),
    (1143, 'Ring', 'Gold 22k', 'Rajkot', 'Rajkot', NULL, NULL, 'Plain'),
    (1144, 'Ring', 'Gold 22k', 'Rajkot', 'Rodium', NULL, NULL, 'Rhodium'),
    (1146, 'Ring', 'Diamond', 'SIGNATURE', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (1147, 'Ring', 'Diamond', 'SIGNATURE', 'CLUSTER', NULL, 'Moulding', 'Cluster'),
    (1148, 'Ring', 'Diamond', 'SIGNATURE', 'COUPLE', NULL, 'Moulding', 'Couple'),
    (1149, 'Ring', 'Diamond', 'SIGNATURE', 'PIE-CUT', NULL, 'Moulding', 'Pie-Cut'),
    (1150, 'Ring', 'Diamond', 'SIGNATURE', 'RADHA KRISHNA', NULL, 'Moulding', 'Radha Krishna'),
    (1151, 'Ring', 'Diamond', 'SIGNATURE', 'Twisted', NULL, 'Moulding', NULL),
    (1152, 'Ring', 'Diamond', 'SIGNATURE', 'Vangi', NULL, 'Moulding', 'Vanki'),
    (1153, 'Ring', 'Gold 22k', 'SIGNITY', 'CLOSED SETTING', NULL, NULL, 'Closed Setting'),
    (1154, 'Ring', 'Gold 22k', 'SIGNITY', 'Vangi', NULL, NULL, 'Vanki'),
    (1158, 'Ring', 'Gold 22k', 'Singapore', 'SINGAPORE STONE', NULL, NULL, 'Singapore Stone'),
    (1160, 'Ring', 'Diamond', 'SOLITAIRE', 'SOLITAIRE', NULL, 'Moulding', 'Solitaire'),
    (1161, 'Ring', 'Gold 22k', 'Traditional', 'Anavaal', NULL, 'Kerala Traditional', NULL),
    (1162, 'Ring', 'Gold 22k', 'Traditional', 'Palakka', NULL, 'Kerala Traditional', NULL),
    (1163, 'Ring', 'Gold 22k', 'Traditional', 'Traditional', NULL, 'Kerala Traditional', NULL),
    (1165, 'Ring', 'Gold 22k', 'Turkish', 'Rodium', NULL, NULL, 'Rhodium'),
    (1167, 'Ring', 'Precious', 'Turkish', 'GEMSTONE', NULL, NULL, 'Gemstone'),
    (1169, 'Stud', 'Gold 14K', '14 Carat Ornaments', '14 Karat Ornaments', NULL, '14 Kt Ornaments', NULL),
    (1170, 'Stud', 'Gold 14K', '14 Carat Ornaments', 'Diamond', NULL, '14 Kt Ornaments', 'Fancy'),
    (1171, 'Stud', 'Gold 18K', '18 Carat', '18 Karat', NULL, '18 Karat', NULL),
    (1172, 'Stud', 'Gold 22k', 'Antique', 'Antique', NULL, NULL, 'Fancy'),
    (1173, 'Stud', 'Gold 22k', 'Antique', 'Ilakka Thali', NULL, NULL, 'Elakkathali'),
    (1176, 'Stud', 'Gold 22k', 'Antique', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (1178, 'Stud', 'Gold 22k', 'BENGALI', 'Jimkka', NULL, 'Bombay', 'Jhumka'),
    (1179, 'Stud', 'Gold 22k', 'BENGALI', 'JIMKKA STONE', NULL, 'Bombay', 'Jhumka Stone'),
    (1180, 'Stud', 'Gold 22k', 'BENGALI', 'Plain', NULL, 'Bombay', NULL),
    (1181, 'Stud', 'Gold 22k', 'BENGALI', 'Rodium', NULL, 'Bombay', 'Rhodium'),
    (1182, 'Stud', 'Gold 22k', 'BENGALI', 'Stone', NULL, 'Bombay', NULL),
    (1183, 'Stud', 'Gold 22k', 'Bengali special', 'Bengali', NULL, 'Bombay', 'Plain'),
    (1184, 'Stud', 'Gold 22k', 'Bombay', 'Bombay', NULL, NULL, 'Plain'),
    (1186, 'Stud', 'Gold 22k', 'Bombay', 'Jimkka', NULL, NULL, 'Jhumka'),
    (1188, 'Stud', 'Gold 22k', 'Bombay', 'Rodium', NULL, NULL, 'Rhodium'),
    (1190, 'Stud', 'Diamond', 'BRIDAL', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (1191, 'Stud', 'Diamond', 'BRIDAL', 'Lakshmi', NULL, 'Moulding', NULL),
    (1193, 'Stud', 'Gold 22k', 'Chettinadu', 'CHAND BALI STONE', NULL, NULL, 'Chand Bali Stone'),
    (1194, 'Stud', 'Gold 22k', 'Chettinadu', 'Chettinadu', NULL, NULL, 'Nakashi'),
    (1195, 'Stud', 'Gold 22k', 'Chettinadu', 'Jimkka', NULL, NULL, 'Jhumka'),
    (1196, 'Stud', 'Gold 22k', 'Chettinadu', 'JIMKKA STONE', NULL, NULL, 'Jhumka Stone'),
    (1198, 'Stud', 'Gold 22k', 'Chettinadu', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (1200, 'Stud', 'Gold 22k', 'Coimbatore', 'BALI', NULL, NULL, 'Bali'),
    (1201, 'Stud', 'Gold 22k', 'Coimbatore', 'CBT NORMAL', NULL, NULL, 'Cbt'),
    (1202, 'Stud', 'Gold 22k', 'Coimbatore', 'CLOSED SETTING', NULL, NULL, 'Closed Setting'),
    (1203, 'Stud', 'Gold 22k', 'Coimbatore', 'Jimkka', NULL, NULL, 'Jhumka'),
    (1204, 'Stud', 'Gold 22k', 'Coimbatore', 'JIMKKA STONE', NULL, NULL, 'Jhumka Stone'),
    (1206, 'Stud', 'Gold 22k', 'Coimbatore', 'MATTE', NULL, NULL, 'Matte'),
    (1209, 'Stud', 'Gold 22k', 'Culcutta', 'Chand Bali', NULL, 'Kolkata', NULL),
    (1210, 'Stud', 'Gold 22k', 'Culcutta', 'CHAND BALI ENAMEL', NULL, 'Kolkata', 'Chand Bali Enamel'),
    (1211, 'Stud', 'Gold 22k', 'Culcutta', 'CHAND BALI STONE', NULL, 'Kolkata', 'Chand Bali Stone'),
    (1212, 'Stud', 'Gold 22k', 'Culcutta', 'Culcutta plain', NULL, 'Kolkata', 'Plain'),
    (1213, 'Stud', 'Gold 22k', 'Culcutta', 'Culcutta Stone', NULL, 'Kolkata', 'Stone'),
    (1214, 'Stud', 'Gold 22k', 'Culcutta', 'Enamel', NULL, 'Kolkata', NULL),
    (1215, 'Stud', 'Gold 22k', 'Culcutta', 'Jimkka', NULL, 'Kolkata', 'Jhumka'),
    (1216, 'Stud', 'Gold 22k', 'Culcutta', 'JIMKKA ENAMEL', NULL, 'Kolkata', 'Jhumka Enamel'),
    (1217, 'Stud', 'Gold 22k', 'Culcutta', 'JIMKKA STONE', NULL, 'Kolkata', 'Jhumka Stone'),
    (1218, 'Stud', 'Gold 22k', 'Culcutta', 'Plain', NULL, 'Kolkata', NULL),
    (1219, 'Stud', 'Gold 22k', 'Culcutta', 'Stone', NULL, 'Kolkata', NULL),
    (1220, 'Stud', 'Diamond', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (1221, 'Stud', 'Diamond', 'DESIGNER', 'CLUSTER', NULL, 'Moulding', 'Cluster'),
    (1222, 'Stud', 'Diamond', 'DESIGNER', 'Designer', NULL, 'Moulding', 'Fancy'),
    (1223, 'Stud', 'Gold 14K', 'DESIGNER', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (1224, 'Stud', 'Diamond', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (1225, 'Stud', 'Gold 14K', 'Diamond', 'Diamond', NULL, 'Moulding', 'Fancy'),
    (1226, 'Stud', 'Diamond', 'Diamond SI Jewellery', 'Diamond SI', NULL, 'Moulding', 'Fancy'),
    (1227, 'Stud', 'Diamond', 'HERITAGE', 'CLASSIC', NULL, 'Moulding', 'Classic'),
    (1228, 'Stud', 'Diamond', 'HERITAGE', 'CLOSED SETTING', NULL, 'Moulding', 'Closed Setting'),
    (1229, 'Stud', 'Diamond', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (1230, 'Stud', 'Diamond', 'HERITAGE', 'MEENAKSHI', NULL, 'Moulding', 'Meenakshi'),
    (1231, 'Stud', 'Diamond', 'HERITAGE', 'OPEN CLOSE SETTING', NULL, 'Moulding', 'Open Close Setting'),
    (1232, 'Stud', 'Diamond', 'HERITAGE', 'RAM PARIVAR', NULL, 'Moulding', 'Ram Parivar'),
    (1233, 'Stud', 'Polki', 'HERITAGE', 'JADAU', NULL, 'Polki', 'Jadau'),
    (1234, 'Stud', 'Precious', 'HERITAGE', 'FILIGREE', NULL, 'Moulding', 'Filigree'),
    (1235, 'Stud', 'Precious', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (1236, 'Stud', 'Uncut', 'HERITAGE', 'GEMSTONE', NULL, 'Moulding', 'Gemstone'),
    (1237, 'Stud', 'Uncut', 'HERITAGE', 'Jimkka', NULL, 'Moulding', 'Jhumka'),
    (1238, 'Stud', 'Uncut', 'HERITAGE', 'Lakshmi', NULL, 'Moulding', NULL),
    (1239, 'Stud', 'Gold 14K', 'ITALIAN', 'CERA', NULL, NULL, 'Cera'),
    (1240, 'Stud', 'Gold 14K', 'ITALIAN', 'CLASSIC', NULL, 'Italian', 'Fancy'),
    (1241, 'Stud', 'Gold 14K', 'ITALIAN', 'CUPOD', NULL, NULL, 'Cupod'),
    (1242, 'Stud', 'Gold 14K', 'ITALIAN', 'FLORA', NULL, NULL, 'Flora'),
    (1243, 'Stud', 'Gold 14K', 'ITALIAN', 'YIN-YANG', NULL, NULL, 'Yin-Yang'),
    (1245, 'Stud', 'Gold 18K', 'ITALIAN', 'Rodium', NULL, 'Italian', 'Rhodium'),
    (1247, 'Stud', 'Gold 22k', 'Karwar', 'Karwar', NULL, 'Karnataka Traditional', NULL),
    (1248, 'Stud', 'Gold 22k', 'Kerala', 'BALI', NULL, NULL, 'Bali'),
    (1250, 'Stud', 'Gold 22k', 'Kerala', 'Jimkka', NULL, NULL, 'Jhumka'),
    (1254, 'Stud', 'Gold 22k', 'Kerala', 'LAKSHMI STONE', NULL, NULL, 'Lakshmi Stone'),
    (1259, 'Stud', 'Gold 18K', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (1261, 'Stud', 'Gold 22k', 'Moulding', 'Moulding', NULL, NULL, 'Fancy'),
    (1264, 'Stud', 'Gold 22k', 'Moulding', 'RAINBOW', NULL, NULL, 'Rainbow'),
    (1265, 'Stud', 'Gold 22k', 'Moulding', 'Rodium', NULL, NULL, 'Rhodium'),
    (1268, 'Stud', 'Gold 18K', 'Nagas', 'MEENAKSHI', NULL, NULL, 'Meenakshi'),
    (1269, 'Stud', 'Gold 22k', 'Nagas', 'CHAND BALI GOD', NULL, NULL, 'Chand Bali God'),
    (1270, 'Stud', 'Gold 22k', 'Nagas', 'CHAND BALI LAKSHMI', NULL, NULL, 'Chand Bali Lakshmi'),
    (1271, 'Stud', 'Gold 22k', 'Nagas', 'CHAND BALI NAKSHI', NULL, NULL, 'Chand Bali Nakshi'),
    (1272, 'Stud', 'Gold 22k', 'Nagas', 'CHAND BALI RAM PARIVAR', NULL, NULL, 'Chand Bali Ram Parivar'),
    (1274, 'Stud', 'Gold 22k', 'Nagas', 'JIMKKA GOD', NULL, NULL, 'Jhumka God'),
    (1275, 'Stud', 'Gold 22k', 'Nagas', 'JIMKKA LAKSHMI', NULL, NULL, 'Jhumka Lakshmi'),
    (1276, 'Stud', 'Gold 22k', 'Nagas', 'JIMKKA NAKSHI', NULL, NULL, 'Jhumka Nakshi'),
    (1277, 'Stud', 'Gold 22k', 'Nagas', 'JIMKKA RAM PARIVAR', NULL, NULL, 'Jhumka Ram Parivar'),
    (1279, 'Stud', 'Gold 22k', 'Nagas', 'Nagas', NULL, NULL, 'Nakashi'),
    (1280, 'Stud', 'Gold 22k', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (1281, 'Stud', 'Gold 22k', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (1282, 'Stud', 'Gold 22k', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (1285, 'Stud', 'Precious', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (1286, 'Stud', 'Precious', 'Nagas', 'RADHA KRISHNA', NULL, NULL, 'Radha Krishna'),
    (1287, 'Stud', 'Precious', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (1289, 'Stud', 'Uncut', 'Nagas', 'NAKASHI', NULL, NULL, 'Nakashi'),
    (1290, 'Stud', 'Uncut', 'Nagas', 'RAM PARIVAR', NULL, NULL, 'Ram Parivar'),
    (1291, 'Stud', 'Gold 22k', 'Nagas Premium', 'Nagas', NULL, 'Nagas', 'Nakashi'),
    (1292, 'Stud', 'Gold 22k', 'Nagas Premium', 'NAGAS NORMAL', NULL, 'Nagas', 'Nakashi'),
    (1293, 'Stud', 'Gold 22k', 'Nagas Premium', 'special nagas', NULL, 'Nagas', 'Nakashi'),
    (1295, 'Stud', 'Gold 22k', 'Nellore', 'BALI', NULL, 'Karnataka Traditional', 'Nellore Bali'),
    (1296, 'Stud', 'Gold 22k', 'Nellore', 'Chand Bali', NULL, 'Karnataka Traditional', 'Nellore Chand Bali'),
    (1297, 'Stud', 'Gold 22k', 'Nellore', 'CHAND BALI LAKSHMI', NULL, 'Karnataka Traditional', 'Nellore Chand Bali'),
    (1298, 'Stud', 'Gold 22k', 'Nellore', 'God', NULL, 'Karnataka Traditional', 'Nellore God'),
    (1299, 'Stud', 'Gold 22k', 'Nellore', 'Jimkka', NULL, 'Karnataka Traditional', 'Nellore Jimkka'),
    (1300, 'Stud', 'Gold 22k', 'Nellore', 'JIMKKA GOD', NULL, 'Karnataka Traditional', 'Nellore Jimkka God'),
    (1301, 'Stud', 'Gold 22k', 'Nellore', 'JIMKKA LAKSHMI', NULL, 'Karnataka Traditional', 'Nellore Jimkka Lakshmi'),
    (1302, 'Stud', 'Gold 22k', 'Nellore', 'Lakshmi', NULL, 'Karnataka Traditional', 'Nellore Lakshmi'),
    (1303, 'Stud', 'Gold 22k', 'Nellore', 'NAKASHI', NULL, 'Karnataka Traditional', 'Nellore Nakashi'),
    (1304, 'Stud', 'Gold 22k', 'Nellore', 'Nellore', NULL, 'Karnataka Traditional', NULL),
    (1305, 'Stud', 'Gold 22k', 'Nellore', 'Stone', NULL, 'Karnataka Traditional', 'Nellore'),
    (1306, 'Stud', 'Platinum', 'Platinum', 'CLASSIC', NULL, NULL, 'Fancy'),
    (1307, 'Stud', 'Platinum', 'Platinum', 'Platinum', NULL, NULL, 'Fancy'),
    (1308, 'Stud', 'Platinum', 'Platinum', 'Platinum Fusion', NULL, NULL, 'Fusion'),
    (1309, 'Stud', 'Platinum', 'PLATINUM FUSION', 'CLASSIC', NULL, 'Platinum', 'Fusion'),
    (1311, 'Stud', 'Polki', 'Polki', 'Polki', NULL, NULL, 'Fancy'),
    (1313, 'Stud', 'Gold 22k', 'Rajkot', 'BALI', NULL, NULL, 'Bali'),
    (1315, 'Stud', 'Gold 22k', 'Rajkot', 'Rajkot', NULL, NULL, 'Plain'),
    (1316, 'Stud', 'Gold 22k', 'Rajkot', 'Rodium', NULL, NULL, 'Rhodium'),
    (1318, 'Stud', 'Gold 22k', 'Semi Antique', 'Semi Antique', NULL, NULL, 'Nakashi'),
    (1319, 'Stud', 'Gold 22k', 'Semi Turkish', 'Semi Turkish', NULL, NULL, 'Plain'),
    (1320, 'Stud', 'Diamond', 'SIGNATURE', 'BUGADI', NULL, 'Moulding', 'Bugadi'),
    (1321, 'Stud', 'Diamond', 'SIGNATURE', 'CLASSIC', NULL, 'Moulding', 'Fancy'),
    (1322, 'Stud', 'Diamond', 'SIGNATURE', 'CLUSTER', NULL, 'Moulding', 'Cluster'),
    (1323, 'Stud', 'Diamond', 'SIGNATURE', 'SOLITAIRE', NULL, 'Moulding', 'Solitaire'),
    (1324, 'Stud', 'Diamond', 'SIGNATURE', 'Twisted', NULL, 'Moulding', NULL),
    (1325, 'Stud', 'Gold 22k', 'SIGNITY', 'CLOSED SETTING', NULL, NULL, 'Closed Setting'),
    (1328, 'Stud', 'Gold 22k', 'Singapore', 'Rodium', NULL, NULL, 'Rhodium'),
    (1330, 'Stud', 'Gold 22k', 'Singapore', 'SINGAPORE STONE', NULL, NULL, 'Singapore Stone'),
    (1332, 'Stud', 'Diamond', 'SOLITAIRE', 'SOLITAIRE', NULL, 'Moulding', 'Solitaire'),
    (1333, 'Stud', 'Gold 22k', 'Traditional', 'Palakka', NULL, 'Kerala Traditional', NULL),
    (1334, 'Stud', 'Gold 22k', 'Traditional', 'Traditional', NULL, 'Kerala Traditional', NULL),
    (1336, 'Stud', 'Gold 22k', 'Turkish', 'Rodium', NULL, NULL, 'Rhodium'),
    (1340, 'Stud', 'Precious', 'Turkish', 'GEMSTONE', NULL, NULL, 'Gemstone');

-- Saved (expect: every product, every template, 896 rules).
SELECT (SELECT COUNT(*) FROM migration_check.product_before) AS products,
       (SELECT COUNT(*) FROM migration_check.product_before WHERE is_unsold) AS unsold_products,
       (SELECT COUNT(*) FROM migration_check.template_before) AS templates,
       (SELECT COUNT(*) FROM migration_check.enum_before) AS attribute_values,
       (SELECT COUNT(*) FROM migration_check.edge_before) AS hierarchy_edges,
       (SELECT COUNT(*) FROM migration_check.rules) AS rules;
